<?php
// auto-generated by sfPropelCrud
// date: 2008/05/20 12:53:27
$path_theme = sfConfig::get('theme_simad');
$base_path = sfConfig::get('base_simad');

use_helper('Object','jQuery');
?>
<!-- Contenedor Pagina -->
<div class="panel panel-gradient" data-collapsed="0">
  <div class="panel-heading">
    <div class="panel-title">
      Consultar Usuarios
    </div>    
  </div>

  <!-- Contenedor Contenido Formulario-->
  <div class="panel-body">      
    <?php 
        echo form_tag('usuario_firma/list',array('name'=>'consultar','method'=>'GET', 'role' => 'form', 'class' => 'form-horizontal form-groups-bordered validate'));
		$url_back = "";
        foreach ($filters as $key => $value) {
		  if(!empty($key) && !empty($value)){ 
			echo input_hidden_tag($key,$value);
			$url_back .= sprintf("&%s=%s",$key,$value); 
		  }		  
        }        
    ?>
    
    <div class="form-group">
	  <!-- Nombre -->
      <label for="Nombre" class="col-sm-1 control-label">Nombre:</label>
      <div class="col-sm-4">
        <?php
            echo input_tag('nombre', '', array('class'=>'form-control input-sm'));
        ?>
      </div>
      <!-- Apellido -->
      <label for="Apellido" class="col-sm-2 control-label">Apellido:</label>
      <div class="col-sm-4">
        <?php
            echo input_tag('apellido', '', array('class'=>'form-control input-sm'));
        ?>
      </div>
    </div>
    
    <div class="form-group">
	   <!-- UserName -->
      <label for="UserName" class="col-sm-1 control-label">User Name:</label>
      <div class="col-sm-4">
        <?php 
            echo input_tag('userName', '', array('class'=>'form-control input-sm'));
        ?>
      </div>
      <!-- Dependencia -->
      <label for="Dependencia" class="col-sm-2 control-label">Unidad Administrativa:</label>
      <div class="col-sm-4">
        <?php
            echo object_select_tag($dependencia, 'getDependenciaId', array ('peer_method'=>'getDependenciaAll','related_class' => 'Dependencia','class'=>'form-control input-sm select2','include_custom'=>'Seleccione...',));
        ?>
      </div>
    </div>
    
    <div class="form-group">      
      <!-- Regional -->
      <label for="Regional" class="col-sm-1 control-label">Regional:</label>
      <div class="col-sm-4">
        <?php
            echo object_select_tag($regional, 'getRegionalId', array ('related_class' => 'Regional','class'=>'form-control input-sm select2','include_custom'=>'Seleccione...',));
        ?>
      </div>
      <!-- Por Grupos -->
      <label for="Por_Grupos" class="col-sm-2 control-label">Por Grupos:</label>
      <div class="col-sm-4">
        <?php
            echo object_select_tag($grupos, 'getGrupousuariId', array ('related_class' => 'GrupoUsuario','class'=>'form-control input-sm','include_custom'=>'Seleccione...',));
        ?>
      </div>
    </div>
    
    <div class="form-group">
        <!-- Botonera -->
        <div class="col-sm-offset-4 col-sm-5">
            <button type="submit" class="btn btn-success">Consultar</button>
            <?php echo button_to('Deshacer','usuario_firma/consulta?a=1'.$url_back,array('class' => 'btn btn-red')); ?>
        </div>
    </div>
    <div class="clear"></div>    
    </form>
  </div>
</div>  