<?php



/**
 * This class defines the structure of the 'WORKFLOW_HISTORY' table.
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * jue 04 dic 2025 13:42:54
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class WorkflowHistoryTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.WorkflowHistoryTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('WORKFLOW_HISTORY');
        $this->setPhpName('WorkflowHistory');
        $this->setClassname('WorkflowHistory');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('WORKFLOWHISTORY_ID', 'WorkflowhistoryId', 'INTEGER', true, 4, null);
        $this->addForeignKey('WORKFLOWINSTANCE_ID', 'WorkflowinstanceId', 'INTEGER', 'WORKFLOW_INSTANCE', 'WORKFLOWINSTANCE_ID', true, 4, null);
        $this->addForeignKey('USUARIO_ID', 'UsuarioId', 'INTEGER', 'USUARIO', 'USUARIO_ID', true, 4, null);
        $this->addColumn('NODE_ID', 'NodeId', 'VARCHAR', true, 500, null);
        $this->addColumn('NODE_NAME', 'NodeName', 'VARCHAR', false, 500, null);
        $this->addColumn('NODE_TYPE', 'NodeType', 'VARCHAR', false, 100, null);
        $this->addColumn('ACTION', 'Action', 'VARCHAR', false, 100, null);
        $this->addColumn('TIEMPO_EJECUCION', 'TiempoEjecucion', 'INTEGER', false, 4, null);
        $this->addColumn('VARIABLES_BEFORE', 'VariablesBefore', 'LONGVARCHAR', false, 2147483646, null);
        $this->addColumn('VARIABLES_AFTER', 'VariablesAfter', 'LONGVARCHAR', false, 2147483646, null);
        $this->addColumn('COMENTARIOS', 'Comentarios', 'LONGVARCHAR', false, 2147483646, null);
        $this->addColumn('FECHA_CREACION', 'FechaCreacion', 'VARCHAR', false, 54, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('WorkflowInstance', 'WorkflowInstance', RelationMap::MANY_TO_ONE, array('WORKFLOWINSTANCE_ID' => 'WORKFLOWINSTANCE_ID', ), null, null);
        $this->addRelation('Usuario', 'Usuario', RelationMap::MANY_TO_ONE, array('USUARIO_ID' => 'USUARIO_ID', ), null, null);
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' =>  array (
  'form' => 'true',
  'filter' => 'true',
),
            'symfony_behaviors' =>  array (
),
        );
    } // getBehaviors()

} // WorkflowHistoryTableMap
