<?php
// auto-generated by sfPropelCrud
// date: 2008/04/10 16:19:04
$path_theme = sfConfig::get('theme_simad');
$base_path = sfConfig::get('base_simad');

use_helper('Object','jQuery');
?>
<div class="row">
  <div class="col-md-12">
    <!-- Contenedor Pagina -->
    <div class="panel panel-gradient" data-collapsed="0">      
      <div class="panel-heading">
        <div class="panel-title">
          Aceptar Transferencias Primarias
        </div>
      </div>
      <!-- Contenedor Contenido Formulario-->
      <div class="panel-body">
        <?php 
            echo form_tag('transferencia/transferAll', array('name'=>'form1', 'id'=>'form1','role' => 'form', 'class' => 'form-horizontal form-groups-bordered validate'));
            echo input_hidden_tag('localizacionunidaddocumental_id', $sf_params->get('localizacionunidaddocumental_id'));
        ?>
        
        <div class="form-group">
          <!-- Contenido -->
          <label for="contenido" class="col-sm-1 control-label">Nueva ubicacion</label>
          <div class="col-sm-9">
            <?php 
                echo input_tag('ubicacion', '', array('class' => 'form-control required')); 
            ?>
          </div>
        </div>
        
        <div class="form-group">
          <!-- Botonera -->
          <div class="col-sm-offset-4 col-sm-5">
            <button type="submit" class="btn btn-success">Aceptar Transferencia</button>&nbsp;
            <?php 
                echo button_to_function('Cerrar','javascript:parent.jQuery.ReloadAndCloseModalSIMAD();',array('class'=>'btn btn-red'));
            ?>
          </div>
        </div>
        <div class="clear"></div>
        </form>
      </div>
    </div>
  </div>
</div>