<?php
// auto-generated by sfPropelCrud
// date: 2008/09/14 10:55:07
?>
<?php //use_helper('Object') ?>
<?php //use_helper('jQuery')?>
<?php //echo form_tag('manual_tecnico/list', array('name'=>'form1','method'=>'GET')) ?>

<?php //echo object_input_hidden_tag($manual_tecnico, 'getManualtecnicoId') ?>
<?php //echo input_hidden_tag('documentacion_id',$documentacion_id) ?>
<?php //echo input_hidden_tag('documentacion_id',$documentacion_id) ?>
<!--<table width="99%" height="134" cellpadding="0" cellspacing="0" align="center">
<caption>
     Crear/Editar Manual Tecnico
</caption>
<tr> 
  <th height="20" colspan="6" class="nobgLeft" scope="col"></th>
</tr>-->
<tbody>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Especialidad:</th>
  <td colspan="4" class="Color"><?php echo object_select_tag($manual_tecnico, 'getEspecialidadId', array (
  'related_class' => 'Especialidad', 'include_custom'=>'--- Seleccione ---'
)) ?></td>
</tr>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Mencion De Edicion:</th>
  <td colspan="4" class="Color"><?php echo input_tag('mencionEdicion', '', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Material complemetario:</th>
  <td colspan="4" class="Color"><?php echo input_tag('materialComplementario', '', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">ISBN:</th>
  <td colspan="4" class="Color"><?php echo input_tag('isbn', '', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Notas contenido:</th>
  <td colspan="4" class="Color"><?php echo input_tag('notasContenido', '', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Version:</th>
  <td colspan="4" class="Color"><?php echo input_tag('version', '', array (
  'size' => 10,
)) ?></td>
</tr>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Paginacion:</th>
  <td colspan="4" class="Color"><?php echo input_tag('paginacion', '', array (
  'size' => 10,
)) ?></td>
</tr>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Volumen:</th>
  <td colspan="4" class="Color"><?php echo input_tag('volumen', '', array (
  'size' => 10,
)) ?></td>
</tr>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Ilustraciones:</th>
  <td colspan="4" class="Color"><?php echo checkbox_tag('ilustraciones', '', array (
)) ?></td>
</tr>
</tbody>
