<?php


/**
 * Base class that represents a query for the 'TIPO_MANUAL_FORMA' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * 09/22/23 12:54:05
 *
 * @method TipoManualFormaQuery orderByTipomanualformaId($order = Criteria::ASC) Order by the TIPOMANUALFORMA_ID column
 *
 * @method TipoManualFormaQuery groupByTipomanualformaId() Group by the TIPOMANUALFORMA_ID column
 *
 * @method TipoManualFormaQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method TipoManualFormaQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method TipoManualFormaQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method TipoManualFormaQuery leftJoinManualFormas($relationAlias = null) Adds a LEFT JOIN clause to the query using the ManualFormas relation
 * @method TipoManualFormaQuery rightJoinManualFormas($relationAlias = null) Adds a RIGHT JOIN clause to the query using the ManualFormas relation
 * @method TipoManualFormaQuery innerJoinManualFormas($relationAlias = null) Adds a INNER JOIN clause to the query using the ManualFormas relation
 *
 * @method TipoManualForma findOne(PropelPDO $con = null) Return the first TipoManualForma matching the query
 * @method TipoManualForma findOneOrCreate(PropelPDO $con = null) Return the first TipoManualForma matching the query, or a new TipoManualForma object populated from the query conditions when no match is found
 *
 *
 * @method array findByTipomanualformaId(int $TIPOMANUALFORMA_ID) Return TipoManualForma objects filtered by the TIPOMANUALFORMA_ID column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTipoManualFormaQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseTipoManualFormaQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = null, $modelName = null, $modelAlias = null)
    {
        if (null === $dbName) {
            $dbName = 'propel';
        }
        if (null === $modelName) {
            $modelName = 'TipoManualForma';
        }
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new TipoManualFormaQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param   TipoManualFormaQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return TipoManualFormaQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof TipoManualFormaQuery) {
            return $criteria;
        }
        $query = new TipoManualFormaQuery(null, null, $modelAlias);

        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query 
     * @param     PropelPDO $con an optional connection object
     *
     * @return   TipoManualForma|TipoManualForma[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = TipoManualFormaPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is already in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(TipoManualFormaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Alias of findPk to use instance pooling
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 TipoManualForma A model object, or null if the key is not found
     * @throws PropelException
     */
     public function findOneByTipomanualformaId($key, $con = null)
     {
        return $this->findPk($key, $con);
     }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 TipoManualForma A model object, or null if the key is not found
     * @throws PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT [TIPOMANUALFORMA_ID] FROM [TIPO_MANUAL_FORMA] WHERE [TIPOMANUALFORMA_ID] = :p0';
        try {
            $stmt = $con->prepare($sql);			
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new TipoManualForma();
            $obj->hydrate($row);
            TipoManualFormaPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return TipoManualForma|TipoManualForma[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|TipoManualForma[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return TipoManualFormaQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(TipoManualFormaPeer::TIPOMANUALFORMA_ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return TipoManualFormaQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(TipoManualFormaPeer::TIPOMANUALFORMA_ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the TIPOMANUALFORMA_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByTipomanualformaId(1234); // WHERE TIPOMANUALFORMA_ID = 1234
     * $query->filterByTipomanualformaId(array(12, 34)); // WHERE TIPOMANUALFORMA_ID IN (12, 34)
     * $query->filterByTipomanualformaId(array('min' => 12)); // WHERE TIPOMANUALFORMA_ID >= 12
     * $query->filterByTipomanualformaId(array('max' => 12)); // WHERE TIPOMANUALFORMA_ID <= 12
     * </code>
     *
     * @param     mixed $tipomanualformaId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TipoManualFormaQuery The current query, for fluid interface
     */
    public function filterByTipomanualformaId($tipomanualformaId = null, $comparison = null)
    {
        if (is_array($tipomanualformaId)) {
            $useMinMax = false;
            if (isset($tipomanualformaId['min'])) {
                $this->addUsingAlias(TipoManualFormaPeer::TIPOMANUALFORMA_ID, $tipomanualformaId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($tipomanualformaId['max'])) {
                $this->addUsingAlias(TipoManualFormaPeer::TIPOMANUALFORMA_ID, $tipomanualformaId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TipoManualFormaPeer::TIPOMANUALFORMA_ID, $tipomanualformaId, $comparison);
    }

    /**
     * Filter the query by a related ManualFormas object
     *
     * @param   ManualFormas|PropelObjectCollection $manualFormas  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 TipoManualFormaQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByManualFormas($manualFormas, $comparison = null)
    {
        if ($manualFormas instanceof ManualFormas) {
            return $this
                ->addUsingAlias(TipoManualFormaPeer::TIPOMANUALFORMA_ID, $manualFormas->getTipomanualformaId(), $comparison);
        } elseif ($manualFormas instanceof PropelObjectCollection) {
            return $this
                ->useManualFormasQuery()
                ->filterByPrimaryKeys($manualFormas->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterByManualFormas() only accepts arguments of type ManualFormas or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the ManualFormas relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return TipoManualFormaQuery The current query, for fluid interface
     */
    public function joinManualFormas($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('ManualFormas');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'ManualFormas');
        }

        return $this;
    }

    /**
     * Use the ManualFormas relation ManualFormas object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   ManualFormasQuery A secondary query class using the current class as primary query
     */
    public function useManualFormasQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinManualFormas($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'ManualFormas', 'ManualFormasQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   TipoManualForma $tipoManualForma Object to remove from the list of results
     *
     * @return TipoManualFormaQuery The current query, for fluid interface
     */
    public function prune($tipoManualForma = null)
    {
        if ($tipoManualForma) {
            $this->addUsingAlias(TipoManualFormaPeer::TIPOMANUALFORMA_ID, $tipoManualForma->getTipomanualformaId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
