<?php


/**
 * Base static class for performing query and update operations on the 'NOVEDADES' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * 09/22/23 12:53:46
 *
 * @package propel.generator.lib.model.om
 */
abstract class BaseNovedadesPeer
{

    /** the default database name for this class */
    const DATABASE_NAME = 'propel';

    /** the table name for this class */
    const TABLE_NAME = 'NOVEDADES';

    /** the related Propel class for this table */
    const OM_CLASS = 'Novedades';

    /** the related TableMap class for this table */
    const TM_CLASS = 'NovedadesTableMap';

    /** The total number of columns. */
    const NUM_COLUMNS = 19;

    /** The number of lazy-loaded columns. */
    const NUM_LAZY_LOAD_COLUMNS = 0;

    /** The number of columns to hydrate (NUM_COLUMNS - NUM_LAZY_LOAD_COLUMNS) */
    const NUM_HYDRATE_COLUMNS = 19;

    /** the column name for the NOVEDADES_ID field */
    const NOVEDADES_ID = 'NOVEDADES.NOVEDADES_ID';

    /** the column name for the USUARIO_ID field */
    const USUARIO_ID = 'NOVEDADES.USUARIO_ID';

    /** the column name for the MODULO_ID field */
    const MODULO_ID = 'NOVEDADES.MODULO_ID';

    /** the column name for the TIPOCONTROL_ID field */
    const TIPOCONTROL_ID = 'NOVEDADES.TIPOCONTROL_ID';

    /** the column name for the CODIGO_PRINCIPAL field */
    const CODIGO_PRINCIPAL = 'NOVEDADES.CODIGO_PRINCIPAL';

    /** the column name for the DESCRIPCION field */
    const DESCRIPCION = 'NOVEDADES.DESCRIPCION';

    /** the column name for the FECHA_CREACION field */
    const FECHA_CREACION = 'NOVEDADES.FECHA_CREACION';

    /** the column name for the RUTA field */
    const RUTA = 'NOVEDADES.RUTA';

    /** the column name for the REMITENTE field */
    const REMITENTE = 'NOVEDADES.REMITENTE';

    /** the column name for the DESTINATARIO field */
    const DESTINATARIO = 'NOVEDADES.DESTINATARIO';

    /** the column name for the VALOR_FACTURA field */
    const VALOR_FACTURA = 'NOVEDADES.VALOR_FACTURA';

    /** the column name for the TIPO_DOCUMENTO field */
    const TIPO_DOCUMENTO = 'NOVEDADES.TIPO_DOCUMENTO';

    /** the column name for the GUIA field */
    const GUIA = 'NOVEDADES.GUIA';

    /** the column name for the NUMERO_FACTURA field */
    const NUMERO_FACTURA = 'NOVEDADES.NUMERO_FACTURA';

    /** the column name for the ESTADO_APROBACION field */
    const ESTADO_APROBACION = 'NOVEDADES.ESTADO_APROBACION';

    /** the column name for the OBS_APROBACION field */
    const OBS_APROBACION = 'NOVEDADES.OBS_APROBACION';

    /** the column name for the USUARIO_APRUEBA field */
    const USUARIO_APRUEBA = 'NOVEDADES.USUARIO_APRUEBA';

    /** the column name for the USUARIO_DESTINO field */
    const USUARIO_DESTINO = 'NOVEDADES.USUARIO_DESTINO';

    /** the column name for the FECHA_APROBACION field */
    const FECHA_APROBACION = 'NOVEDADES.FECHA_APROBACION';

    /** The default string format for model objects of the related table **/
    const DEFAULT_STRING_FORMAT = 'YAML';

    /**
     * An identity map to hold any loaded instances of Novedades objects.
     * This must be public so that other peer classes can access this when hydrating from JOIN
     * queries.
     * @var        array Novedades[]
     */
    public static $instances = array();


    /**
     * holds an array of fieldnames
     *
     * first dimension keys are the type constants
     * e.g. NovedadesPeer::$fieldNames[NovedadesPeer::TYPE_PHPNAME][0] = 'Id'
     */
    protected static $fieldNames = array (
        BasePeer::TYPE_PHPNAME => array ('NovedadesId', 'UsuarioId', 'ModuloId', 'TipocontrolId', 'CodigoPrincipal', 'Descripcion', 'FechaCreacion', 'Ruta', 'Remitente', 'Destinatario', 'ValorFactura', 'TipoDocumento', 'Guia', 'NumeroFactura', 'EstadoAprobacion', 'ObsAprobacion', 'UsuarioAprueba', 'UsuarioDestino', 'FechaAprobacion', ),
        BasePeer::TYPE_STUDLYPHPNAME => array ('novedadesId', 'usuarioId', 'moduloId', 'tipocontrolId', 'codigoPrincipal', 'descripcion', 'fechaCreacion', 'ruta', 'remitente', 'destinatario', 'valorFactura', 'tipoDocumento', 'guia', 'numeroFactura', 'estadoAprobacion', 'obsAprobacion', 'usuarioAprueba', 'usuarioDestino', 'fechaAprobacion', ),
        BasePeer::TYPE_COLNAME => array (NovedadesPeer::NOVEDADES_ID, NovedadesPeer::USUARIO_ID, NovedadesPeer::MODULO_ID, NovedadesPeer::TIPOCONTROL_ID, NovedadesPeer::CODIGO_PRINCIPAL, NovedadesPeer::DESCRIPCION, NovedadesPeer::FECHA_CREACION, NovedadesPeer::RUTA, NovedadesPeer::REMITENTE, NovedadesPeer::DESTINATARIO, NovedadesPeer::VALOR_FACTURA, NovedadesPeer::TIPO_DOCUMENTO, NovedadesPeer::GUIA, NovedadesPeer::NUMERO_FACTURA, NovedadesPeer::ESTADO_APROBACION, NovedadesPeer::OBS_APROBACION, NovedadesPeer::USUARIO_APRUEBA, NovedadesPeer::USUARIO_DESTINO, NovedadesPeer::FECHA_APROBACION, ),
        BasePeer::TYPE_RAW_COLNAME => array ('NOVEDADES_ID', 'USUARIO_ID', 'MODULO_ID', 'TIPOCONTROL_ID', 'CODIGO_PRINCIPAL', 'DESCRIPCION', 'FECHA_CREACION', 'RUTA', 'REMITENTE', 'DESTINATARIO', 'VALOR_FACTURA', 'TIPO_DOCUMENTO', 'GUIA', 'NUMERO_FACTURA', 'ESTADO_APROBACION', 'OBS_APROBACION', 'USUARIO_APRUEBA', 'USUARIO_DESTINO', 'FECHA_APROBACION', ),
        BasePeer::TYPE_FIELDNAME => array ('NOVEDADES_ID', 'USUARIO_ID', 'MODULO_ID', 'TIPOCONTROL_ID', 'CODIGO_PRINCIPAL', 'DESCRIPCION', 'FECHA_CREACION', 'RUTA', 'REMITENTE', 'DESTINATARIO', 'VALOR_FACTURA', 'TIPO_DOCUMENTO', 'GUIA', 'NUMERO_FACTURA', 'ESTADO_APROBACION', 'OBS_APROBACION', 'USUARIO_APRUEBA', 'USUARIO_DESTINO', 'FECHA_APROBACION', ),
        BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, )
    );

    /**
     * holds an array of keys for quick access to the fieldnames array
     *
     * first dimension keys are the type constants
     * e.g. NovedadesPeer::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
     */
    protected static $fieldKeys = array (
        BasePeer::TYPE_PHPNAME => array ('NovedadesId' => 0, 'UsuarioId' => 1, 'ModuloId' => 2, 'TipocontrolId' => 3, 'CodigoPrincipal' => 4, 'Descripcion' => 5, 'FechaCreacion' => 6, 'Ruta' => 7, 'Remitente' => 8, 'Destinatario' => 9, 'ValorFactura' => 10, 'TipoDocumento' => 11, 'Guia' => 12, 'NumeroFactura' => 13, 'EstadoAprobacion' => 14, 'ObsAprobacion' => 15, 'UsuarioAprueba' => 16, 'UsuarioDestino' => 17, 'FechaAprobacion' => 18, ),
        BasePeer::TYPE_STUDLYPHPNAME => array ('novedadesId' => 0, 'usuarioId' => 1, 'moduloId' => 2, 'tipocontrolId' => 3, 'codigoPrincipal' => 4, 'descripcion' => 5, 'fechaCreacion' => 6, 'ruta' => 7, 'remitente' => 8, 'destinatario' => 9, 'valorFactura' => 10, 'tipoDocumento' => 11, 'guia' => 12, 'numeroFactura' => 13, 'estadoAprobacion' => 14, 'obsAprobacion' => 15, 'usuarioAprueba' => 16, 'usuarioDestino' => 17, 'fechaAprobacion' => 18, ),
        BasePeer::TYPE_COLNAME => array (NovedadesPeer::NOVEDADES_ID => 0, NovedadesPeer::USUARIO_ID => 1, NovedadesPeer::MODULO_ID => 2, NovedadesPeer::TIPOCONTROL_ID => 3, NovedadesPeer::CODIGO_PRINCIPAL => 4, NovedadesPeer::DESCRIPCION => 5, NovedadesPeer::FECHA_CREACION => 6, NovedadesPeer::RUTA => 7, NovedadesPeer::REMITENTE => 8, NovedadesPeer::DESTINATARIO => 9, NovedadesPeer::VALOR_FACTURA => 10, NovedadesPeer::TIPO_DOCUMENTO => 11, NovedadesPeer::GUIA => 12, NovedadesPeer::NUMERO_FACTURA => 13, NovedadesPeer::ESTADO_APROBACION => 14, NovedadesPeer::OBS_APROBACION => 15, NovedadesPeer::USUARIO_APRUEBA => 16, NovedadesPeer::USUARIO_DESTINO => 17, NovedadesPeer::FECHA_APROBACION => 18, ),
        BasePeer::TYPE_RAW_COLNAME => array ('NOVEDADES_ID' => 0, 'USUARIO_ID' => 1, 'MODULO_ID' => 2, 'TIPOCONTROL_ID' => 3, 'CODIGO_PRINCIPAL' => 4, 'DESCRIPCION' => 5, 'FECHA_CREACION' => 6, 'RUTA' => 7, 'REMITENTE' => 8, 'DESTINATARIO' => 9, 'VALOR_FACTURA' => 10, 'TIPO_DOCUMENTO' => 11, 'GUIA' => 12, 'NUMERO_FACTURA' => 13, 'ESTADO_APROBACION' => 14, 'OBS_APROBACION' => 15, 'USUARIO_APRUEBA' => 16, 'USUARIO_DESTINO' => 17, 'FECHA_APROBACION' => 18, ),
        BasePeer::TYPE_FIELDNAME => array ('NOVEDADES_ID' => 0, 'USUARIO_ID' => 1, 'MODULO_ID' => 2, 'TIPOCONTROL_ID' => 3, 'CODIGO_PRINCIPAL' => 4, 'DESCRIPCION' => 5, 'FECHA_CREACION' => 6, 'RUTA' => 7, 'REMITENTE' => 8, 'DESTINATARIO' => 9, 'VALOR_FACTURA' => 10, 'TIPO_DOCUMENTO' => 11, 'GUIA' => 12, 'NUMERO_FACTURA' => 13, 'ESTADO_APROBACION' => 14, 'OBS_APROBACION' => 15, 'USUARIO_APRUEBA' => 16, 'USUARIO_DESTINO' => 17, 'FECHA_APROBACION' => 18, ),
        BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, )
    );

    /**
     * Translates a fieldname to another type
     *
     * @param      string $name field name
     * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
     * @param      string $toType   One of the class type constants
     * @return string          translated name of the field.
     * @throws PropelException - if the specified name could not be found in the fieldname mappings.
     */
    public static function translateFieldName($name, $fromType, $toType)
    {
        $toNames = NovedadesPeer::getFieldNames($toType);
        $key = isset(NovedadesPeer::$fieldKeys[$fromType][$name]) ? NovedadesPeer::$fieldKeys[$fromType][$name] : null;
        if ($key === null) {
            throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(NovedadesPeer::$fieldKeys[$fromType], true));
        }

        return $toNames[$key];
    }

    /**
     * Returns an array of field names.
     *
     * @param      string $type The type of fieldnames to return:
     *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
     * @return array           A list of field names
     * @throws PropelException - if the type is not valid.
     */
    public static function getFieldNames($type = BasePeer::TYPE_PHPNAME)
    {
        if (!array_key_exists($type, NovedadesPeer::$fieldNames)) {
            throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
        }

        return NovedadesPeer::$fieldNames[$type];
    }

    /**
     * Convenience method which changes table.column to alias.column.
     *
     * Using this method you can maintain SQL abstraction while using column aliases.
     * <code>
     *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
     *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
     * </code>
     * @param      string $alias The alias for the current table.
     * @param      string $column The column name for current table. (i.e. NovedadesPeer::COLUMN_NAME).
     * @return string
     */
    public static function alias($alias, $column)
    {
        return str_replace(NovedadesPeer::TABLE_NAME.'.', $alias.'.', $column);
    }

    /**
     * Add all the columns needed to create a new object.
     *
     * Note: any columns that were marked with lazyLoad="true" in the
     * XML schema will not be added to the select list and only loaded
     * on demand.
     *
     * @param      Criteria $criteria object containing the columns to add.
     * @param      string   $alias    optional table alias
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function addSelectColumns(Criteria $criteria, $alias = null)
    {
        if (null === $alias) {
            $criteria->addSelectColumn(NovedadesPeer::NOVEDADES_ID);
            $criteria->addSelectColumn(NovedadesPeer::USUARIO_ID);
            $criteria->addSelectColumn(NovedadesPeer::MODULO_ID);
            $criteria->addSelectColumn(NovedadesPeer::TIPOCONTROL_ID);
            $criteria->addSelectColumn(NovedadesPeer::CODIGO_PRINCIPAL);
            $criteria->addSelectColumn(NovedadesPeer::DESCRIPCION);
            $criteria->addSelectColumn(NovedadesPeer::FECHA_CREACION);
            $criteria->addSelectColumn(NovedadesPeer::RUTA);
            $criteria->addSelectColumn(NovedadesPeer::REMITENTE);
            $criteria->addSelectColumn(NovedadesPeer::DESTINATARIO);
            $criteria->addSelectColumn(NovedadesPeer::VALOR_FACTURA);
            $criteria->addSelectColumn(NovedadesPeer::TIPO_DOCUMENTO);
            $criteria->addSelectColumn(NovedadesPeer::GUIA);
            $criteria->addSelectColumn(NovedadesPeer::NUMERO_FACTURA);
            $criteria->addSelectColumn(NovedadesPeer::ESTADO_APROBACION);
            $criteria->addSelectColumn(NovedadesPeer::OBS_APROBACION);
            $criteria->addSelectColumn(NovedadesPeer::USUARIO_APRUEBA);
            $criteria->addSelectColumn(NovedadesPeer::USUARIO_DESTINO);
            $criteria->addSelectColumn(NovedadesPeer::FECHA_APROBACION);
        } else {
            $criteria->addSelectColumn($alias . '.NOVEDADES_ID');
            $criteria->addSelectColumn($alias . '.USUARIO_ID');
            $criteria->addSelectColumn($alias . '.MODULO_ID');
            $criteria->addSelectColumn($alias . '.TIPOCONTROL_ID');
            $criteria->addSelectColumn($alias . '.CODIGO_PRINCIPAL');
            $criteria->addSelectColumn($alias . '.DESCRIPCION');
            $criteria->addSelectColumn($alias . '.FECHA_CREACION');
            $criteria->addSelectColumn($alias . '.RUTA');
            $criteria->addSelectColumn($alias . '.REMITENTE');
            $criteria->addSelectColumn($alias . '.DESTINATARIO');
            $criteria->addSelectColumn($alias . '.VALOR_FACTURA');
            $criteria->addSelectColumn($alias . '.TIPO_DOCUMENTO');
            $criteria->addSelectColumn($alias . '.GUIA');
            $criteria->addSelectColumn($alias . '.NUMERO_FACTURA');
            $criteria->addSelectColumn($alias . '.ESTADO_APROBACION');
            $criteria->addSelectColumn($alias . '.OBS_APROBACION');
            $criteria->addSelectColumn($alias . '.USUARIO_APRUEBA');
            $criteria->addSelectColumn($alias . '.USUARIO_DESTINO');
            $criteria->addSelectColumn($alias . '.FECHA_APROBACION');
        }
    }

    /**
     * Returns the number of rows matching criteria.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @return int Number of matching rows.
     */
    public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
    {
        // we may modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(NovedadesPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            NovedadesPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME); // Set the correct dbName

        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        // BasePeer returns a PDOStatement
        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }
    /**
     * Selects one object from the DB.
     *
     * @param      Criteria $criteria object used to create the SELECT statement.
     * @param      PropelPDO $con
     * @return Novedades
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
    {
        $critcopy = clone $criteria;
        $critcopy->setLimit(1);
        $objects = NovedadesPeer::doSelect($critcopy, $con);
        if ($objects) {
            return $objects[0];
        }

        return null;
    }
    /**
     * Selects several row from the DB.
     *
     * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
     * @param      PropelPDO $con
     * @return array           Array of selected Objects
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelect(Criteria $criteria, PropelPDO $con = null)
    {
        return NovedadesPeer::populateObjects(NovedadesPeer::doSelectStmt($criteria, $con));
    }
    /**
     * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
     *
     * Use this method directly if you want to work with an executed statement directly (for example
     * to perform your own object hydration).
     *
     * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
     * @param      PropelPDO $con The connection to use
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     * @return PDOStatement The executed PDOStatement object.
     * @see        BasePeer::doSelect()
     */
    public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        if (!$criteria->hasSelectClause()) {
            $criteria = clone $criteria;
            NovedadesPeer::addSelectColumns($criteria);
        }

        // Set the correct dbName
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME);
        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }


        // BasePeer returns a PDOStatement
        return BasePeer::doSelect($criteria, $con);
    }
    /**
     * Adds an object to the instance pool.
     *
     * Propel keeps cached copies of objects in an instance pool when they are retrieved
     * from the database.  In some cases -- especially when you override doSelect*()
     * methods in your stub classes -- you may need to explicitly add objects
     * to the cache in order to ensure that the same objects are always returned by doSelect*()
     * and retrieveByPK*() calls.
     *
     * @param Novedades $obj A Novedades object.
     * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
     */
    public static function addInstanceToPool($obj, $key = null)
    {
        if (Propel::isInstancePoolingEnabled()) {
            if ($key === null) {
                $key = (string) $obj->getNovedadesId();
            } // if key === null
            NovedadesPeer::$instances[$key] = $obj;
        }
    }

    /**
     * Removes an object from the instance pool.
     *
     * Propel keeps cached copies of objects in an instance pool when they are retrieved
     * from the database.  In some cases -- especially when you override doDelete
     * methods in your stub classes -- you may need to explicitly remove objects
     * from the cache in order to prevent returning objects that no longer exist.
     *
     * @param      mixed $value A Novedades object or a primary key value.
     *
     * @return void
     * @throws PropelException - if the value is invalid.
     */
    public static function removeInstanceFromPool($value)
    {
        if (Propel::isInstancePoolingEnabled() && $value !== null) {
            if (is_object($value) && $value instanceof Novedades) {
                $key = (string) $value->getNovedadesId();
            } elseif (is_scalar($value)) {
                // assume we've been passed a primary key
                $key = (string) $value;
            } else {
                $e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Novedades object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
                throw $e;
            }

            unset(NovedadesPeer::$instances[$key]);
        }
    } // removeInstanceFromPool()

    /**
     * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
     *
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, a serialize()d version of the primary key will be returned.
     *
     * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
     * @return Novedades Found object or null if 1) no instance exists for specified key or 2) instance pooling has been disabled.
     * @see        getPrimaryKeyHash()
     */
    public static function getInstanceFromPool($key)
    {
        if (Propel::isInstancePoolingEnabled()) {
            if (isset(NovedadesPeer::$instances[$key])) {
                return NovedadesPeer::$instances[$key];
            }
        }

        return null; // just to be explicit
    }
    
    /**
     * Clear the instance pool.
     *
     * @return void
     */
    public static function clearInstancePool($and_clear_all_references = false)
    {
      if ($and_clear_all_references) {
        foreach (NovedadesPeer::$instances as $instance) {
          $instance->clearAllReferences(true);
        }
      }
        NovedadesPeer::$instances = array();
    }
    
    /**
     * Method to invalidate the instance pool of all tables related to NOVEDADES
     * by a foreign key with ON DELETE CASCADE
     */
    public static function clearRelatedInstancePool()
    {
    }

    /**
     * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
     *
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, a serialize()d version of the primary key will be returned.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @return string A string version of PK or null if the components of primary key in result array are all null.
     */
    public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
    {
        // If the PK cannot be derived from the row, return null.
        if ($row[$startcol] === null) {
            return null;
        }

        return (string) $row[$startcol];
    }

    /**
     * Retrieves the primary key from the DB resultset row
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, an array of the primary key columns will be returned.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @return mixed The primary key of the row
     */
    public static function getPrimaryKeyFromRow($row, $startcol = 0)
    {

        return (int) $row[$startcol];
    }
    
    /**
     * The returned array will contain objects of the default type or
     * objects that inherit from the default.
     *
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function populateObjects(PDOStatement $stmt)
    {
        $results = array();
    
        // set the class once to avoid overhead in the loop
        $cls = NovedadesPeer::getOMClass();
        // populate the object(s)
        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key = NovedadesPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj = NovedadesPeer::getInstanceFromPool($key))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj->hydrate($row, 0, true); // rehydrate
                $results[] = $obj;
            } else {
                $obj = new $cls();
                $obj->hydrate($row);
                $results[] = $obj;
                NovedadesPeer::addInstanceToPool($obj, $key);
            } // if key exists
        }
        $stmt->closeCursor();

        return $results;
    }
    /**
     * Populates an object of the default type or an object that inherit from the default.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     * @return array (Novedades object, last column rank)
     */
    public static function populateObject($row, $startcol = 0)
    {
        $key = NovedadesPeer::getPrimaryKeyHashFromRow($row, $startcol);
        if (null !== ($obj = NovedadesPeer::getInstanceFromPool($key))) {
            // We no longer rehydrate the object, since this can cause data loss.
            // See http://www.propelorm.org/ticket/509
            // $obj->hydrate($row, $startcol, true); // rehydrate
            $col = $startcol + NovedadesPeer::NUM_HYDRATE_COLUMNS;
        } else {
            $cls = NovedadesPeer::OM_CLASS;
            $obj = new $cls();
            $col = $obj->hydrate($row, $startcol);
            NovedadesPeer::addInstanceToPool($obj, $key);
        }

        return array($obj, $col);
    }


    /**
     * Returns the number of rows matching criteria, joining the related Usuario table
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinUsuario(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(NovedadesPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            NovedadesPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

        // Set the correct dbName
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria->addJoin(NovedadesPeer::USUARIO_ID, UsuarioPeer::USUARIO_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }


    /**
     * Returns the number of rows matching criteria, joining the related Modulo table
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinModulo(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(NovedadesPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            NovedadesPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

        // Set the correct dbName
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria->addJoin(NovedadesPeer::MODULO_ID, ModuloPeer::MODULO_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }


    /**
     * Returns the number of rows matching criteria, joining the related TipoControl table
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinTipoControl(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(NovedadesPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            NovedadesPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

        // Set the correct dbName
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria->addJoin(NovedadesPeer::TIPOCONTROL_ID, TipoControlPeer::TIPOCONTROL_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }


    /**
     * Selects a collection of Novedades objects pre-filled with their Usuario objects.
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of Novedades objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinUsuario(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(NovedadesPeer::DATABASE_NAME);
        }

        NovedadesPeer::addSelectColumns($criteria);
        $startcol = NovedadesPeer::NUM_HYDRATE_COLUMNS;
        UsuarioPeer::addSelectColumns($criteria);

        $criteria->addJoin(NovedadesPeer::USUARIO_ID, UsuarioPeer::USUARIO_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = NovedadesPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = NovedadesPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {

                $cls = NovedadesPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                NovedadesPeer::addInstanceToPool($obj1, $key1);
            } // if $obj1 already loaded

            $key2 = UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol);
            if ($key2 !== null) {
                $obj2 = UsuarioPeer::getInstanceFromPool($key2);
                if (!$obj2) {

                    $cls = UsuarioPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol);
                    UsuarioPeer::addInstanceToPool($obj2, $key2);
                } // if obj2 already loaded

                // Add the $obj1 (Novedades) to $obj2 (Usuario)
                $obj2->addNovedades($obj1);

            } // if joined row was not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }


    /**
     * Selects a collection of Novedades objects pre-filled with their Modulo objects.
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of Novedades objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinModulo(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(NovedadesPeer::DATABASE_NAME);
        }

        NovedadesPeer::addSelectColumns($criteria);
        $startcol = NovedadesPeer::NUM_HYDRATE_COLUMNS;
        ModuloPeer::addSelectColumns($criteria);

        $criteria->addJoin(NovedadesPeer::MODULO_ID, ModuloPeer::MODULO_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = NovedadesPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = NovedadesPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {

                $cls = NovedadesPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                NovedadesPeer::addInstanceToPool($obj1, $key1);
            } // if $obj1 already loaded

            $key2 = ModuloPeer::getPrimaryKeyHashFromRow($row, $startcol);
            if ($key2 !== null) {
                $obj2 = ModuloPeer::getInstanceFromPool($key2);
                if (!$obj2) {

                    $cls = ModuloPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol);
                    ModuloPeer::addInstanceToPool($obj2, $key2);
                } // if obj2 already loaded

                // Add the $obj1 (Novedades) to $obj2 (Modulo)
                $obj2->addNovedades($obj1);

            } // if joined row was not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }


    /**
     * Selects a collection of Novedades objects pre-filled with their TipoControl objects.
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of Novedades objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinTipoControl(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(NovedadesPeer::DATABASE_NAME);
        }

        NovedadesPeer::addSelectColumns($criteria);
        $startcol = NovedadesPeer::NUM_HYDRATE_COLUMNS;
        TipoControlPeer::addSelectColumns($criteria);

        $criteria->addJoin(NovedadesPeer::TIPOCONTROL_ID, TipoControlPeer::TIPOCONTROL_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = NovedadesPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = NovedadesPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {

                $cls = NovedadesPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                NovedadesPeer::addInstanceToPool($obj1, $key1);
            } // if $obj1 already loaded

            $key2 = TipoControlPeer::getPrimaryKeyHashFromRow($row, $startcol);
            if ($key2 !== null) {
                $obj2 = TipoControlPeer::getInstanceFromPool($key2);
                if (!$obj2) {

                    $cls = TipoControlPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol);
                    TipoControlPeer::addInstanceToPool($obj2, $key2);
                } // if obj2 already loaded

                // Add the $obj1 (Novedades) to $obj2 (TipoControl)
                $obj2->addNovedades($obj1);

            } // if joined row was not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }


    /**
     * Returns the number of rows matching criteria, joining all related tables
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(NovedadesPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            NovedadesPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

        // Set the correct dbName
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria->addJoin(NovedadesPeer::USUARIO_ID, UsuarioPeer::USUARIO_ID, $join_behavior);

        $criteria->addJoin(NovedadesPeer::MODULO_ID, ModuloPeer::MODULO_ID, $join_behavior);

        $criteria->addJoin(NovedadesPeer::TIPOCONTROL_ID, TipoControlPeer::TIPOCONTROL_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }

    /**
     * Selects a collection of Novedades objects pre-filled with all related objects.
     *
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of Novedades objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(NovedadesPeer::DATABASE_NAME);
        }

        NovedadesPeer::addSelectColumns($criteria);
        $startcol2 = NovedadesPeer::NUM_HYDRATE_COLUMNS;

        UsuarioPeer::addSelectColumns($criteria);
        $startcol3 = $startcol2 + UsuarioPeer::NUM_HYDRATE_COLUMNS;

        ModuloPeer::addSelectColumns($criteria);
        $startcol4 = $startcol3 + ModuloPeer::NUM_HYDRATE_COLUMNS;

        TipoControlPeer::addSelectColumns($criteria);
        $startcol5 = $startcol4 + TipoControlPeer::NUM_HYDRATE_COLUMNS;

        $criteria->addJoin(NovedadesPeer::USUARIO_ID, UsuarioPeer::USUARIO_ID, $join_behavior);

        $criteria->addJoin(NovedadesPeer::MODULO_ID, ModuloPeer::MODULO_ID, $join_behavior);

        $criteria->addJoin(NovedadesPeer::TIPOCONTROL_ID, TipoControlPeer::TIPOCONTROL_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = NovedadesPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = NovedadesPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {
                $cls = NovedadesPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                NovedadesPeer::addInstanceToPool($obj1, $key1);
            } // if obj1 already loaded

            // Add objects for joined Usuario rows

            $key2 = UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol2);
            if ($key2 !== null) {
                $obj2 = UsuarioPeer::getInstanceFromPool($key2);
                if (!$obj2) {

                    $cls = UsuarioPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol2);
                    UsuarioPeer::addInstanceToPool($obj2, $key2);
                } // if obj2 loaded

                // Add the $obj1 (Novedades) to the collection in $obj2 (Usuario)
                $obj2->addNovedades($obj1);
            } // if joined row not null

            // Add objects for joined Modulo rows

            $key3 = ModuloPeer::getPrimaryKeyHashFromRow($row, $startcol3);
            if ($key3 !== null) {
                $obj3 = ModuloPeer::getInstanceFromPool($key3);
                if (!$obj3) {

                    $cls = ModuloPeer::getOMClass();

                    $obj3 = new $cls();
                    $obj3->hydrate($row, $startcol3);
                    ModuloPeer::addInstanceToPool($obj3, $key3);
                } // if obj3 loaded

                // Add the $obj1 (Novedades) to the collection in $obj3 (Modulo)
                $obj3->addNovedades($obj1);
            } // if joined row not null

            // Add objects for joined TipoControl rows

            $key4 = TipoControlPeer::getPrimaryKeyHashFromRow($row, $startcol4);
            if ($key4 !== null) {
                $obj4 = TipoControlPeer::getInstanceFromPool($key4);
                if (!$obj4) {

                    $cls = TipoControlPeer::getOMClass();

                    $obj4 = new $cls();
                    $obj4->hydrate($row, $startcol4);
                    TipoControlPeer::addInstanceToPool($obj4, $key4);
                } // if obj4 loaded

                // Add the $obj1 (Novedades) to the collection in $obj4 (TipoControl)
                $obj4->addNovedades($obj1);
            } // if joined row not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }


    /**
     * Returns the number of rows matching criteria, joining the related Usuario table
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinAllExceptUsuario(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(NovedadesPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            NovedadesPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY should not affect count

        // Set the correct dbName
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
    
        $criteria->addJoin(NovedadesPeer::MODULO_ID, ModuloPeer::MODULO_ID, $join_behavior);

        $criteria->addJoin(NovedadesPeer::TIPOCONTROL_ID, TipoControlPeer::TIPOCONTROL_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }


    /**
     * Returns the number of rows matching criteria, joining the related Modulo table
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinAllExceptModulo(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(NovedadesPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            NovedadesPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY should not affect count

        // Set the correct dbName
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
    
        $criteria->addJoin(NovedadesPeer::USUARIO_ID, UsuarioPeer::USUARIO_ID, $join_behavior);

        $criteria->addJoin(NovedadesPeer::TIPOCONTROL_ID, TipoControlPeer::TIPOCONTROL_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }


    /**
     * Returns the number of rows matching criteria, joining the related TipoControl table
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinAllExceptTipoControl(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(NovedadesPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            NovedadesPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY should not affect count

        // Set the correct dbName
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
    
        $criteria->addJoin(NovedadesPeer::USUARIO_ID, UsuarioPeer::USUARIO_ID, $join_behavior);

        $criteria->addJoin(NovedadesPeer::MODULO_ID, ModuloPeer::MODULO_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }


    /**
     * Selects a collection of Novedades objects pre-filled with all related objects except Usuario.
     *
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of Novedades objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinAllExceptUsuario(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        // $criteria->getDbName() will return the same object if not set to another value
        // so == check is okay and faster
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(NovedadesPeer::DATABASE_NAME);
        }

        NovedadesPeer::addSelectColumns($criteria);
        $startcol2 = NovedadesPeer::NUM_HYDRATE_COLUMNS;

        ModuloPeer::addSelectColumns($criteria);
        $startcol3 = $startcol2 + ModuloPeer::NUM_HYDRATE_COLUMNS;

        TipoControlPeer::addSelectColumns($criteria);
        $startcol4 = $startcol3 + TipoControlPeer::NUM_HYDRATE_COLUMNS;

        $criteria->addJoin(NovedadesPeer::MODULO_ID, ModuloPeer::MODULO_ID, $join_behavior);

        $criteria->addJoin(NovedadesPeer::TIPOCONTROL_ID, TipoControlPeer::TIPOCONTROL_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }


        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = NovedadesPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = NovedadesPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {
                $cls = NovedadesPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                NovedadesPeer::addInstanceToPool($obj1, $key1);
            } // if obj1 already loaded

                // Add objects for joined Modulo rows

                $key2 = ModuloPeer::getPrimaryKeyHashFromRow($row, $startcol2);
                if ($key2 !== null) {
                    $obj2 = ModuloPeer::getInstanceFromPool($key2);
                    if (!$obj2) {
    
                        $cls = ModuloPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol2);
                    ModuloPeer::addInstanceToPool($obj2, $key2);
                } // if $obj2 already loaded

                // Add the $obj1 (Novedades) to the collection in $obj2 (Modulo)
                $obj2->addNovedades($obj1);

            } // if joined row is not null

                // Add objects for joined TipoControl rows

                $key3 = TipoControlPeer::getPrimaryKeyHashFromRow($row, $startcol3);
                if ($key3 !== null) {
                    $obj3 = TipoControlPeer::getInstanceFromPool($key3);
                    if (!$obj3) {
    
                        $cls = TipoControlPeer::getOMClass();

                    $obj3 = new $cls();
                    $obj3->hydrate($row, $startcol3);
                    TipoControlPeer::addInstanceToPool($obj3, $key3);
                } // if $obj3 already loaded

                // Add the $obj1 (Novedades) to the collection in $obj3 (TipoControl)
                $obj3->addNovedades($obj1);

            } // if joined row is not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }


    /**
     * Selects a collection of Novedades objects pre-filled with all related objects except Modulo.
     *
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of Novedades objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinAllExceptModulo(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        // $criteria->getDbName() will return the same object if not set to another value
        // so == check is okay and faster
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(NovedadesPeer::DATABASE_NAME);
        }

        NovedadesPeer::addSelectColumns($criteria);
        $startcol2 = NovedadesPeer::NUM_HYDRATE_COLUMNS;

        UsuarioPeer::addSelectColumns($criteria);
        $startcol3 = $startcol2 + UsuarioPeer::NUM_HYDRATE_COLUMNS;

        TipoControlPeer::addSelectColumns($criteria);
        $startcol4 = $startcol3 + TipoControlPeer::NUM_HYDRATE_COLUMNS;

        $criteria->addJoin(NovedadesPeer::USUARIO_ID, UsuarioPeer::USUARIO_ID, $join_behavior);

        $criteria->addJoin(NovedadesPeer::TIPOCONTROL_ID, TipoControlPeer::TIPOCONTROL_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }


        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = NovedadesPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = NovedadesPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {
                $cls = NovedadesPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                NovedadesPeer::addInstanceToPool($obj1, $key1);
            } // if obj1 already loaded

                // Add objects for joined Usuario rows

                $key2 = UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol2);
                if ($key2 !== null) {
                    $obj2 = UsuarioPeer::getInstanceFromPool($key2);
                    if (!$obj2) {
    
                        $cls = UsuarioPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol2);
                    UsuarioPeer::addInstanceToPool($obj2, $key2);
                } // if $obj2 already loaded

                // Add the $obj1 (Novedades) to the collection in $obj2 (Usuario)
                $obj2->addNovedades($obj1);

            } // if joined row is not null

                // Add objects for joined TipoControl rows

                $key3 = TipoControlPeer::getPrimaryKeyHashFromRow($row, $startcol3);
                if ($key3 !== null) {
                    $obj3 = TipoControlPeer::getInstanceFromPool($key3);
                    if (!$obj3) {
    
                        $cls = TipoControlPeer::getOMClass();

                    $obj3 = new $cls();
                    $obj3->hydrate($row, $startcol3);
                    TipoControlPeer::addInstanceToPool($obj3, $key3);
                } // if $obj3 already loaded

                // Add the $obj1 (Novedades) to the collection in $obj3 (TipoControl)
                $obj3->addNovedades($obj1);

            } // if joined row is not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }


    /**
     * Selects a collection of Novedades objects pre-filled with all related objects except TipoControl.
     *
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of Novedades objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinAllExceptTipoControl(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        // $criteria->getDbName() will return the same object if not set to another value
        // so == check is okay and faster
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(NovedadesPeer::DATABASE_NAME);
        }

        NovedadesPeer::addSelectColumns($criteria);
        $startcol2 = NovedadesPeer::NUM_HYDRATE_COLUMNS;

        UsuarioPeer::addSelectColumns($criteria);
        $startcol3 = $startcol2 + UsuarioPeer::NUM_HYDRATE_COLUMNS;

        ModuloPeer::addSelectColumns($criteria);
        $startcol4 = $startcol3 + ModuloPeer::NUM_HYDRATE_COLUMNS;

        $criteria->addJoin(NovedadesPeer::USUARIO_ID, UsuarioPeer::USUARIO_ID, $join_behavior);

        $criteria->addJoin(NovedadesPeer::MODULO_ID, ModuloPeer::MODULO_ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseNovedadesPeer', $criteria, $con);
        }


        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = NovedadesPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = NovedadesPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {
                $cls = NovedadesPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                NovedadesPeer::addInstanceToPool($obj1, $key1);
            } // if obj1 already loaded

                // Add objects for joined Usuario rows

                $key2 = UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol2);
                if ($key2 !== null) {
                    $obj2 = UsuarioPeer::getInstanceFromPool($key2);
                    if (!$obj2) {
    
                        $cls = UsuarioPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol2);
                    UsuarioPeer::addInstanceToPool($obj2, $key2);
                } // if $obj2 already loaded

                // Add the $obj1 (Novedades) to the collection in $obj2 (Usuario)
                $obj2->addNovedades($obj1);

            } // if joined row is not null

                // Add objects for joined Modulo rows

                $key3 = ModuloPeer::getPrimaryKeyHashFromRow($row, $startcol3);
                if ($key3 !== null) {
                    $obj3 = ModuloPeer::getInstanceFromPool($key3);
                    if (!$obj3) {
    
                        $cls = ModuloPeer::getOMClass();

                    $obj3 = new $cls();
                    $obj3->hydrate($row, $startcol3);
                    ModuloPeer::addInstanceToPool($obj3, $key3);
                } // if $obj3 already loaded

                // Add the $obj1 (Novedades) to the collection in $obj3 (Modulo)
                $obj3->addNovedades($obj1);

            } // if joined row is not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }

    /**
     * Returns the TableMap related to this peer.
     * This method is not needed for general use but a specific application could have a need.
     * @return TableMap
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function getTableMap()
    {
        return Propel::getDatabaseMap(NovedadesPeer::DATABASE_NAME)->getTable(NovedadesPeer::TABLE_NAME);
    }

    /**
     * Add a TableMap instance to the database for this peer class.
     */
    public static function buildTableMap()
    {
      $dbMap = Propel::getDatabaseMap(BaseNovedadesPeer::DATABASE_NAME);
      if (!$dbMap->hasTable(BaseNovedadesPeer::TABLE_NAME)) {
        $dbMap->addTableObject(new \NovedadesTableMap());
      }
    }

    /**
     * The class that the Peer will make instances of.
     *
     *
     * @return string ClassName
     */
    public static function getOMClass($row = 0, $colnum = 0)
    {
        return NovedadesPeer::OM_CLASS;
    }

    /**
     * Performs an INSERT on the database, given a Novedades or Criteria object.
     *
     * @param      mixed $values Criteria or Novedades object containing data that is used to create the INSERT statement.
     * @param      PropelPDO $con the PropelPDO connection to use
     * @return mixed           The new primary key.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doInsert($values, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        if ($values instanceof Criteria) {
            $criteria = clone $values; // rename for clarity
        } else {
            $criteria = $values->buildCriteria(); // build Criteria from Novedades object
        }

        if ($criteria->containsKey(NovedadesPeer::NOVEDADES_ID) && $criteria->keyContainsValue(NovedadesPeer::NOVEDADES_ID) ) {
            throw new PropelException('Cannot insert a value for auto-increment primary key ('.NovedadesPeer::NOVEDADES_ID.')');
        }

        // remove pkey col since this table uses auto-increment and passing a null value for it is not valid
        $criteria->remove(NovedadesPeer::NOVEDADES_ID);


        // Set the correct dbName
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME);

        try {
            // use transaction because $criteria could contain info
            // for more than one table (I guess, conceivably)
            $con->beginTransaction();
            $pk = BasePeer::doInsert($criteria, $con);
            $con->commit();
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }

        return $pk;
    }

    /**
     * Performs an UPDATE on the database, given a Novedades or Criteria object.
     *
     * @param      mixed $values Criteria or Novedades object containing data that is used to create the UPDATE statement.
     * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
     * @return int             The number of affected rows (if supported by underlying database driver).
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doUpdate($values, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $selectCriteria = new Criteria(NovedadesPeer::DATABASE_NAME);

        if ($values instanceof Criteria) {
            $criteria = clone $values; // rename for clarity

            $comparison = $criteria->getComparison(NovedadesPeer::NOVEDADES_ID);
            $value = $criteria->remove(NovedadesPeer::NOVEDADES_ID);
            if ($value) {
                $selectCriteria->add(NovedadesPeer::NOVEDADES_ID, $value, $comparison);
            } else {
                $selectCriteria->setPrimaryTableName(NovedadesPeer::TABLE_NAME);
            }

        } else { // $values is Novedades object
            $criteria = $values->buildCriteria(); // gets full criteria
            $selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
        }

        // set the correct dbName
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME);

        return BasePeer::doUpdate($selectCriteria, $criteria, $con);
    }

    /**
     * Deletes all rows from the NOVEDADES table.
     *
     * @param      PropelPDO $con the connection to use
     * @return int             The number of affected rows (if supported by underlying database driver).
     * @throws PropelException
     */
    public static function doDeleteAll(PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }
        $affectedRows = 0; // initialize var to track total num of affected rows
        try {
            // use transaction because $criteria could contain info
            // for more than one table or we could emulating ON DELETE CASCADE, etc.
            $con->beginTransaction();
            $affectedRows += BasePeer::doDeleteAll(NovedadesPeer::TABLE_NAME, $con, NovedadesPeer::DATABASE_NAME);
            // Because this db requires some delete cascade/set null emulation, we have to
            // clear the cached instance *after* the emulation has happened (since
            // instances get re-added by the select statement contained therein).
            NovedadesPeer::clearInstancePool();
            NovedadesPeer::clearRelatedInstancePool();
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs a DELETE on the database, given a Novedades or Criteria object OR a primary key value.
     *
     * @param      mixed $values Criteria or Novedades object or primary key or array of primary keys
     *              which is used to create the DELETE statement
     * @param      PropelPDO $con the connection to use
     * @return int The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
     *				if supported by native driver or if emulated using Propel.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
     public static function doDelete($values, PropelPDO $con = null)
     {
        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        if ($values instanceof Criteria) {
            // invalidate the cache for all objects of this type, since we have no
            // way of knowing (without running a query) what objects should be invalidated
            // from the cache based on this Criteria.
            NovedadesPeer::clearInstancePool();
            // rename for clarity
            $criteria = clone $values;
        } elseif ($values instanceof Novedades) { // it's a model object
            // invalidate the cache for this single object
            NovedadesPeer::removeInstanceFromPool($values);
            // create criteria based on pk values
            $criteria = $values->buildPkeyCriteria();
        } else { // it's a primary key, or an array of pks
            $criteria = new Criteria(NovedadesPeer::DATABASE_NAME);
            $criteria->add(NovedadesPeer::NOVEDADES_ID, (array) $values, Criteria::IN);
            // invalidate the cache for this object(s)
            foreach ((array) $values as $singleval) {
                NovedadesPeer::removeInstanceFromPool($singleval);
            }
        }

        // Set the correct dbName
        $criteria->setDbName(NovedadesPeer::DATABASE_NAME);

        $affectedRows = 0; // initialize var to track total num of affected rows

        try {
            // use transaction because $criteria could contain info
            // for more than one table or we could emulating ON DELETE CASCADE, etc.
            $con->beginTransaction();
            
            $affectedRows += BasePeer::doDelete($criteria, $con);
            NovedadesPeer::clearRelatedInstancePool();
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Validates all modified columns of given Novedades object.
     * If parameter $columns is either a single column name or an array of column names
     * than only those columns are validated.
     *
     * NOTICE: This does not apply to primary or foreign keys for now.
     *
     * @param Novedades $obj The object to validate.
     * @param      mixed $cols Column name or array of column names.
     *
     * @return mixed TRUE if all columns are valid or the error message of the first invalid column.
     */
    public static function doValidate($obj, $cols = null)
    {
        $columns = array();

        if ($cols) {
            $dbMap = Propel::getDatabaseMap(NovedadesPeer::DATABASE_NAME);
            $tableMap = $dbMap->getTable(NovedadesPeer::TABLE_NAME);

            if (! is_array($cols)) {
                $cols = array($cols);
            }

            foreach ($cols as $colName) {
                if ($tableMap->hasColumn($colName)) {
                    $get = 'get' . $tableMap->getColumn($colName)->getPhpName();
                    $columns[$colName] = $obj->$get();
                }
            }
        } else {

        }

        return BasePeer::doValidate(NovedadesPeer::DATABASE_NAME, NovedadesPeer::TABLE_NAME, $columns);
    }

    /**
     * Retrieve a single object by pkey.
     *
     * @param int $pk the primary key.
     * @param      PropelPDO $con the connection to use
     * @return Novedades
     */
    public static function retrieveByPK($pk, PropelPDO $con = null)
    {

        if (null !== ($obj = NovedadesPeer::getInstanceFromPool((string) $pk))) {
            return $obj;
        }

        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria = new Criteria(NovedadesPeer::DATABASE_NAME);
        $criteria->add(NovedadesPeer::NOVEDADES_ID, $pk);

        $v = NovedadesPeer::doSelect($criteria, $con);

        return !empty($v) > 0 ? $v[0] : null;
    }

    /**
     * Retrieve multiple objects by pkey.
     *
     * @param      array $pks List of primary keys
     * @param      PropelPDO $con the connection to use
     * @return Novedades[]
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function retrieveByPKs($pks, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(NovedadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $objs = null;
        if (empty($pks)) {
            $objs = array();
        } else {
            $criteria = new Criteria(NovedadesPeer::DATABASE_NAME);
            $criteria->add(NovedadesPeer::NOVEDADES_ID, $pks, Criteria::IN);
            $objs = NovedadesPeer::doSelect($criteria, $con);
        }

        return $objs;
    }

    // symfony behavior
    
    /**
     * Returns an array of arrays that contain columns in each unique index.
     *
     * @return array
     */
    static public function getUniqueColumnNames()
    {
      return array();
    }

    // symfony_behaviors behavior
    
    /**
     * Returns the name of the hook to call from inside the supplied method.
     *
     * @param string $method The calling method
     *
     * @return string A hook name for {@link sfMixer}
     *
     * @throws LogicException If the method name is not recognized
     */
    static private function getMixerPreSelectHook($method)
    {
      if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
      {
        return sprintf('BaseNovedadesPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
      }
    
      throw new LogicException(sprintf('Unrecognized function "%s"', $method));
    }

} // BaseNovedadesPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseNovedadesPeer::buildTableMap();

