<?php


/**
 * Base class that represents a query for the 'DETALLE_PRESTAMO' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * 09/22/23 12:54:12
 *
 * @method DetallePrestamoQuery orderByDetalleprestamoId($order = Criteria::ASC) Order by the DETALLEPRESTAMO_ID column
 * @method DetallePrestamoQuery orderByPrestamoId($order = Criteria::ASC) Order by the PRESTAMO_ID column
 * @method DetallePrestamoQuery orderByEstadoprestamoId($order = Criteria::ASC) Order by the ESTADOPRESTAMO_ID column
 * @method DetallePrestamoQuery orderBySolicitudprestamoId($order = Criteria::ASC) Order by the SOLICITUDPRESTAMO_ID column
 *
 * @method DetallePrestamoQuery groupByDetalleprestamoId() Group by the DETALLEPRESTAMO_ID column
 * @method DetallePrestamoQuery groupByPrestamoId() Group by the PRESTAMO_ID column
 * @method DetallePrestamoQuery groupByEstadoprestamoId() Group by the ESTADOPRESTAMO_ID column
 * @method DetallePrestamoQuery groupBySolicitudprestamoId() Group by the SOLICITUDPRESTAMO_ID column
 *
 * @method DetallePrestamoQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method DetallePrestamoQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method DetallePrestamoQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method DetallePrestamoQuery leftJoinPrestamo($relationAlias = null) Adds a LEFT JOIN clause to the query using the Prestamo relation
 * @method DetallePrestamoQuery rightJoinPrestamo($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Prestamo relation
 * @method DetallePrestamoQuery innerJoinPrestamo($relationAlias = null) Adds a INNER JOIN clause to the query using the Prestamo relation
 *
 * @method DetallePrestamoQuery leftJoinEstadoPrestamo($relationAlias = null) Adds a LEFT JOIN clause to the query using the EstadoPrestamo relation
 * @method DetallePrestamoQuery rightJoinEstadoPrestamo($relationAlias = null) Adds a RIGHT JOIN clause to the query using the EstadoPrestamo relation
 * @method DetallePrestamoQuery innerJoinEstadoPrestamo($relationAlias = null) Adds a INNER JOIN clause to the query using the EstadoPrestamo relation
 *
 * @method DetallePrestamoQuery leftJoinSolicitudPrestamo($relationAlias = null) Adds a LEFT JOIN clause to the query using the SolicitudPrestamo relation
 * @method DetallePrestamoQuery rightJoinSolicitudPrestamo($relationAlias = null) Adds a RIGHT JOIN clause to the query using the SolicitudPrestamo relation
 * @method DetallePrestamoQuery innerJoinSolicitudPrestamo($relationAlias = null) Adds a INNER JOIN clause to the query using the SolicitudPrestamo relation
 *
 * @method DetallePrestamo findOne(PropelPDO $con = null) Return the first DetallePrestamo matching the query
 * @method DetallePrestamo findOneOrCreate(PropelPDO $con = null) Return the first DetallePrestamo matching the query, or a new DetallePrestamo object populated from the query conditions when no match is found
 *
 * @method DetallePrestamo findOneByPrestamoId(int $PRESTAMO_ID) Return the first DetallePrestamo filtered by the PRESTAMO_ID column
 * @method DetallePrestamo findOneByEstadoprestamoId(int $ESTADOPRESTAMO_ID) Return the first DetallePrestamo filtered by the ESTADOPRESTAMO_ID column
 * @method DetallePrestamo findOneBySolicitudprestamoId(int $SOLICITUDPRESTAMO_ID) Return the first DetallePrestamo filtered by the SOLICITUDPRESTAMO_ID column
 *
 * @method array findByDetalleprestamoId(int $DETALLEPRESTAMO_ID) Return DetallePrestamo objects filtered by the DETALLEPRESTAMO_ID column
 * @method array findByPrestamoId(int $PRESTAMO_ID) Return DetallePrestamo objects filtered by the PRESTAMO_ID column
 * @method array findByEstadoprestamoId(int $ESTADOPRESTAMO_ID) Return DetallePrestamo objects filtered by the ESTADOPRESTAMO_ID column
 * @method array findBySolicitudprestamoId(int $SOLICITUDPRESTAMO_ID) Return DetallePrestamo objects filtered by the SOLICITUDPRESTAMO_ID column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseDetallePrestamoQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseDetallePrestamoQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = null, $modelName = null, $modelAlias = null)
    {
        if (null === $dbName) {
            $dbName = 'propel';
        }
        if (null === $modelName) {
            $modelName = 'DetallePrestamo';
        }
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new DetallePrestamoQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param   DetallePrestamoQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return DetallePrestamoQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof DetallePrestamoQuery) {
            return $criteria;
        }
        $query = new DetallePrestamoQuery(null, null, $modelAlias);

        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query 
     * @param     PropelPDO $con an optional connection object
     *
     * @return   DetallePrestamo|DetallePrestamo[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = DetallePrestamoPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is already in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(DetallePrestamoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Alias of findPk to use instance pooling
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 DetallePrestamo A model object, or null if the key is not found
     * @throws PropelException
     */
     public function findOneByDetalleprestamoId($key, $con = null)
     {
        return $this->findPk($key, $con);
     }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 DetallePrestamo A model object, or null if the key is not found
     * @throws PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT [DETALLEPRESTAMO_ID], [PRESTAMO_ID], [ESTADOPRESTAMO_ID], [SOLICITUDPRESTAMO_ID] FROM [DETALLE_PRESTAMO] WHERE [DETALLEPRESTAMO_ID] = :p0';
        try {
            $stmt = $con->prepare($sql);			
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new DetallePrestamo();
            $obj->hydrate($row);
            DetallePrestamoPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return DetallePrestamo|DetallePrestamo[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|DetallePrestamo[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return DetallePrestamoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(DetallePrestamoPeer::DETALLEPRESTAMO_ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return DetallePrestamoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(DetallePrestamoPeer::DETALLEPRESTAMO_ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the DETALLEPRESTAMO_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByDetalleprestamoId(1234); // WHERE DETALLEPRESTAMO_ID = 1234
     * $query->filterByDetalleprestamoId(array(12, 34)); // WHERE DETALLEPRESTAMO_ID IN (12, 34)
     * $query->filterByDetalleprestamoId(array('min' => 12)); // WHERE DETALLEPRESTAMO_ID >= 12
     * $query->filterByDetalleprestamoId(array('max' => 12)); // WHERE DETALLEPRESTAMO_ID <= 12
     * </code>
     *
     * @param     mixed $detalleprestamoId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DetallePrestamoQuery The current query, for fluid interface
     */
    public function filterByDetalleprestamoId($detalleprestamoId = null, $comparison = null)
    {
        if (is_array($detalleprestamoId)) {
            $useMinMax = false;
            if (isset($detalleprestamoId['min'])) {
                $this->addUsingAlias(DetallePrestamoPeer::DETALLEPRESTAMO_ID, $detalleprestamoId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($detalleprestamoId['max'])) {
                $this->addUsingAlias(DetallePrestamoPeer::DETALLEPRESTAMO_ID, $detalleprestamoId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(DetallePrestamoPeer::DETALLEPRESTAMO_ID, $detalleprestamoId, $comparison);
    }

    /**
     * Filter the query on the PRESTAMO_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByPrestamoId(1234); // WHERE PRESTAMO_ID = 1234
     * $query->filterByPrestamoId(array(12, 34)); // WHERE PRESTAMO_ID IN (12, 34)
     * $query->filterByPrestamoId(array('min' => 12)); // WHERE PRESTAMO_ID >= 12
     * $query->filterByPrestamoId(array('max' => 12)); // WHERE PRESTAMO_ID <= 12
     * </code>
     *
     * @see       filterByPrestamo()
     *
     * @param     mixed $prestamoId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DetallePrestamoQuery The current query, for fluid interface
     */
    public function filterByPrestamoId($prestamoId = null, $comparison = null)
    {
        if (is_array($prestamoId)) {
            $useMinMax = false;
            if (isset($prestamoId['min'])) {
                $this->addUsingAlias(DetallePrestamoPeer::PRESTAMO_ID, $prestamoId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($prestamoId['max'])) {
                $this->addUsingAlias(DetallePrestamoPeer::PRESTAMO_ID, $prestamoId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(DetallePrestamoPeer::PRESTAMO_ID, $prestamoId, $comparison);
    }

    /**
     * Filter the query on the ESTADOPRESTAMO_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByEstadoprestamoId(1234); // WHERE ESTADOPRESTAMO_ID = 1234
     * $query->filterByEstadoprestamoId(array(12, 34)); // WHERE ESTADOPRESTAMO_ID IN (12, 34)
     * $query->filterByEstadoprestamoId(array('min' => 12)); // WHERE ESTADOPRESTAMO_ID >= 12
     * $query->filterByEstadoprestamoId(array('max' => 12)); // WHERE ESTADOPRESTAMO_ID <= 12
     * </code>
     *
     * @see       filterByEstadoPrestamo()
     *
     * @param     mixed $estadoprestamoId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DetallePrestamoQuery The current query, for fluid interface
     */
    public function filterByEstadoprestamoId($estadoprestamoId = null, $comparison = null)
    {
        if (is_array($estadoprestamoId)) {
            $useMinMax = false;
            if (isset($estadoprestamoId['min'])) {
                $this->addUsingAlias(DetallePrestamoPeer::ESTADOPRESTAMO_ID, $estadoprestamoId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($estadoprestamoId['max'])) {
                $this->addUsingAlias(DetallePrestamoPeer::ESTADOPRESTAMO_ID, $estadoprestamoId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(DetallePrestamoPeer::ESTADOPRESTAMO_ID, $estadoprestamoId, $comparison);
    }

    /**
     * Filter the query on the SOLICITUDPRESTAMO_ID column
     *
     * Example usage:
     * <code>
     * $query->filterBySolicitudprestamoId(1234); // WHERE SOLICITUDPRESTAMO_ID = 1234
     * $query->filterBySolicitudprestamoId(array(12, 34)); // WHERE SOLICITUDPRESTAMO_ID IN (12, 34)
     * $query->filterBySolicitudprestamoId(array('min' => 12)); // WHERE SOLICITUDPRESTAMO_ID >= 12
     * $query->filterBySolicitudprestamoId(array('max' => 12)); // WHERE SOLICITUDPRESTAMO_ID <= 12
     * </code>
     *
     * @see       filterBySolicitudPrestamo()
     *
     * @param     mixed $solicitudprestamoId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DetallePrestamoQuery The current query, for fluid interface
     */
    public function filterBySolicitudprestamoId($solicitudprestamoId = null, $comparison = null)
    {
        if (is_array($solicitudprestamoId)) {
            $useMinMax = false;
            if (isset($solicitudprestamoId['min'])) {
                $this->addUsingAlias(DetallePrestamoPeer::SOLICITUDPRESTAMO_ID, $solicitudprestamoId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($solicitudprestamoId['max'])) {
                $this->addUsingAlias(DetallePrestamoPeer::SOLICITUDPRESTAMO_ID, $solicitudprestamoId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(DetallePrestamoPeer::SOLICITUDPRESTAMO_ID, $solicitudprestamoId, $comparison);
    }

    /**
     * Filter the query by a related Prestamo object
     *
     * @param   Prestamo|PropelObjectCollection $prestamo The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 DetallePrestamoQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByPrestamo($prestamo, $comparison = null)
    {
        if ($prestamo instanceof Prestamo) {
            return $this
                ->addUsingAlias(DetallePrestamoPeer::PRESTAMO_ID, $prestamo->getPrestamoId(), $comparison);
        } elseif ($prestamo instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(DetallePrestamoPeer::PRESTAMO_ID, $prestamo->toKeyValue('PrimaryKey', 'PrestamoId'), $comparison);
        } else {
            throw new PropelException('filterByPrestamo() only accepts arguments of type Prestamo or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Prestamo relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return DetallePrestamoQuery The current query, for fluid interface
     */
    public function joinPrestamo($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Prestamo');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Prestamo');
        }

        return $this;
    }

    /**
     * Use the Prestamo relation Prestamo object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   PrestamoQuery A secondary query class using the current class as primary query
     */
    public function usePrestamoQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinPrestamo($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Prestamo', 'PrestamoQuery');
    }

    /**
     * Filter the query by a related EstadoPrestamo object
     *
     * @param   EstadoPrestamo|PropelObjectCollection $estadoPrestamo The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 DetallePrestamoQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByEstadoPrestamo($estadoPrestamo, $comparison = null)
    {
        if ($estadoPrestamo instanceof EstadoPrestamo) {
            return $this
                ->addUsingAlias(DetallePrestamoPeer::ESTADOPRESTAMO_ID, $estadoPrestamo->getEstadoprestamoId(), $comparison);
        } elseif ($estadoPrestamo instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(DetallePrestamoPeer::ESTADOPRESTAMO_ID, $estadoPrestamo->toKeyValue('PrimaryKey', 'EstadoprestamoId'), $comparison);
        } else {
            throw new PropelException('filterByEstadoPrestamo() only accepts arguments of type EstadoPrestamo or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the EstadoPrestamo relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return DetallePrestamoQuery The current query, for fluid interface
     */
    public function joinEstadoPrestamo($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('EstadoPrestamo');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'EstadoPrestamo');
        }

        return $this;
    }

    /**
     * Use the EstadoPrestamo relation EstadoPrestamo object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   EstadoPrestamoQuery A secondary query class using the current class as primary query
     */
    public function useEstadoPrestamoQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinEstadoPrestamo($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'EstadoPrestamo', 'EstadoPrestamoQuery');
    }

    /**
     * Filter the query by a related SolicitudPrestamo object
     *
     * @param   SolicitudPrestamo|PropelObjectCollection $solicitudPrestamo The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 DetallePrestamoQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterBySolicitudPrestamo($solicitudPrestamo, $comparison = null)
    {
        if ($solicitudPrestamo instanceof SolicitudPrestamo) {
            return $this
                ->addUsingAlias(DetallePrestamoPeer::SOLICITUDPRESTAMO_ID, $solicitudPrestamo->getSolicitudprestamoId(), $comparison);
        } elseif ($solicitudPrestamo instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(DetallePrestamoPeer::SOLICITUDPRESTAMO_ID, $solicitudPrestamo->toKeyValue('PrimaryKey', 'SolicitudprestamoId'), $comparison);
        } else {
            throw new PropelException('filterBySolicitudPrestamo() only accepts arguments of type SolicitudPrestamo or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the SolicitudPrestamo relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return DetallePrestamoQuery The current query, for fluid interface
     */
    public function joinSolicitudPrestamo($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('SolicitudPrestamo');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'SolicitudPrestamo');
        }

        return $this;
    }

    /**
     * Use the SolicitudPrestamo relation SolicitudPrestamo object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   SolicitudPrestamoQuery A secondary query class using the current class as primary query
     */
    public function useSolicitudPrestamoQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinSolicitudPrestamo($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'SolicitudPrestamo', 'SolicitudPrestamoQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   DetallePrestamo $detallePrestamo Object to remove from the list of results
     *
     * @return DetallePrestamoQuery The current query, for fluid interface
     */
    public function prune($detallePrestamo = null)
    {
        if ($detallePrestamo) {
            $this->addUsingAlias(DetallePrestamoPeer::DETALLEPRESTAMO_ID, $detallePrestamo->getDetalleprestamoId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
