<?php


/**
 * Base class that represents a query for the 'METADATOS_SUBSERIE' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * 09/22/23 12:53:58
 *
 * @method MetadatosSubserieQuery orderByMetadatosubserieId($order = Criteria::ASC) Order by the METADATOSUBSERIE_ID column
 * @method MetadatosSubserieQuery orderBySubserieId($order = Criteria::ASC) Order by the SUBSERIE_ID column
 * @method MetadatosSubserieQuery orderByMetadatoId($order = Criteria::ASC) Order by the METADATO_ID column
 *
 * @method MetadatosSubserieQuery groupByMetadatosubserieId() Group by the METADATOSUBSERIE_ID column
 * @method MetadatosSubserieQuery groupBySubserieId() Group by the SUBSERIE_ID column
 * @method MetadatosSubserieQuery groupByMetadatoId() Group by the METADATO_ID column
 *
 * @method MetadatosSubserieQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method MetadatosSubserieQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method MetadatosSubserieQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method MetadatosSubserieQuery leftJoinSubserie($relationAlias = null) Adds a LEFT JOIN clause to the query using the Subserie relation
 * @method MetadatosSubserieQuery rightJoinSubserie($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Subserie relation
 * @method MetadatosSubserieQuery innerJoinSubserie($relationAlias = null) Adds a INNER JOIN clause to the query using the Subserie relation
 *
 * @method MetadatosSubserieQuery leftJoinMetaDatos($relationAlias = null) Adds a LEFT JOIN clause to the query using the MetaDatos relation
 * @method MetadatosSubserieQuery rightJoinMetaDatos($relationAlias = null) Adds a RIGHT JOIN clause to the query using the MetaDatos relation
 * @method MetadatosSubserieQuery innerJoinMetaDatos($relationAlias = null) Adds a INNER JOIN clause to the query using the MetaDatos relation
 *
 * @method MetadatosSubserie findOne(PropelPDO $con = null) Return the first MetadatosSubserie matching the query
 * @method MetadatosSubserie findOneOrCreate(PropelPDO $con = null) Return the first MetadatosSubserie matching the query, or a new MetadatosSubserie object populated from the query conditions when no match is found
 *
 * @method MetadatosSubserie findOneBySubserieId(int $SUBSERIE_ID) Return the first MetadatosSubserie filtered by the SUBSERIE_ID column
 * @method MetadatosSubserie findOneByMetadatoId(int $METADATO_ID) Return the first MetadatosSubserie filtered by the METADATO_ID column
 *
 * @method array findByMetadatosubserieId(int $METADATOSUBSERIE_ID) Return MetadatosSubserie objects filtered by the METADATOSUBSERIE_ID column
 * @method array findBySubserieId(int $SUBSERIE_ID) Return MetadatosSubserie objects filtered by the SUBSERIE_ID column
 * @method array findByMetadatoId(int $METADATO_ID) Return MetadatosSubserie objects filtered by the METADATO_ID column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseMetadatosSubserieQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseMetadatosSubserieQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = null, $modelName = null, $modelAlias = null)
    {
        if (null === $dbName) {
            $dbName = 'propel';
        }
        if (null === $modelName) {
            $modelName = 'MetadatosSubserie';
        }
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new MetadatosSubserieQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param   MetadatosSubserieQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return MetadatosSubserieQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof MetadatosSubserieQuery) {
            return $criteria;
        }
        $query = new MetadatosSubserieQuery(null, null, $modelAlias);

        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query 
     * @param     PropelPDO $con an optional connection object
     *
     * @return   MetadatosSubserie|MetadatosSubserie[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = MetadatosSubseriePeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is already in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(MetadatosSubseriePeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Alias of findPk to use instance pooling
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 MetadatosSubserie A model object, or null if the key is not found
     * @throws PropelException
     */
     public function findOneByMetadatosubserieId($key, $con = null)
     {
        return $this->findPk($key, $con);
     }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 MetadatosSubserie A model object, or null if the key is not found
     * @throws PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT [METADATOSUBSERIE_ID], [SUBSERIE_ID], [METADATO_ID] FROM [METADATOS_SUBSERIE] WHERE [METADATOSUBSERIE_ID] = :p0';
        try {
            $stmt = $con->prepare($sql);			
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new MetadatosSubserie();
            $obj->hydrate($row);
            MetadatosSubseriePeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return MetadatosSubserie|MetadatosSubserie[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|MetadatosSubserie[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return MetadatosSubserieQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(MetadatosSubseriePeer::METADATOSUBSERIE_ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return MetadatosSubserieQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(MetadatosSubseriePeer::METADATOSUBSERIE_ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the METADATOSUBSERIE_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByMetadatosubserieId(1234); // WHERE METADATOSUBSERIE_ID = 1234
     * $query->filterByMetadatosubserieId(array(12, 34)); // WHERE METADATOSUBSERIE_ID IN (12, 34)
     * $query->filterByMetadatosubserieId(array('min' => 12)); // WHERE METADATOSUBSERIE_ID >= 12
     * $query->filterByMetadatosubserieId(array('max' => 12)); // WHERE METADATOSUBSERIE_ID <= 12
     * </code>
     *
     * @param     mixed $metadatosubserieId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return MetadatosSubserieQuery The current query, for fluid interface
     */
    public function filterByMetadatosubserieId($metadatosubserieId = null, $comparison = null)
    {
        if (is_array($metadatosubserieId)) {
            $useMinMax = false;
            if (isset($metadatosubserieId['min'])) {
                $this->addUsingAlias(MetadatosSubseriePeer::METADATOSUBSERIE_ID, $metadatosubserieId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($metadatosubserieId['max'])) {
                $this->addUsingAlias(MetadatosSubseriePeer::METADATOSUBSERIE_ID, $metadatosubserieId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(MetadatosSubseriePeer::METADATOSUBSERIE_ID, $metadatosubserieId, $comparison);
    }

    /**
     * Filter the query on the SUBSERIE_ID column
     *
     * Example usage:
     * <code>
     * $query->filterBySubserieId(1234); // WHERE SUBSERIE_ID = 1234
     * $query->filterBySubserieId(array(12, 34)); // WHERE SUBSERIE_ID IN (12, 34)
     * $query->filterBySubserieId(array('min' => 12)); // WHERE SUBSERIE_ID >= 12
     * $query->filterBySubserieId(array('max' => 12)); // WHERE SUBSERIE_ID <= 12
     * </code>
     *
     * @see       filterBySubserie()
     *
     * @param     mixed $subserieId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return MetadatosSubserieQuery The current query, for fluid interface
     */
    public function filterBySubserieId($subserieId = null, $comparison = null)
    {
        if (is_array($subserieId)) {
            $useMinMax = false;
            if (isset($subserieId['min'])) {
                $this->addUsingAlias(MetadatosSubseriePeer::SUBSERIE_ID, $subserieId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($subserieId['max'])) {
                $this->addUsingAlias(MetadatosSubseriePeer::SUBSERIE_ID, $subserieId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(MetadatosSubseriePeer::SUBSERIE_ID, $subserieId, $comparison);
    }

    /**
     * Filter the query on the METADATO_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByMetadatoId(1234); // WHERE METADATO_ID = 1234
     * $query->filterByMetadatoId(array(12, 34)); // WHERE METADATO_ID IN (12, 34)
     * $query->filterByMetadatoId(array('min' => 12)); // WHERE METADATO_ID >= 12
     * $query->filterByMetadatoId(array('max' => 12)); // WHERE METADATO_ID <= 12
     * </code>
     *
     * @see       filterByMetaDatos()
     *
     * @param     mixed $metadatoId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return MetadatosSubserieQuery The current query, for fluid interface
     */
    public function filterByMetadatoId($metadatoId = null, $comparison = null)
    {
        if (is_array($metadatoId)) {
            $useMinMax = false;
            if (isset($metadatoId['min'])) {
                $this->addUsingAlias(MetadatosSubseriePeer::METADATO_ID, $metadatoId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($metadatoId['max'])) {
                $this->addUsingAlias(MetadatosSubseriePeer::METADATO_ID, $metadatoId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(MetadatosSubseriePeer::METADATO_ID, $metadatoId, $comparison);
    }

    /**
     * Filter the query by a related Subserie object
     *
     * @param   Subserie|PropelObjectCollection $subserie The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 MetadatosSubserieQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterBySubserie($subserie, $comparison = null)
    {
        if ($subserie instanceof Subserie) {
            return $this
                ->addUsingAlias(MetadatosSubseriePeer::SUBSERIE_ID, $subserie->getSubserieId(), $comparison);
        } elseif ($subserie instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(MetadatosSubseriePeer::SUBSERIE_ID, $subserie->toKeyValue('PrimaryKey', 'SubserieId'), $comparison);
        } else {
            throw new PropelException('filterBySubserie() only accepts arguments of type Subserie or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Subserie relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return MetadatosSubserieQuery The current query, for fluid interface
     */
    public function joinSubserie($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Subserie');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Subserie');
        }

        return $this;
    }

    /**
     * Use the Subserie relation Subserie object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   SubserieQuery A secondary query class using the current class as primary query
     */
    public function useSubserieQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinSubserie($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Subserie', 'SubserieQuery');
    }

    /**
     * Filter the query by a related MetaDatos object
     *
     * @param   MetaDatos|PropelObjectCollection $metaDatos The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 MetadatosSubserieQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByMetaDatos($metaDatos, $comparison = null)
    {
        if ($metaDatos instanceof MetaDatos) {
            return $this
                ->addUsingAlias(MetadatosSubseriePeer::METADATO_ID, $metaDatos->getMetadatoId(), $comparison);
        } elseif ($metaDatos instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(MetadatosSubseriePeer::METADATO_ID, $metaDatos->toKeyValue('PrimaryKey', 'MetadatoId'), $comparison);
        } else {
            throw new PropelException('filterByMetaDatos() only accepts arguments of type MetaDatos or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the MetaDatos relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return MetadatosSubserieQuery The current query, for fluid interface
     */
    public function joinMetaDatos($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('MetaDatos');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'MetaDatos');
        }

        return $this;
    }

    /**
     * Use the MetaDatos relation MetaDatos object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   MetaDatosQuery A secondary query class using the current class as primary query
     */
    public function useMetaDatosQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinMetaDatos($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'MetaDatos', 'MetaDatosQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   MetadatosSubserie $metadatosSubserie Object to remove from the list of results
     *
     * @return MetadatosSubserieQuery The current query, for fluid interface
     */
    public function prune($metadatosSubserie = null)
    {
        if ($metadatosSubserie) {
            $this->addUsingAlias(MetadatosSubseriePeer::METADATOSUBSERIE_ID, $metadatosSubserie->getMetadatosubserieId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
