<?php


/**
 * Base class that represents a query for the 'PROV_ITEM_FLUJO' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * 09/22/23 12:54:06
 *
 * @method ProvItemFlujoQuery orderByProvItemFlujoId($order = Criteria::ASC) Order by the PROV_ITEM_FLUJO_ID column
 * @method ProvItemFlujoQuery orderByDescripcion($order = Criteria::ASC) Order by the DESCRIPCION column
 *
 * @method ProvItemFlujoQuery groupByProvItemFlujoId() Group by the PROV_ITEM_FLUJO_ID column
 * @method ProvItemFlujoQuery groupByDescripcion() Group by the DESCRIPCION column
 *
 * @method ProvItemFlujoQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method ProvItemFlujoQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method ProvItemFlujoQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method ProvItemFlujoQuery leftJoinProvEstadoFlujoPeriodo($relationAlias = null) Adds a LEFT JOIN clause to the query using the ProvEstadoFlujoPeriodo relation
 * @method ProvItemFlujoQuery rightJoinProvEstadoFlujoPeriodo($relationAlias = null) Adds a RIGHT JOIN clause to the query using the ProvEstadoFlujoPeriodo relation
 * @method ProvItemFlujoQuery innerJoinProvEstadoFlujoPeriodo($relationAlias = null) Adds a INNER JOIN clause to the query using the ProvEstadoFlujoPeriodo relation
 *
 * @method ProvItemFlujo findOne(PropelPDO $con = null) Return the first ProvItemFlujo matching the query
 * @method ProvItemFlujo findOneOrCreate(PropelPDO $con = null) Return the first ProvItemFlujo matching the query, or a new ProvItemFlujo object populated from the query conditions when no match is found
 *
 * @method ProvItemFlujo findOneByDescripcion(string $DESCRIPCION) Return the first ProvItemFlujo filtered by the DESCRIPCION column
 *
 * @method array findByProvItemFlujoId(int $PROV_ITEM_FLUJO_ID) Return ProvItemFlujo objects filtered by the PROV_ITEM_FLUJO_ID column
 * @method array findByDescripcion(string $DESCRIPCION) Return ProvItemFlujo objects filtered by the DESCRIPCION column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseProvItemFlujoQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseProvItemFlujoQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = null, $modelName = null, $modelAlias = null)
    {
        if (null === $dbName) {
            $dbName = 'propel';
        }
        if (null === $modelName) {
            $modelName = 'ProvItemFlujo';
        }
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new ProvItemFlujoQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param   ProvItemFlujoQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return ProvItemFlujoQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof ProvItemFlujoQuery) {
            return $criteria;
        }
        $query = new ProvItemFlujoQuery(null, null, $modelAlias);

        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query 
     * @param     PropelPDO $con an optional connection object
     *
     * @return   ProvItemFlujo|ProvItemFlujo[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = ProvItemFlujoPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is already in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(ProvItemFlujoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Alias of findPk to use instance pooling
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 ProvItemFlujo A model object, or null if the key is not found
     * @throws PropelException
     */
     public function findOneByProvItemFlujoId($key, $con = null)
     {
        return $this->findPk($key, $con);
     }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 ProvItemFlujo A model object, or null if the key is not found
     * @throws PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT [PROV_ITEM_FLUJO_ID], [DESCRIPCION] FROM [PROV_ITEM_FLUJO] WHERE [PROV_ITEM_FLUJO_ID] = :p0';
        try {
            $stmt = $con->prepare($sql);			
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new ProvItemFlujo();
            $obj->hydrate($row);
            ProvItemFlujoPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return ProvItemFlujo|ProvItemFlujo[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|ProvItemFlujo[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return ProvItemFlujoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(ProvItemFlujoPeer::PROV_ITEM_FLUJO_ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return ProvItemFlujoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(ProvItemFlujoPeer::PROV_ITEM_FLUJO_ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the PROV_ITEM_FLUJO_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByProvItemFlujoId(1234); // WHERE PROV_ITEM_FLUJO_ID = 1234
     * $query->filterByProvItemFlujoId(array(12, 34)); // WHERE PROV_ITEM_FLUJO_ID IN (12, 34)
     * $query->filterByProvItemFlujoId(array('min' => 12)); // WHERE PROV_ITEM_FLUJO_ID >= 12
     * $query->filterByProvItemFlujoId(array('max' => 12)); // WHERE PROV_ITEM_FLUJO_ID <= 12
     * </code>
     *
     * @param     mixed $provItemFlujoId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ProvItemFlujoQuery The current query, for fluid interface
     */
    public function filterByProvItemFlujoId($provItemFlujoId = null, $comparison = null)
    {
        if (is_array($provItemFlujoId)) {
            $useMinMax = false;
            if (isset($provItemFlujoId['min'])) {
                $this->addUsingAlias(ProvItemFlujoPeer::PROV_ITEM_FLUJO_ID, $provItemFlujoId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($provItemFlujoId['max'])) {
                $this->addUsingAlias(ProvItemFlujoPeer::PROV_ITEM_FLUJO_ID, $provItemFlujoId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ProvItemFlujoPeer::PROV_ITEM_FLUJO_ID, $provItemFlujoId, $comparison);
    }

    /**
     * Filter the query on the DESCRIPCION column
     *
     * Example usage:
     * <code>
     * $query->filterByDescripcion('fooValue');   // WHERE DESCRIPCION = 'fooValue'
     * $query->filterByDescripcion('%fooValue%'); // WHERE DESCRIPCION LIKE '%fooValue%'
     * </code>
     *
     * @param     string $descripcion The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ProvItemFlujoQuery The current query, for fluid interface
     */
    public function filterByDescripcion($descripcion = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($descripcion)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $descripcion)) {
                $descripcion = str_replace('*', '%', $descripcion);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(ProvItemFlujoPeer::DESCRIPCION, $descripcion, $comparison);
    }

    /**
     * Filter the query by a related ProvEstadoFlujoPeriodo object
     *
     * @param   ProvEstadoFlujoPeriodo|PropelObjectCollection $provEstadoFlujoPeriodo  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 ProvItemFlujoQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByProvEstadoFlujoPeriodo($provEstadoFlujoPeriodo, $comparison = null)
    {
        if ($provEstadoFlujoPeriodo instanceof ProvEstadoFlujoPeriodo) {
            return $this
                ->addUsingAlias(ProvItemFlujoPeer::PROV_ITEM_FLUJO_ID, $provEstadoFlujoPeriodo->getProvItemFlujoId(), $comparison);
        } elseif ($provEstadoFlujoPeriodo instanceof PropelObjectCollection) {
            return $this
                ->useProvEstadoFlujoPeriodoQuery()
                ->filterByPrimaryKeys($provEstadoFlujoPeriodo->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterByProvEstadoFlujoPeriodo() only accepts arguments of type ProvEstadoFlujoPeriodo or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the ProvEstadoFlujoPeriodo relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return ProvItemFlujoQuery The current query, for fluid interface
     */
    public function joinProvEstadoFlujoPeriodo($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('ProvEstadoFlujoPeriodo');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'ProvEstadoFlujoPeriodo');
        }

        return $this;
    }

    /**
     * Use the ProvEstadoFlujoPeriodo relation ProvEstadoFlujoPeriodo object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   ProvEstadoFlujoPeriodoQuery A secondary query class using the current class as primary query
     */
    public function useProvEstadoFlujoPeriodoQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinProvEstadoFlujoPeriodo($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'ProvEstadoFlujoPeriodo', 'ProvEstadoFlujoPeriodoQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   ProvItemFlujo $provItemFlujo Object to remove from the list of results
     *
     * @return ProvItemFlujoQuery The current query, for fluid interface
     */
    public function prune($provItemFlujo = null)
    {
        if ($provItemFlujo) {
            $this->addUsingAlias(ProvItemFlujoPeer::PROV_ITEM_FLUJO_ID, $provItemFlujo->getProvItemFlujoId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
