<?php


/**
 * Base class that represents a query for the 'COMRECIBIDA_RESPUESTA' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * mar 07 ene 2025 08:43:31
 *
 * @method ComrecibidaRespuestaQuery orderByComrecibidarespuestaId($order = Criteria::ASC) Order by the COMRECIBIDARESPUESTA_ID column
 * @method ComrecibidaRespuestaQuery orderByComrecibidaId($order = Criteria::ASC) Order by the COMRECIBIDA_ID column
 * @method ComrecibidaRespuestaQuery orderByComenviadaId($order = Criteria::ASC) Order by the COMENVIADA_ID column
 * @method ComrecibidaRespuestaQuery orderByUsuarioId($order = Criteria::ASC) Order by the USUARIO_ID column
 * @method ComrecibidaRespuestaQuery orderByFechaCreacion($order = Criteria::ASC) Order by the FECHA_CREACION column
 *
 * @method ComrecibidaRespuestaQuery groupByComrecibidarespuestaId() Group by the COMRECIBIDARESPUESTA_ID column
 * @method ComrecibidaRespuestaQuery groupByComrecibidaId() Group by the COMRECIBIDA_ID column
 * @method ComrecibidaRespuestaQuery groupByComenviadaId() Group by the COMENVIADA_ID column
 * @method ComrecibidaRespuestaQuery groupByUsuarioId() Group by the USUARIO_ID column
 * @method ComrecibidaRespuestaQuery groupByFechaCreacion() Group by the FECHA_CREACION column
 *
 * @method ComrecibidaRespuestaQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method ComrecibidaRespuestaQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method ComrecibidaRespuestaQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method ComrecibidaRespuestaQuery leftJoinComRecibida($relationAlias = null) Adds a LEFT JOIN clause to the query using the ComRecibida relation
 * @method ComrecibidaRespuestaQuery rightJoinComRecibida($relationAlias = null) Adds a RIGHT JOIN clause to the query using the ComRecibida relation
 * @method ComrecibidaRespuestaQuery innerJoinComRecibida($relationAlias = null) Adds a INNER JOIN clause to the query using the ComRecibida relation
 *
 * @method ComrecibidaRespuestaQuery leftJoinComEnviada($relationAlias = null) Adds a LEFT JOIN clause to the query using the ComEnviada relation
 * @method ComrecibidaRespuestaQuery rightJoinComEnviada($relationAlias = null) Adds a RIGHT JOIN clause to the query using the ComEnviada relation
 * @method ComrecibidaRespuestaQuery innerJoinComEnviada($relationAlias = null) Adds a INNER JOIN clause to the query using the ComEnviada relation
 *
 * @method ComrecibidaRespuestaQuery leftJoinUsuario($relationAlias = null) Adds a LEFT JOIN clause to the query using the Usuario relation
 * @method ComrecibidaRespuestaQuery rightJoinUsuario($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Usuario relation
 * @method ComrecibidaRespuestaQuery innerJoinUsuario($relationAlias = null) Adds a INNER JOIN clause to the query using the Usuario relation
 *
 * @method ComrecibidaRespuesta findOne(PropelPDO $con = null) Return the first ComrecibidaRespuesta matching the query
 * @method ComrecibidaRespuesta findOneOrCreate(PropelPDO $con = null) Return the first ComrecibidaRespuesta matching the query, or a new ComrecibidaRespuesta object populated from the query conditions when no match is found
 *
 * @method ComrecibidaRespuesta findOneByComrecibidaId(int $COMRECIBIDA_ID) Return the first ComrecibidaRespuesta filtered by the COMRECIBIDA_ID column
 * @method ComrecibidaRespuesta findOneByComenviadaId(int $COMENVIADA_ID) Return the first ComrecibidaRespuesta filtered by the COMENVIADA_ID column
 * @method ComrecibidaRespuesta findOneByUsuarioId(int $USUARIO_ID) Return the first ComrecibidaRespuesta filtered by the USUARIO_ID column
 * @method ComrecibidaRespuesta findOneByFechaCreacion(string $FECHA_CREACION) Return the first ComrecibidaRespuesta filtered by the FECHA_CREACION column
 *
 * @method array findByComrecibidarespuestaId(int $COMRECIBIDARESPUESTA_ID) Return ComrecibidaRespuesta objects filtered by the COMRECIBIDARESPUESTA_ID column
 * @method array findByComrecibidaId(int $COMRECIBIDA_ID) Return ComrecibidaRespuesta objects filtered by the COMRECIBIDA_ID column
 * @method array findByComenviadaId(int $COMENVIADA_ID) Return ComrecibidaRespuesta objects filtered by the COMENVIADA_ID column
 * @method array findByUsuarioId(int $USUARIO_ID) Return ComrecibidaRespuesta objects filtered by the USUARIO_ID column
 * @method array findByFechaCreacion(string $FECHA_CREACION) Return ComrecibidaRespuesta objects filtered by the FECHA_CREACION column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseComrecibidaRespuestaQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseComrecibidaRespuestaQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = null, $modelName = null, $modelAlias = null)
    {
        if (null === $dbName) {
            $dbName = 'propel';
        }
        if (null === $modelName) {
            $modelName = 'ComrecibidaRespuesta';
        }
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new ComrecibidaRespuestaQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param   ComrecibidaRespuestaQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return ComrecibidaRespuestaQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof ComrecibidaRespuestaQuery) {
            return $criteria;
        }
        $query = new ComrecibidaRespuestaQuery(null, null, $modelAlias);

        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query 
     * @param     PropelPDO $con an optional connection object
     *
     * @return   ComrecibidaRespuesta|ComrecibidaRespuesta[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = ComrecibidaRespuestaPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is already in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(ComrecibidaRespuestaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Alias of findPk to use instance pooling
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 ComrecibidaRespuesta A model object, or null if the key is not found
     * @throws PropelException
     */
     public function findOneByComrecibidarespuestaId($key, $con = null)
     {
        return $this->findPk($key, $con);
     }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 ComrecibidaRespuesta A model object, or null if the key is not found
     * @throws PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT [COMRECIBIDARESPUESTA_ID], [COMRECIBIDA_ID], [COMENVIADA_ID], [USUARIO_ID], [FECHA_CREACION] FROM [COMRECIBIDA_RESPUESTA] WHERE [COMRECIBIDARESPUESTA_ID] = :p0';
        try {
            $stmt = $con->prepare($sql);			
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new ComrecibidaRespuesta();
            $obj->hydrate($row);
            ComrecibidaRespuestaPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return ComrecibidaRespuesta|ComrecibidaRespuesta[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|ComrecibidaRespuesta[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return ComrecibidaRespuestaQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(ComrecibidaRespuestaPeer::COMRECIBIDARESPUESTA_ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return ComrecibidaRespuestaQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(ComrecibidaRespuestaPeer::COMRECIBIDARESPUESTA_ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the COMRECIBIDARESPUESTA_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByComrecibidarespuestaId(1234); // WHERE COMRECIBIDARESPUESTA_ID = 1234
     * $query->filterByComrecibidarespuestaId(array(12, 34)); // WHERE COMRECIBIDARESPUESTA_ID IN (12, 34)
     * $query->filterByComrecibidarespuestaId(array('min' => 12)); // WHERE COMRECIBIDARESPUESTA_ID >= 12
     * $query->filterByComrecibidarespuestaId(array('max' => 12)); // WHERE COMRECIBIDARESPUESTA_ID <= 12
     * </code>
     *
     * @param     mixed $comrecibidarespuestaId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ComrecibidaRespuestaQuery The current query, for fluid interface
     */
    public function filterByComrecibidarespuestaId($comrecibidarespuestaId = null, $comparison = null)
    {
        if (is_array($comrecibidarespuestaId)) {
            $useMinMax = false;
            if (isset($comrecibidarespuestaId['min'])) {
                $this->addUsingAlias(ComrecibidaRespuestaPeer::COMRECIBIDARESPUESTA_ID, $comrecibidarespuestaId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($comrecibidarespuestaId['max'])) {
                $this->addUsingAlias(ComrecibidaRespuestaPeer::COMRECIBIDARESPUESTA_ID, $comrecibidarespuestaId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ComrecibidaRespuestaPeer::COMRECIBIDARESPUESTA_ID, $comrecibidarespuestaId, $comparison);
    }

    /**
     * Filter the query on the COMRECIBIDA_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByComrecibidaId(1234); // WHERE COMRECIBIDA_ID = 1234
     * $query->filterByComrecibidaId(array(12, 34)); // WHERE COMRECIBIDA_ID IN (12, 34)
     * $query->filterByComrecibidaId(array('min' => 12)); // WHERE COMRECIBIDA_ID >= 12
     * $query->filterByComrecibidaId(array('max' => 12)); // WHERE COMRECIBIDA_ID <= 12
     * </code>
     *
     * @see       filterByComRecibida()
     *
     * @param     mixed $comrecibidaId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ComrecibidaRespuestaQuery The current query, for fluid interface
     */
    public function filterByComrecibidaId($comrecibidaId = null, $comparison = null)
    {
        if (is_array($comrecibidaId)) {
            $useMinMax = false;
            if (isset($comrecibidaId['min'])) {
                $this->addUsingAlias(ComrecibidaRespuestaPeer::COMRECIBIDA_ID, $comrecibidaId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($comrecibidaId['max'])) {
                $this->addUsingAlias(ComrecibidaRespuestaPeer::COMRECIBIDA_ID, $comrecibidaId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ComrecibidaRespuestaPeer::COMRECIBIDA_ID, $comrecibidaId, $comparison);
    }

    /**
     * Filter the query on the COMENVIADA_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByComenviadaId(1234); // WHERE COMENVIADA_ID = 1234
     * $query->filterByComenviadaId(array(12, 34)); // WHERE COMENVIADA_ID IN (12, 34)
     * $query->filterByComenviadaId(array('min' => 12)); // WHERE COMENVIADA_ID >= 12
     * $query->filterByComenviadaId(array('max' => 12)); // WHERE COMENVIADA_ID <= 12
     * </code>
     *
     * @see       filterByComEnviada()
     *
     * @param     mixed $comenviadaId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ComrecibidaRespuestaQuery The current query, for fluid interface
     */
    public function filterByComenviadaId($comenviadaId = null, $comparison = null)
    {
        if (is_array($comenviadaId)) {
            $useMinMax = false;
            if (isset($comenviadaId['min'])) {
                $this->addUsingAlias(ComrecibidaRespuestaPeer::COMENVIADA_ID, $comenviadaId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($comenviadaId['max'])) {
                $this->addUsingAlias(ComrecibidaRespuestaPeer::COMENVIADA_ID, $comenviadaId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ComrecibidaRespuestaPeer::COMENVIADA_ID, $comenviadaId, $comparison);
    }

    /**
     * Filter the query on the USUARIO_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByUsuarioId(1234); // WHERE USUARIO_ID = 1234
     * $query->filterByUsuarioId(array(12, 34)); // WHERE USUARIO_ID IN (12, 34)
     * $query->filterByUsuarioId(array('min' => 12)); // WHERE USUARIO_ID >= 12
     * $query->filterByUsuarioId(array('max' => 12)); // WHERE USUARIO_ID <= 12
     * </code>
     *
     * @see       filterByUsuario()
     *
     * @param     mixed $usuarioId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ComrecibidaRespuestaQuery The current query, for fluid interface
     */
    public function filterByUsuarioId($usuarioId = null, $comparison = null)
    {
        if (is_array($usuarioId)) {
            $useMinMax = false;
            if (isset($usuarioId['min'])) {
                $this->addUsingAlias(ComrecibidaRespuestaPeer::USUARIO_ID, $usuarioId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($usuarioId['max'])) {
                $this->addUsingAlias(ComrecibidaRespuestaPeer::USUARIO_ID, $usuarioId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ComrecibidaRespuestaPeer::USUARIO_ID, $usuarioId, $comparison);
    }

    /**
     * Filter the query on the FECHA_CREACION column
     *
     * Example usage:
     * <code>
     * $query->filterByFechaCreacion('2011-03-14'); // WHERE FECHA_CREACION = '2011-03-14'
     * $query->filterByFechaCreacion('now'); // WHERE FECHA_CREACION = '2011-03-14'
     * $query->filterByFechaCreacion(array('max' => 'yesterday')); // WHERE FECHA_CREACION < '2011-03-13'
     * </code>
     *
     * @param     mixed $fechaCreacion The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ComrecibidaRespuestaQuery The current query, for fluid interface
     */
    public function filterByFechaCreacion($fechaCreacion = null, $comparison = null)
    {
        if (is_array($fechaCreacion)) {
            $useMinMax = false;
            if (isset($fechaCreacion['min'])) {
                $this->addUsingAlias(ComrecibidaRespuestaPeer::FECHA_CREACION, $fechaCreacion['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($fechaCreacion['max'])) {
                $this->addUsingAlias(ComrecibidaRespuestaPeer::FECHA_CREACION, $fechaCreacion['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ComrecibidaRespuestaPeer::FECHA_CREACION, $fechaCreacion, $comparison);
    }

    /**
     * Filter the query by a related ComRecibida object
     *
     * @param   ComRecibida|PropelObjectCollection $comRecibida The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 ComrecibidaRespuestaQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByComRecibida($comRecibida, $comparison = null)
    {
        if ($comRecibida instanceof ComRecibida) {
            return $this
                ->addUsingAlias(ComrecibidaRespuestaPeer::COMRECIBIDA_ID, $comRecibida->getComrecibidaId(), $comparison);
        } elseif ($comRecibida instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(ComrecibidaRespuestaPeer::COMRECIBIDA_ID, $comRecibida->toKeyValue('PrimaryKey', 'ComrecibidaId'), $comparison);
        } else {
            throw new PropelException('filterByComRecibida() only accepts arguments of type ComRecibida or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the ComRecibida relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return ComrecibidaRespuestaQuery The current query, for fluid interface
     */
    public function joinComRecibida($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('ComRecibida');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'ComRecibida');
        }

        return $this;
    }

    /**
     * Use the ComRecibida relation ComRecibida object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   ComRecibidaQuery A secondary query class using the current class as primary query
     */
    public function useComRecibidaQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinComRecibida($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'ComRecibida', 'ComRecibidaQuery');
    }

    /**
     * Filter the query by a related ComEnviada object
     *
     * @param   ComEnviada|PropelObjectCollection $comEnviada The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 ComrecibidaRespuestaQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByComEnviada($comEnviada, $comparison = null)
    {
        if ($comEnviada instanceof ComEnviada) {
            return $this
                ->addUsingAlias(ComrecibidaRespuestaPeer::COMENVIADA_ID, $comEnviada->getComenviadaId(), $comparison);
        } elseif ($comEnviada instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(ComrecibidaRespuestaPeer::COMENVIADA_ID, $comEnviada->toKeyValue('PrimaryKey', 'ComenviadaId'), $comparison);
        } else {
            throw new PropelException('filterByComEnviada() only accepts arguments of type ComEnviada or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the ComEnviada relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return ComrecibidaRespuestaQuery The current query, for fluid interface
     */
    public function joinComEnviada($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('ComEnviada');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'ComEnviada');
        }

        return $this;
    }

    /**
     * Use the ComEnviada relation ComEnviada object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   ComEnviadaQuery A secondary query class using the current class as primary query
     */
    public function useComEnviadaQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinComEnviada($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'ComEnviada', 'ComEnviadaQuery');
    }

    /**
     * Filter the query by a related Usuario object
     *
     * @param   Usuario|PropelObjectCollection $usuario The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 ComrecibidaRespuestaQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByUsuario($usuario, $comparison = null)
    {
        if ($usuario instanceof Usuario) {
            return $this
                ->addUsingAlias(ComrecibidaRespuestaPeer::USUARIO_ID, $usuario->getUsuarioId(), $comparison);
        } elseif ($usuario instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(ComrecibidaRespuestaPeer::USUARIO_ID, $usuario->toKeyValue('PrimaryKey', 'UsuarioId'), $comparison);
        } else {
            throw new PropelException('filterByUsuario() only accepts arguments of type Usuario or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Usuario relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return ComrecibidaRespuestaQuery The current query, for fluid interface
     */
    public function joinUsuario($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Usuario');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Usuario');
        }

        return $this;
    }

    /**
     * Use the Usuario relation Usuario object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   UsuarioQuery A secondary query class using the current class as primary query
     */
    public function useUsuarioQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinUsuario($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Usuario', 'UsuarioQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   ComrecibidaRespuesta $comrecibidaRespuesta Object to remove from the list of results
     *
     * @return ComrecibidaRespuestaQuery The current query, for fluid interface
     */
    public function prune($comrecibidaRespuesta = null)
    {
        if ($comrecibidaRespuesta) {
            $this->addUsingAlias(ComrecibidaRespuestaPeer::COMRECIBIDARESPUESTA_ID, $comrecibidaRespuesta->getComrecibidarespuestaId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
