<?php


/**
 * Base class that represents a query for the 'ESTADO_PQR' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * 09/22/23 12:53:50
 *
 * @method EstadoPqrQuery orderByEstadopqrId($order = Criteria::ASC) Order by the ESTADOPQR_ID column
 * @method EstadoPqrQuery orderByDescripcion($order = Criteria::ASC) Order by the DESCRIPCION column
 *
 * @method EstadoPqrQuery groupByEstadopqrId() Group by the ESTADOPQR_ID column
 * @method EstadoPqrQuery groupByDescripcion() Group by the DESCRIPCION column
 *
 * @method EstadoPqrQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method EstadoPqrQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method EstadoPqrQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method EstadoPqrQuery leftJoinPqr($relationAlias = null) Adds a LEFT JOIN clause to the query using the Pqr relation
 * @method EstadoPqrQuery rightJoinPqr($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Pqr relation
 * @method EstadoPqrQuery innerJoinPqr($relationAlias = null) Adds a INNER JOIN clause to the query using the Pqr relation
 *
 * @method EstadoPqr findOne(PropelPDO $con = null) Return the first EstadoPqr matching the query
 * @method EstadoPqr findOneOrCreate(PropelPDO $con = null) Return the first EstadoPqr matching the query, or a new EstadoPqr object populated from the query conditions when no match is found
 *
 * @method EstadoPqr findOneByDescripcion(string $DESCRIPCION) Return the first EstadoPqr filtered by the DESCRIPCION column
 *
 * @method array findByEstadopqrId(int $ESTADOPQR_ID) Return EstadoPqr objects filtered by the ESTADOPQR_ID column
 * @method array findByDescripcion(string $DESCRIPCION) Return EstadoPqr objects filtered by the DESCRIPCION column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseEstadoPqrQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseEstadoPqrQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = null, $modelName = null, $modelAlias = null)
    {
        if (null === $dbName) {
            $dbName = 'propel';
        }
        if (null === $modelName) {
            $modelName = 'EstadoPqr';
        }
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new EstadoPqrQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param   EstadoPqrQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return EstadoPqrQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof EstadoPqrQuery) {
            return $criteria;
        }
        $query = new EstadoPqrQuery(null, null, $modelAlias);

        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query 
     * @param     PropelPDO $con an optional connection object
     *
     * @return   EstadoPqr|EstadoPqr[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = EstadoPqrPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is already in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(EstadoPqrPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Alias of findPk to use instance pooling
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 EstadoPqr A model object, or null if the key is not found
     * @throws PropelException
     */
     public function findOneByEstadopqrId($key, $con = null)
     {
        return $this->findPk($key, $con);
     }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 EstadoPqr A model object, or null if the key is not found
     * @throws PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT [ESTADOPQR_ID], [DESCRIPCION] FROM [ESTADO_PQR] WHERE [ESTADOPQR_ID] = :p0';
        try {
            $stmt = $con->prepare($sql);			
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new EstadoPqr();
            $obj->hydrate($row);
            EstadoPqrPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return EstadoPqr|EstadoPqr[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|EstadoPqr[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return EstadoPqrQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(EstadoPqrPeer::ESTADOPQR_ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return EstadoPqrQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(EstadoPqrPeer::ESTADOPQR_ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the ESTADOPQR_ID column
     *
     * Example usage:
     * <code>
     * $query->filterByEstadopqrId(1234); // WHERE ESTADOPQR_ID = 1234
     * $query->filterByEstadopqrId(array(12, 34)); // WHERE ESTADOPQR_ID IN (12, 34)
     * $query->filterByEstadopqrId(array('min' => 12)); // WHERE ESTADOPQR_ID >= 12
     * $query->filterByEstadopqrId(array('max' => 12)); // WHERE ESTADOPQR_ID <= 12
     * </code>
     *
     * @param     mixed $estadopqrId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return EstadoPqrQuery The current query, for fluid interface
     */
    public function filterByEstadopqrId($estadopqrId = null, $comparison = null)
    {
        if (is_array($estadopqrId)) {
            $useMinMax = false;
            if (isset($estadopqrId['min'])) {
                $this->addUsingAlias(EstadoPqrPeer::ESTADOPQR_ID, $estadopqrId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($estadopqrId['max'])) {
                $this->addUsingAlias(EstadoPqrPeer::ESTADOPQR_ID, $estadopqrId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(EstadoPqrPeer::ESTADOPQR_ID, $estadopqrId, $comparison);
    }

    /**
     * Filter the query on the DESCRIPCION column
     *
     * Example usage:
     * <code>
     * $query->filterByDescripcion('fooValue');   // WHERE DESCRIPCION = 'fooValue'
     * $query->filterByDescripcion('%fooValue%'); // WHERE DESCRIPCION LIKE '%fooValue%'
     * </code>
     *
     * @param     string $descripcion The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return EstadoPqrQuery The current query, for fluid interface
     */
    public function filterByDescripcion($descripcion = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($descripcion)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $descripcion)) {
                $descripcion = str_replace('*', '%', $descripcion);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(EstadoPqrPeer::DESCRIPCION, $descripcion, $comparison);
    }

    /**
     * Filter the query by a related Pqr object
     *
     * @param   Pqr|PropelObjectCollection $pqr  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 EstadoPqrQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByPqr($pqr, $comparison = null)
    {
        if ($pqr instanceof Pqr) {
            return $this
                ->addUsingAlias(EstadoPqrPeer::ESTADOPQR_ID, $pqr->getEstadopqrId(), $comparison);
        } elseif ($pqr instanceof PropelObjectCollection) {
            return $this
                ->usePqrQuery()
                ->filterByPrimaryKeys($pqr->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterByPqr() only accepts arguments of type Pqr or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Pqr relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return EstadoPqrQuery The current query, for fluid interface
     */
    public function joinPqr($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Pqr');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Pqr');
        }

        return $this;
    }

    /**
     * Use the Pqr relation Pqr object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   PqrQuery A secondary query class using the current class as primary query
     */
    public function usePqrQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinPqr($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Pqr', 'PqrQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   EstadoPqr $estadoPqr Object to remove from the list of results
     *
     * @return EstadoPqrQuery The current query, for fluid interface
     */
    public function prune($estadoPqr = null)
    {
        if ($estadoPqr) {
            $this->addUsingAlias(EstadoPqrPeer::ESTADOPQR_ID, $estadoPqr->getEstadopqrId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
