<?php


/**
 * Base class that represents a row from the 'NOTIFICACION_EMAIL' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * 09/22/23 12:53:54
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseNotificacionEmail extends BaseObject implements Persistent
{
    /**
     * Peer class name
     */
    const PEER = 'NotificacionEmailPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        NotificacionEmailPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinite loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the notificacionemail_id field.
     * @var        int
     */
    protected $notificacionemail_id;

    /**
     * The value for the dependencia_id field.
     * @var        int
     */
    protected $dependencia_id;

    /**
     * The value for the host_smtp field.
     * @var        string
     */
    protected $host_smtp;

    /**
     * The value for the email_login field.
     * @var        string
     */
    protected $email_login;

    /**
     * The value for the email_pass field.
     * @var        string
     */
    protected $email_pass;

    /**
     * The value for the puerto field.
     * @var        int
     */
    protected $puerto;

    /**
     * The value for the secure_smtp field.
     * @var        string
     */
    protected $secure_smtp;

    /**
     * The value for the auth_smtp field.
     * @var        int
     */
    protected $auth_smtp;

    /**
     * The value for the certimail field.
     * @var        string
     */
    protected $certimail;

    /**
     * The value for the email_body field.
     * @var        string
     */
    protected $email_body;

    /**
     * @var        Dependencia
     */
    protected $aDependencia;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

    /**
     * Flag to prevent endless clearAllReferences($deep=true) loop, if this object is referenced
     * @var        boolean
     */
    protected $alreadyInClearAllReferencesDeep = false;

    /**
     * Get the [notificacionemail_id] column value.
     * 
     * @return int
     */
    public function getNotificacionemailId()
    {

        return $this->notificacionemail_id;
    }

    /**
     * Get the [dependencia_id] column value.
     * 
     * @return int
     */
    public function getDependenciaId()
    {

        return $this->dependencia_id;
    }

    /**
     * Get the [host_smtp] column value.
     * 
     * @return string
     */
    public function getHostSmtp()
    {

        return $this->host_smtp;
    }

    /**
     * Get the [email_login] column value.
     * 
     * @return string
     */
    public function getEmailLogin()
    {

        return $this->email_login;
    }

    /**
     * Get the [email_pass] column value.
     * 
     * @return string
     */
    public function getEmailPass()
    {

        return $this->email_pass;
    }

    /**
     * Get the [puerto] column value.
     * 
     * @return int
     */
    public function getPuerto()
    {

        return $this->puerto;
    }

    /**
     * Get the [secure_smtp] column value.
     * 
     * @return string
     */
    public function getSecureSmtp()
    {

        return $this->secure_smtp;
    }

    /**
     * Get the [auth_smtp] column value.
     * 
     * @return int
     */
    public function getAuthSmtp()
    {

        return $this->auth_smtp;
    }

    /**
     * Get the [certimail] column value.
     * 
     * @return string
     */
    public function getCertimail()
    {

        return $this->certimail;
    }

    /**
     * Get the [email_body] column value.
     * 
     * @return string
     */
    public function getEmailBody()
    {

        return $this->email_body;
    }

    /**
     * Set the value of [notificacionemail_id] column.
     * 
     * @param  int $v new value
     * @return NotificacionEmail The current object (for fluent API support)
     */
    public function setNotificacionemailId($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->notificacionemail_id !== $v) {
            $this->notificacionemail_id = $v;
            $this->modifiedColumns[] = NotificacionEmailPeer::NOTIFICACIONEMAIL_ID;
        }


        return $this;
    } // setNotificacionemailId()

    /**
     * Set the value of [dependencia_id] column.
     * 
     * @param  int $v new value
     * @return NotificacionEmail The current object (for fluent API support)
     */
    public function setDependenciaId($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->dependencia_id !== $v) {
            $this->dependencia_id = $v;
            $this->modifiedColumns[] = NotificacionEmailPeer::DEPENDENCIA_ID;
        }

        if ($this->aDependencia !== null && $this->aDependencia->getDependenciaId() !== $v) {
            $this->aDependencia = null;
        }


        return $this;
    } // setDependenciaId()

    /**
     * Set the value of [host_smtp] column.
     * 
     * @param  string $v new value
     * @return NotificacionEmail The current object (for fluent API support)
     */
    public function setHostSmtp($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->host_smtp !== $v) {
            $this->host_smtp = $v;
            $this->modifiedColumns[] = NotificacionEmailPeer::HOST_SMTP;
        }


        return $this;
    } // setHostSmtp()

    /**
     * Set the value of [email_login] column.
     * 
     * @param  string $v new value
     * @return NotificacionEmail The current object (for fluent API support)
     */
    public function setEmailLogin($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->email_login !== $v) {
            $this->email_login = $v;
            $this->modifiedColumns[] = NotificacionEmailPeer::EMAIL_LOGIN;
        }


        return $this;
    } // setEmailLogin()

    /**
     * Set the value of [email_pass] column.
     * 
     * @param  string $v new value
     * @return NotificacionEmail The current object (for fluent API support)
     */
    public function setEmailPass($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->email_pass !== $v) {
            $this->email_pass = $v;
            $this->modifiedColumns[] = NotificacionEmailPeer::EMAIL_PASS;
        }


        return $this;
    } // setEmailPass()

    /**
     * Set the value of [puerto] column.
     * 
     * @param  int $v new value
     * @return NotificacionEmail The current object (for fluent API support)
     */
    public function setPuerto($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->puerto !== $v) {
            $this->puerto = $v;
            $this->modifiedColumns[] = NotificacionEmailPeer::PUERTO;
        }


        return $this;
    } // setPuerto()

    /**
     * Set the value of [secure_smtp] column.
     * 
     * @param  string $v new value
     * @return NotificacionEmail The current object (for fluent API support)
     */
    public function setSecureSmtp($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->secure_smtp !== $v) {
            $this->secure_smtp = $v;
            $this->modifiedColumns[] = NotificacionEmailPeer::SECURE_SMTP;
        }


        return $this;
    } // setSecureSmtp()

    /**
     * Set the value of [auth_smtp] column.
     * 
     * @param  int $v new value
     * @return NotificacionEmail The current object (for fluent API support)
     */
    public function setAuthSmtp($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->auth_smtp !== $v) {
            $this->auth_smtp = $v;
            $this->modifiedColumns[] = NotificacionEmailPeer::AUTH_SMTP;
        }


        return $this;
    } // setAuthSmtp()

    /**
     * Set the value of [certimail] column.
     * 
     * @param  string $v new value
     * @return NotificacionEmail The current object (for fluent API support)
     */
    public function setCertimail($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->certimail !== $v) {
            $this->certimail = $v;
            $this->modifiedColumns[] = NotificacionEmailPeer::CERTIMAIL;
        }


        return $this;
    } // setCertimail()

    /**
     * Set the value of [email_body] column.
     * 
     * @param  string $v new value
     * @return NotificacionEmail The current object (for fluent API support)
     */
    public function setEmailBody($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->email_body !== $v) {
            $this->email_body = $v;
            $this->modifiedColumns[] = NotificacionEmailPeer::EMAIL_BODY;
        }


        return $this;
    } // setEmailBody()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
        // otherwise, everything was equal, so return true
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param int $startcol 0-based offset column which indicates which resultset column to start with.
     * @param boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->notificacionemail_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->dependencia_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
            $this->host_smtp = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
            $this->email_login = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
            $this->email_pass = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
            $this->puerto = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
            $this->secure_smtp = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
            $this->auth_smtp = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
            $this->certimail = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
            $this->email_body = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }
            $this->postHydrate($row, $startcol, $rehydrate);

            return $startcol + 10; // 10 = NotificacionEmailPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating NotificacionEmail object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

        if ($this->aDependencia !== null && $this->dependencia_id !== $this->aDependencia->getDependenciaId()) {
            $this->aDependencia = null;
        }
    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param boolean $deep (optional) Whether to also de-associated any related objects.
     * @param PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(NotificacionEmailPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = NotificacionEmailPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

            $this->aDependencia = null;
        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(NotificacionEmailPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = NotificacionEmailQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseNotificacionEmail:delete:pre') as $callable)
            {
              if (call_user_func($callable, $this, $con))
              {
                $con->commit();
                return;
              }
            }

            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseNotificacionEmail:delete:post') as $callable)
                {
                  call_user_func($callable, $this, $con);
                }

                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(NotificacionEmailPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseNotificacionEmail:save:pre') as $callable)
            {
              if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
              {
                  $con->commit();
                return $affectedRows;
              }
            }

            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseNotificacionEmail:save:post') as $callable)
                {
                  call_user_func($callable, $this, $con, $affectedRows);
                }

                NotificacionEmailPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            // We call the save method on the following object(s) if they
            // were passed to this object by their corresponding set
            // method.  This object relates to these object(s) by a
            // foreign key reference.

            if ($this->aDependencia !== null) {
                if ($this->aDependencia->isModified() || $this->aDependencia->isNew()) {
                    $affectedRows += $this->aDependencia->save($con);
                }
                $this->setDependencia($this->aDependencia);
            }

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $this->modifiedColumns[] = NotificacionEmailPeer::NOTIFICACIONEMAIL_ID;
        $criteria = $this->buildCriteria();
        if ($criteria->keyContainsValue(NotificacionEmailPeer::NOTIFICACIONEMAIL_ID) ) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . NotificacionEmailPeer::NOTIFICACIONEMAIL_ID . ')');
        }
        // remove pkey col since this table uses auto-increment and passing a null value for it is not valid
        $criteria->remove(NotificacionEmailPeer::NOTIFICACIONEMAIL_ID);
        $pk = BasePeer::doInsert($criteria, $con);
        $this->setNotificacionemailId($pk);  //[IMV] update autoincrement primary key
        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        }

        $this->validationFailures = $res;

        return false;
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggregated array of ValidationFailed objects will be returned.
     *
     * @param array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objects otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            // We call the validate method on the following object(s) if they
            // were passed to this object by their corresponding set
            // method.  This object relates to these object(s) by a
            // foreign key reference.

            if ($this->aDependencia !== null) {
                if (!$this->aDependencia->validate($columns)) {
                    $failureMap = array_merge($failureMap, $this->aDependencia->getValidationFailures());
                }
            }


            if (($retval = NotificacionEmailPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }



            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param string $name name
     * @param string $type The type of fieldname the $name is of:
     *               one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *               BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *               Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = NotificacionEmailPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getNotificacionemailId();
                break;
            case 1:
                return $this->getDependenciaId();
                break;
            case 2:
                return $this->getHostSmtp();
                break;
            case 3:
                return $this->getEmailLogin();
                break;
            case 4:
                return $this->getEmailPass();
                break;
            case 5:
                return $this->getPuerto();
                break;
            case 6:
                return $this->getSecureSmtp();
                break;
            case 7:
                return $this->getAuthSmtp();
                break;
            case 8:
                return $this->getCertimail();
                break;
            case 9:
                return $this->getEmailBody();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to true.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
    {
        if (isset($alreadyDumpedObjects['NotificacionEmail'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['NotificacionEmail'][$this->getPrimaryKey()] = true;
        $keys = NotificacionEmailPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getNotificacionemailId(),
            $keys[1] => $this->getDependenciaId(),
            $keys[2] => $this->getHostSmtp(),
            $keys[3] => $this->getEmailLogin(),
            $keys[4] => $this->getEmailPass(),
            $keys[5] => $this->getPuerto(),
            $keys[6] => $this->getSecureSmtp(),
            $keys[7] => $this->getAuthSmtp(),
            $keys[8] => $this->getCertimail(),
            $keys[9] => $this->getEmailBody(),
        );
        $virtualColumns = $this->virtualColumns;
        foreach ($virtualColumns as $key => $virtualColumn) {
            $result[$key] = $virtualColumn;
        }
        
        if ($includeForeignObjects) {
            if (null !== $this->aDependencia) {
                $result['Dependencia'] = $this->aDependencia->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }
        }

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param string $name peer name
     * @param mixed $value field value
     * @param string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = NotificacionEmailPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @param mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setNotificacionemailId($value);
                break;
            case 1:
                $this->setDependenciaId($value);
                break;
            case 2:
                $this->setHostSmtp($value);
                break;
            case 3:
                $this->setEmailLogin($value);
                break;
            case 4:
                $this->setEmailPass($value);
                break;
            case 5:
                $this->setPuerto($value);
                break;
            case 6:
                $this->setSecureSmtp($value);
                break;
            case 7:
                $this->setAuthSmtp($value);
                break;
            case 8:
                $this->setCertimail($value);
                break;
            case 9:
                $this->setEmailBody($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param array  $arr     An array to populate the object from.
     * @param string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = NotificacionEmailPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setNotificacionemailId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setDependenciaId($arr[$keys[1]]);
        if (array_key_exists($keys[2], $arr)) $this->setHostSmtp($arr[$keys[2]]);
        if (array_key_exists($keys[3], $arr)) $this->setEmailLogin($arr[$keys[3]]);
        if (array_key_exists($keys[4], $arr)) $this->setEmailPass($arr[$keys[4]]);
        if (array_key_exists($keys[5], $arr)) $this->setPuerto($arr[$keys[5]]);
        if (array_key_exists($keys[6], $arr)) $this->setSecureSmtp($arr[$keys[6]]);
        if (array_key_exists($keys[7], $arr)) $this->setAuthSmtp($arr[$keys[7]]);
        if (array_key_exists($keys[8], $arr)) $this->setCertimail($arr[$keys[8]]);
        if (array_key_exists($keys[9], $arr)) $this->setEmailBody($arr[$keys[9]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(NotificacionEmailPeer::DATABASE_NAME);

        if ($this->isColumnModified(NotificacionEmailPeer::NOTIFICACIONEMAIL_ID)) $criteria->add(NotificacionEmailPeer::NOTIFICACIONEMAIL_ID, $this->notificacionemail_id);
        if ($this->isColumnModified(NotificacionEmailPeer::DEPENDENCIA_ID)) $criteria->add(NotificacionEmailPeer::DEPENDENCIA_ID, $this->dependencia_id);
        if ($this->isColumnModified(NotificacionEmailPeer::HOST_SMTP)) $criteria->add(NotificacionEmailPeer::HOST_SMTP, $this->host_smtp);
        if ($this->isColumnModified(NotificacionEmailPeer::EMAIL_LOGIN)) $criteria->add(NotificacionEmailPeer::EMAIL_LOGIN, $this->email_login);
        if ($this->isColumnModified(NotificacionEmailPeer::EMAIL_PASS)) $criteria->add(NotificacionEmailPeer::EMAIL_PASS, $this->email_pass);
        if ($this->isColumnModified(NotificacionEmailPeer::PUERTO)) $criteria->add(NotificacionEmailPeer::PUERTO, $this->puerto);
        if ($this->isColumnModified(NotificacionEmailPeer::SECURE_SMTP)) $criteria->add(NotificacionEmailPeer::SECURE_SMTP, $this->secure_smtp);
        if ($this->isColumnModified(NotificacionEmailPeer::AUTH_SMTP)) $criteria->add(NotificacionEmailPeer::AUTH_SMTP, $this->auth_smtp);
        if ($this->isColumnModified(NotificacionEmailPeer::CERTIMAIL)) $criteria->add(NotificacionEmailPeer::CERTIMAIL, $this->certimail);
        if ($this->isColumnModified(NotificacionEmailPeer::EMAIL_BODY)) $criteria->add(NotificacionEmailPeer::EMAIL_BODY, $this->email_body);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(NotificacionEmailPeer::DATABASE_NAME);
        $criteria->add(NotificacionEmailPeer::NOTIFICACIONEMAIL_ID, $this->notificacionemail_id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return int
     */
    public function getPrimaryKey()
    {
        return $this->getNotificacionemailId();
    }

    /**
     * Generic method to set the primary key (notificacionemail_id column).
     *
     * @param  int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setNotificacionemailId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getNotificacionemailId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param object $copyObj An object of NotificacionEmail (or compatible) type.
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setDependenciaId($this->getDependenciaId());
        $copyObj->setHostSmtp($this->getHostSmtp());
        $copyObj->setEmailLogin($this->getEmailLogin());
        $copyObj->setEmailPass($this->getEmailPass());
        $copyObj->setPuerto($this->getPuerto());
        $copyObj->setSecureSmtp($this->getSecureSmtp());
        $copyObj->setAuthSmtp($this->getAuthSmtp());
        $copyObj->setCertimail($this->getCertimail());
        $copyObj->setEmailBody($this->getEmailBody());

        if ($deepCopy && !$this->startCopy) {
            // important: temporarily setNew(false) because this affects the behavior of
            // the getter/setter methods for fkey referrer objects.
            $copyObj->setNew(false);
            // store object hash to prevent cycle
            $this->startCopy = true;

            //unflag object copy
            $this->startCopy = false;
        } // if ($deepCopy)

        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setNotificacionemailId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return NotificacionEmail Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return NotificacionEmailPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new NotificacionEmailPeer();
        }

        return self::$peer;
    }

    /**
     * Declares an association between this object and a Dependencia object.
     *
     * @param                  Dependencia $v
     * @return NotificacionEmail The current object (for fluent API support)
     * @throws PropelException
     */
    public function setDependencia(Dependencia $v = null)
    {
        if ($v === null) {
            $this->setDependenciaId(NULL);
        } else {
            $this->setDependenciaId($v->getDependenciaId());
        }

        $this->aDependencia = $v;

        // Add binding for other direction of this n:n relationship.
        // If this object has already been added to the Dependencia object, it will not be re-added.
        if ($v !== null) {
            $v->addNotificacionEmail($this);
        }


        return $this;
    }


    /**
     * Get the associated Dependencia object
     *
     * @param PropelPDO $con Optional Connection object.
     * @param $doQuery Executes a query to get the object if required
     * @return Dependencia The associated Dependencia object.
     * @throws PropelException
     */
    public function getDependencia(PropelPDO $con = null, $doQuery = true)
    {
        if ($this->aDependencia === null && ($this->dependencia_id !== null) && $doQuery) {
            $this->aDependencia = DependenciaQuery::create()->findPk($this->dependencia_id, $con);
            /* The following can be used additionally to
                guarantee the related object contains a reference
                to this object.  This level of coupling may, however, be
                undesirable since it could result in an only partially populated collection
                in the referenced object.
                $this->aDependencia->addNotificacionEmails($this);
             */
        }

        return $this->aDependencia;
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->notificacionemail_id = null;
        $this->dependencia_id = null;
        $this->host_smtp = null;
        $this->email_login = null;
        $this->email_pass = null;
        $this->puerto = null;
        $this->secure_smtp = null;
        $this->auth_smtp = null;
        $this->certimail = null;
        $this->email_body = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->alreadyInClearAllReferencesDeep = false;
        $this->clearAllReferences();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volume/high-memory operations.
     *
     * @param boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep && !$this->alreadyInClearAllReferencesDeep) {
            $this->alreadyInClearAllReferencesDeep = true;
            if ($this->aDependencia instanceof Persistent) {
              $this->aDependencia->clearAllReferences($deep);
            }

            $this->alreadyInClearAllReferencesDeep = false;
        } // if ($deep)

        $this->aDependencia = null;
    }

    /**
     * return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(NotificacionEmailPeer::DEFAULT_STRING_FORMAT);
    }

    /**
     * return true is the object is in saving state
     *
     * @return boolean
     */
    public function isAlreadyInSave()
    {
        return $this->alreadyInSave;
    }

    /**
     * Catches calls to virtual methods
     */
    public function __call($name, $params)
    {
        
        // symfony_behaviors behavior
        if ($callable = sfMixer::getCallable('BaseNotificacionEmail:' . $name))
        {
          array_unshift($params, $this);
          return call_user_func_array($callable, $params);
        }


        return parent::__call($name, $params);
    }

}
