-- =====================================================================================
-- UARIV-202605 — Flujo de aprobación configurable para Actos Administrativos
-- DDL/DML completo para PRIMER despliegue a PRODUCTIVO (9 fases originales + ampliación A-E)
-- Generado a partir del diff real de config/schema.yml contra la línea base previa al
-- requerimiento (commit 47df76db). Ejecutar en una transacción / con backup previo (ver minutograma).
-- =====================================================================================

BEGIN TRANSACTION;

-- =====================================================================================
-- 1. TABLAS NUEVAS
-- =====================================================================================

-- Catálogo de etapas del flujo configurable (Fase 1) + candado de edición global (ampliación)
CREATE TABLE ACTOADMIN_ETAPA (
    ACTOADMINETAPA_ID INT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    ROLUSUARIOACTOADMINISTVO_ID INT NOT NULL,
    ORDEN SMALLINT NOT NULL,
    ESTA_ACTIVO TINYINT NOT NULL CONSTRAINT DF_ACTOADMIN_ETAPA_ESTA_ACTIVO DEFAULT (1),
    TAG_PREFIJO NVARCHAR(30) NOT NULL,
    PERMITE_EDICION TINYINT NOT NULL CONSTRAINT DF_ACTOADMIN_ETAPA_PERMITE_EDICION DEFAULT (1),
    FECHA_CREACION DATETIME2(3) NOT NULL,
    FECHA_MODIFICACION DATETIME2(3) NOT NULL,
    CONSTRAINT PK_ACTOADMIN_ETAPA PRIMARY KEY (ACTOADMINETAPA_ID),
    CONSTRAINT FK_ACTOADMIN_ETAPA_ROL FOREIGN KEY (ROLUSUARIOACTOADMINISTVO_ID) REFERENCES ROL_USUARIO_ACTO_ADMINISTVO (ROLUSUARIOACTOADMINISTVO_ID)
);
CREATE INDEX IX_ACTOADMIN_ETAPA_ORDEN ON ACTOADMIN_ETAPA (ORDEN);
GO

-- Bitácora del flujo (registra cada transición: creación, aprobación, devolución, firma, radicación, finalización, purga)
CREATE TABLE ACTOADMIN_ETAPA_BITACORA (
    ACTOADMINETAPABITACORA_ID INT IDENTITY(1,1) NOT NULL,
    ACTOADMINISTRATIVO_ID INT NOT NULL,
    ACTOADMINETAPA_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    ROLUSUARIOACTOADMINISTVO_ID INT NOT NULL,
    ESTADOACTOADMINISTRATIVO_ID INT NOT NULL,
    ACCION NVARCHAR(30) NOT NULL,
    OBSERVACION NVARCHAR(900) NULL,
    FECHA_ACCION DATETIME2(3) NOT NULL,
    CONSTRAINT PK_ACTOADMIN_ETAPA_BITACORA PRIMARY KEY (ACTOADMINETAPABITACORA_ID),
    CONSTRAINT FK_ACTOADMIN_ETAPA_BITACORA_ACTO FOREIGN KEY (ACTOADMINISTRATIVO_ID) REFERENCES ACTO_ADMINISTRATIVO (ACTOADMINISTRATIVO_ID),
    CONSTRAINT FK_ACTOADMIN_ETAPA_BITACORA_ETAPA FOREIGN KEY (ACTOADMINETAPA_ID) REFERENCES ACTOADMIN_ETAPA (ACTOADMINETAPA_ID),
    CONSTRAINT FK_ACTOADMIN_ETAPA_BITACORA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID),
    CONSTRAINT FK_ACTOADMIN_ETAPA_BITACORA_ROL FOREIGN KEY (ROLUSUARIOACTOADMINISTVO_ID) REFERENCES ROL_USUARIO_ACTO_ADMINISTVO (ROLUSUARIOACTOADMINISTVO_ID),
    CONSTRAINT FK_ACTOADMIN_ETAPA_BITACORA_ESTADO FOREIGN KEY (ESTADOACTOADMINISTRATIVO_ID) REFERENCES ESTADO_ACTO_ADMINISTRATIVO (ESTADOACTOADMINISTRATIVO_ID)
);
CREATE INDEX IX_ACTOADMIN_ETAPA_BITACORA_ACTO ON ACTOADMIN_ETAPA_BITACORA (ACTOADMINISTRATIVO_ID);
GO

-- Configuración global: días de retención de versiones preliminares (Fase 7)
CREATE TABLE ACTOADMIN_CONFIGURACION (
    ACTOADMINCONFIGURACION_ID INT IDENTITY(1,1) NOT NULL,
    DIAS_RETENCION_BORRADOR INT NOT NULL CONSTRAINT DF_ACTOADMIN_CONFIGURACION_DIAS DEFAULT (0),
    USUARIO_ID INT NOT NULL,
    FECHA_MODIFICACION DATETIME2(3) NOT NULL,
    CONSTRAINT PK_ACTOADMIN_CONFIGURACION PRIMARY KEY (ACTOADMINCONFIGURACION_ID),
    CONSTRAINT FK_ACTOADMIN_CONFIGURACION_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID)
);
GO

-- Historial de versiones del archivo Word (ampliación)
CREATE TABLE ACTOADMIN_WORD_VERSION (
    ACTOADMINWORDVERSION_ID INT IDENTITY(1,1) NOT NULL,
    ACTOADMINISTRATIVO_ID INT NOT NULL,
    RUTA_ARCHIVO NVARCHAR(500) NOT NULL,
    VERSION_NUMBER INT NOT NULL,
    CURRENT_VERSION TINYINT NOT NULL CONSTRAINT DF_ACTOADMIN_WORD_VERSION_CURRENT DEFAULT (0),
    USUARIO_ID INT NOT NULL,
    FECHA_CREACION DATETIME2(3) NOT NULL,
    CONSTRAINT PK_ACTOADMIN_WORD_VERSION PRIMARY KEY (ACTOADMINWORDVERSION_ID),
    CONSTRAINT FK_ACTOADMIN_WORD_VERSION_ACTO FOREIGN KEY (ACTOADMINISTRATIVO_ID) REFERENCES ACTO_ADMINISTRATIVO (ACTOADMINISTRATIVO_ID),
    CONSTRAINT FK_ACTOADMIN_WORD_VERSION_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID)
);
CREATE INDEX IX_ACTOADMIN_WORD_VERSION_ACTO ON ACTOADMIN_WORD_VERSION (ACTOADMINISTRATIVO_ID);
GO

-- Override por acto puntual del candado de edición por etapa (ampliación)
CREATE TABLE ACTOADMIN_ETAPA_ACTO_CONFIG (
    ACTOADMINETAPAACTOCONFIG_ID INT IDENTITY(1,1) NOT NULL,
    ACTOADMINISTRATIVO_ID INT NOT NULL,
    ACTOADMINETAPA_ID INT NOT NULL,
    PERMITE_EDICION TINYINT NOT NULL,
    USUARIO_ID INT NOT NULL,
    FECHA_MODIFICACION DATETIME2(3) NOT NULL,
    CONSTRAINT PK_ACTOADMIN_ETAPA_ACTO_CONFIG PRIMARY KEY (ACTOADMINETAPAACTOCONFIG_ID),
    CONSTRAINT FK_ACTOADMIN_ETAPA_ACTO_CONFIG_ACTO FOREIGN KEY (ACTOADMINISTRATIVO_ID) REFERENCES ACTO_ADMINISTRATIVO (ACTOADMINISTRATIVO_ID),
    CONSTRAINT FK_ACTOADMIN_ETAPA_ACTO_CONFIG_ETAPA FOREIGN KEY (ACTOADMINETAPA_ID) REFERENCES ACTOADMIN_ETAPA (ACTOADMINETAPA_ID),
    CONSTRAINT FK_ACTOADMIN_ETAPA_ACTO_CONFIG_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID)
);
CREATE UNIQUE INDEX IX_ACTOADMIN_ETAPA_ACTO_CONFIG_UNICO ON ACTOADMIN_ETAPA_ACTO_CONFIG (ACTOADMINISTRATIVO_ID, ACTOADMINETAPA_ID);
GO

-- =====================================================================================
-- 2. COLUMNAS NUEVAS EN TABLAS EXISTENTES
-- =====================================================================================

-- Devolución: a qué etapa concreta del catálogo se devolvió (antes solo guardaba el rol)
ALTER TABLE ACTOADMIN_DEVOLUCION ADD ACTOADMINETAPA_ID INT NULL
    CONSTRAINT FK_ACTOADMIN_DEVOLUCION_ETAPA FOREIGN KEY REFERENCES ACTOADMIN_ETAPA (ACTOADMINETAPA_ID);
GO

-- Participantes del acto: etapa del catálogo asociada, orden de ejecución por documento y candado de edición por participante
ALTER TABLE ACTOADMINISTRATIVO_USUARIO ADD ACTOADMINETAPA_ID INT NULL
    CONSTRAINT FK_ACTOADMINISTRATIVO_USUARIO_ETAPA FOREIGN KEY REFERENCES ACTOADMIN_ETAPA (ACTOADMINETAPA_ID);
ALTER TABLE ACTOADMINISTRATIVO_USUARIO ADD ORDEN_EJECUCION SMALLINT NULL;
ALTER TABLE ACTOADMINISTRATIVO_USUARIO ADD PUEDE_EDITAR TINYINT NULL
    CONSTRAINT DF_ACTOADMINISTRATIVO_USUARIO_PUEDE_EDITAR DEFAULT (1);
GO

-- Radicación masiva por contingencia (Fase 8): si se debe crear el interesado automáticamente
ALTER TABLE COM_MIGMASIVO ADD CREAR_INTERESADO TINYINT NULL
    CONSTRAINT DF_COM_MIGMASIVO_CREAR_INTERESADO DEFAULT (0);
GO

-- =====================================================================================
-- 3. PERMISOS NUEVOS (tabla FORMA) — AJUSTAR @modulo_id ANTES DE EJECUTAR
-- =====================================================================================
-- Verificar primero el MODULO_ID real del módulo "Actos Administrativos" en este ambiente:
--   SELECT DISTINCT F.MODULO_ID FROM FORMA F WHERE F.NOMBRE LIKE 'ACTO_ADMINISTRATIVO_%';
-- Reemplazar el valor de @modulo_id abajo con el resultado antes de ejecutar esta sección.

DECLARE @modulo_id INT = NULL; -- <-- COMPLETAR

IF @modulo_id IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FORMA WHERE NOMBRE = 'ACTO_ADMINISTRATIVO_USAR_PDF')
        INSERT INTO FORMA (MODULO_ID, NOMBRE, DESCRIPCION, IS_PUBLIC)
        VALUES (@modulo_id, 'ACTO_ADMINISTRATIVO_USAR_PDF', 'Permite adjuntar el acto administrativo como PDF directo (sin generar desde plantilla Word)', 0);

    IF NOT EXISTS (SELECT 1 FROM FORMA WHERE NOMBRE = 'ACTO_ADMINISTRATIVO_CONFIGURAR_FLUJO')
        INSERT INTO FORMA (MODULO_ID, NOMBRE, DESCRIPCION, IS_PUBLIC)
        VALUES (@modulo_id, 'ACTO_ADMINISTRATIVO_CONFIGURAR_FLUJO', 'Permite configurar el orden de ejecución y el candado de edición por acto administrativo puntual', 0);

    IF NOT EXISTS (SELECT 1 FROM FORMA WHERE NOMBRE = 'ACTO_ADMINISTRATIVO_VER_VERSIONES_PRELIMINARES')
        INSERT INTO FORMA (MODULO_ID, NOMBRE, DESCRIPCION, IS_PUBLIC)
        VALUES (@modulo_id, 'ACTO_ADMINISTRATIVO_VER_VERSIONES_PRELIMINARES', 'Permite consultar versiones preliminares de un acto administrativo ya radicado', 0);
END
ELSE
BEGIN
    RAISERROR('Debe completar @modulo_id antes de ejecutar la sección de permisos (FORMA).', 16, 1);
END
GO

-- =====================================================================================
-- 4. DATOS INICIALES RECOMENDADOS (ajustar a la operación real del cliente antes de ejecutar)
-- =====================================================================================
-- ACTOADMIN_CONFIGURACION necesita al menos una fila para que ActoadminConfiguracionPeer::getConfiguracionActual()
-- no falle. DIAS_RETENCION_BORRADOR = 0 desactiva la depuración automática hasta que el cliente la configure
-- desde la pantalla de administración.
IF NOT EXISTS (SELECT 1 FROM ACTOADMIN_CONFIGURACION)
BEGIN
    INSERT INTO ACTOADMIN_CONFIGURACION (DIAS_RETENCION_BORRADOR, USUARIO_ID, FECHA_MODIFICACION)
    VALUES (0, 1, GETDATE()); -- <-- Ajustar USUARIO_ID al administrador real
END
GO

COMMIT TRANSACTION;
