<?php
// auto-generated by sfPropelCrud
// date: 2025/07/01 12:39:12
$path_theme = sfConfig::get('theme_simad');
$base_path = sfConfig::get('base_simad');
$currentUser = $sf_user->getAttribute('usuario_id', '', 'subscriber');

use_helper('Object','jQuery');
?>
<div class="row">
    <div class="col-md-12">
        <!-- Contenedor Pagina -->
        <div class="panel panel-gradient" data-collapsed="0">
            <div class="panel-heading">
                <div class="panel-title">
                    <?php echo $expediente_etiqueta->getPrimaryKey() ? "Editar" : "Crear" ?> Etiqueta
                </div>
            </div>
            <!-- Contenedor de Mensajes de error -->
            <?php if ($sf_user->hasFlash('messages_success')): ?>
                <div class="alert alert-success"><strong>Excelente! </strong><?php echo $sf_user->getFlash('messages_success') ?></div>
            <?php endif ?>     
            <?php if ($sf_user->hasFlash('messages_info')): ?>
                <div class="alert alert-info"><strong>!Informaci&oacute;n </strong><?php echo $sf_user->getFlash('messages_info') ?></div>
            <?php endif ?>
            <?php if ($sf_user->hasFlash('messages_error')): ?>
                <div class="alert alert-danger"><strong>Opps! </strong><?php echo $sf_user->getFlash('messages_error') ?></div>
            <?php endif ?>
            <?php if ($sf_user->hasFlash('messages_warning')): ?>
                <div class="alert alert-warning"><strong>!Atenci&oacute;n </strong><?php echo $sf_user->getFlash('messages_warning') ?></div>
            <?php endif ?>
            <!-- Contenedor Contenido Formulario-->
            <div class="panel-body">                
                <?php echo form_tag('automatizacion_unidaddoc/updateNewEtiqueta', array('name'=>'form1', 'role' => 'form', 'class' => 'form-groups-bordered validate')); ?>
                    <?php echo object_input_hidden_tag($expediente_etiqueta, 'getModuloId'); ?>
                    <?php echo object_input_hidden_tag($expediente_etiqueta, 'getExpedienteetiquetaId'); ?>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <!-- Nombre Regla -->
                                <label for="lbgetNombreEtiqueta" class="control-label">Nombre Etiqueta<span class="ctrlreq">(*)</span>:</label>
                                <?php    					
                                    echo object_input_tag($expediente_etiqueta, 'getNombre', array ('data-validate'=>'minlength[3]', 'data-validate'=>'maxlength[20]', 'class' => 'form-control input-sm required','placeholder'=>'Digite el nombre de la etiqueta'));
                                ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                            <!-- Descripcion Etiqueta -->
                            <label for="lbgetDescripcionEtiqueta" class="control-label">Descripci&oacute;n Etiqueta<span class="ctrlreq">(*)</span>:</label>				  
                            <?php
                                echo object_textarea_tag($expediente_etiqueta, 'getDescripcion', array ('data-validate'=>'minlength[4]', 'data-validate'=>'maxlength[250]', 'class' => 'form-control input-sm required','placeholder'=>'Digite descripci&oacute;n de la etiqueta'));
                            ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <!-- Modulo Metadatos -->
                                <label for="lbModuloMetadatos" class="control-label">Metadato Origen<span class="ctrlreq">(*)</span>:</label>
                                <select name="modulo_metadato" id="modulo_metadato" class="select2 form-control input-sm required" data-allow-clear="true" data-placeholder="Seleccione Modulo...">
                                    <option value="">Seleccione...</option>
                                    <?php
                                        foreach ($metadatos_modulo as $row) {
                                            echo '<option value="'.$row['id'].'">'.$row['text'].'</option>';
                                        }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <!-- Botonera -->
                            <div class="col-sm-offset-8 col-sm-3">
                                <div class="col-sm-offset-3 col-sm-10">
                                    <button id='saveNewEtiqueta' name='saveNewEtiqueta' type="submit" class="btn btn-success" href="#" data-toggle='tooltip' data-original-title='Gardar registro'>
                                        <i class="entypo-floppy"></i>Guardar Registro
                                    </button>
                                
                                    <a class="btn btn-red" href="#" onclick="javascript:jQuery.CloseModalRefreshParent()" >
                                        <i class="entypo-cancel"></i>Cerrar
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                </form>
            </div>
        </div>
    </div>
</div>