<?php
// auto-generated by sfPropelCrud
// date: 2008/08/20 18:34:53
?>
<?php

/**
 * solicitud_prestamo_cliente actions.
 *
 * @package    simad
 * @subpackage solicitud_prestamo_cliente
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
include_once(sfConfig::get('sf_lib_dir')."/Fechas.class.php");
class solicitud_prestamo_clienteActions extends sfActions
{
	
  public function verificaPrilegio($currentForm)
  { 
  	$usuariologuiado = $this->getUser()->getAttribute('usuario_id', '', 'subscriber');
	if(!$this->getUser()->checkPerm($currentForm, $usuariologuiado)){
		$this->redirect(sfConfig::get('base_simad').'/no_autorizado.html');
	}	 
  }
  
  public function verificaPrilegioCerrar($currentForm)
  { 
 	$usuariologuiado = $this->getUser()->getAttribute('usuario_id', '', 'subscriber');
	if(!$this->getUser()->checkPerm($currentForm, $usuariologuiado)){
		$this->redirect(sfConfig::get('base_simad').'/no_autorizado.html');
	}	 	  
  }
  
  public function executeIndex()
  {
    return $this->forward('solicitud_prestamo_cliente', 'list');
  }

  public function executeList()
  {
  	$currentForm="solicitud_prestamo_cliente/list";
  	$this->verificaPrilegio($currentForm);
    $c = new Criteria();
    $c->setDistinct();
    $usuariologueado           = $this->getUser()->getAttribute('usuario_id', '', 'subscriber');
    $parametros = '';
    /**************************************************************************************************************/
    if($this->getRequestParameter('misSolicitudes')){
		$c->add(ClSolicitudPrestamoPeer::USUARIO_ID, $usuariologueado);
		$parametros .= "&misSolicitudes=".$this->getRequestParameter('misSolicitudes');		
	}
	/**************************************************************************************************************/
	if($this->getRequestParameter('codCliente')){
		$c->addJoin(ClSolicitudPrestamoPeer::CLIENTE_ID, ClientePeer::CLIENTE_ID);	    
	    $c->add(ClientePeer::CODIGO_CLIENTE,'%'.$this->getRequestParameter('codCliente').'%',Criteria::LIKE);
		$parametros .= "&codCliente=".$this->getRequestParameter('codCliente');				
	}		
    /************************************************************************************************************/
    if($this->getRequestParameter('nombCliente')){
		$c->addJoin(ClSolicitudPrestamoPeer::CLIENTE_ID, ClientePeer::CLIENTE_ID);	    
	    $c->add(ClientePeer::NOMBRE_CLIENTE,'%'.$this->getRequestParameter('nombCliente').'%',Criteria::LIKE);
		$parametros .= "&nombCliente=".$this->getRequestParameter('nombCliente');				
	}		
    /************************************************************************************************************/
    if($this->getRequestParameter('numSolicitud')){			    
	    $c->add(ClSolicitudPrestamoPeer::CLSOLICITUDPRESTAMO_ID,$this->getRequestParameter('numSolicitud'));
		$parametros .= "&numSolicitud=".$this->getRequestParameter('numSolicitud');				
	}		
    /************************************************************************************************************/
    if($this->getRequestParameter('usuario_id')){
		$c->add(ClSolicitudPrestamoPeer::USUARIO_ID, $this->getRequestParameter('usuario_id'));
		$parametros.= "&usuario_id=".$this->getRequestParameter('usuario_id');		
	}	
	/**************************************************************************************************************/
	if($this->getRequestParameter('cl_solicitud_prestamo_estado_id')){			    
	    $c->add(ClSolicitudPrestamoPeer::CLSOLICITUDPRESTAMOESTADO_ID,$this->getRequestParameter('cl_solicitud_prestamo_estado_id'));
		$parametros.= "&cl_solicitud_prestamo_estado_id=".$this->getRequestParameter('cl_solicitud_prestamo_estado_id');				
	}
	/************************************************************************************************************/
	if ($this->getRequestParameter('fechaInicial')) {
			if ($this->getRequestParameter('fechaFinal')) {
	            $c->add(ClSolicitudPrestamoPeer::FECHA_CREACION,$this->getRequestParameter('fechaInicial'),Criteria::GREATER_THAN);
	            $c->addAnd(ClSolicitudPrestamoPeer::FECHA_CREACION,$this->getRequestParameter('fechaFinal'),Criteria::LESS_THAN);
	            $this->parametros .= "&fechaInicial=" . str_replace("/","-",$this->getRequestParameter('fechaInicial'));
	        }else{
			    $c->add(ClSolicitudPrestamoPeer::FECHA_CREACION,$this->getRequestParameter('fechaInicial'),Criteria::GREATER_THAN);
			    $this->parametros .= "&fechaInicial=" . str_replace("/","-",$this->getRequestParameter('fechaFinal'));
		    }
	}
	/**************************************************************************************************************/
	if(!$this->getUser()->checkPerm('SOLICITUD_PRESTAMO_CLIENTES_LISTAR_TODAS', $usuariologueado)){
		$c->add(ClSolicitudPrestamoPeer::USUARIO_ID,$usuariologueado);
		//exit();
	}elseif($this->getUser()->checkPerm('SOLICITUD_PRESTAMO_CLIENTES_LISTAR_REGIONAL', $usuariologueado)){
		//$c->addJoin(ClSolicitudPrestamoPeer::USUARIO_ID,UsuarioPeer::USUARIO_ID);
		//$c->add(UsuarioPeer)
	}elseif($this->getUser()->checkPerm('SOLICITUD_PRESTAMO_CLIENTES_LISTAR_PROPIAS', $usuariologueado)){
		$c->add(ClSolicitudPrestamoPeer::USUARIO_ID,$usuariologueado);
		//exit();
	}	
    /*************************Consulta Para Las Solicitudes Pendientes*********************************************/
		$cadSolicitud   = $this->getUser()->getAttribute('solicitud_cliente','','prestamo_cliente');
		$arrIds         = split(",",$cadSolicitud);		
		$a = new Criteria();
		$a->add(ClSolicitudPrestamoPeer::CLSOLICITUDPRESTAMO_ID,$arrIds,Criteria::IN);
		//$a->add(SolicitudPrestamoPeer::USUARIO_ID,$usuariologueado);	
		
		$pagina = new sfPropelPager('ClSolicitudPrestamo',10);
		$pagina->setCriteria($a);
		$pagina->setPage($this->getRequestParameter('page',1));
		$pagina->init();
		$this->pagina = $pagina;
		$this->arrIds = $arrIds;		
	/*************************************************************************************************************/
	
    /**************************************************************************************************************/
  	$pager=new sfPropelPager('ClSolicitudPrestamo',10);
	$pager->setCriteria($c);
	$pager->setPage($this->getRequestParameter('page',1));
	$pager->init();
	$this->pager=$pager;
	$this->filtros_consulta = $parametros;
	//$this->usuariologueado = $usuariologueado;
	/**************************************************************************************************************/
	$estados= array();
	$i = 0;	
	foreach($pager->getResults() as $linea){		
		//$b->setDistinct();
		$b = new Criteria();		
		$b->addJoin(ClDetallePrestamoPeer::CLSOLICITUDPRESTAMO_ID,ClSolicitudPrestamoPeer::CLSOLICITUDPRESTAMO_ID);
		$b->add(ClDetallePrestamoPeer::CLESTADOPRESTAMO_ID,1);	
		$b->add(ClSolicitudPrestamoPeer::CLIENTE_ID,$linea->getClienteId());		
		$detalle  = ClSolicitudPrestamoPeer::doSelectOne($b);
		if($detalle != null){
			$estados[]= 1;
		}else{
			$estados[]= 0;
		}												
	}	
	$this->estados = $estados; 
  }
  
  public function executeExcel()
  {
    $c  = new Criteria();  	
  	$usuariologueado     = $this->getUser()->getAttribute('usuario_id', '', 'subscriber');
  	$this->user_name     = $this->getUser()->getAttribute('username', '', 'subscriber');
    $parametros = '';
    /**************************************************************************************************************/
    if($this->getRequestParameter('misSolicitudes')){
		$c->add(ClSolicitudPrestamoPeer::USUARIO_ID, $usuariologueado);
		$parametros .= "&misSolicitudes=".$this->getRequestParameter('misSolicitudes');		
	}
	/**************************************************************************************************************/
	if($this->getRequestParameter('codCliente')){
		$c->addJoin(ClSolicitudPrestamoPeer::CLIENTE_ID, ClientePeer::CLIENTE_ID);	    
	    $c->add(ClientePeer::CODIGO_CLIENTE,'%'.$this->getRequestParameter('codCliente').'%',Criteria::LIKE);
		$parametros .= "&codCliente=".$this->getRequestParameter('codCliente');				
	}		
    /************************************************************************************************************/
    if($this->getRequestParameter('nombCliente')){
		$c->addJoin(ClSolicitudPrestamoPeer::CLIENTE_ID, ClientePeer::CLIENTE_ID);	    
	    $c->add(ClientePeer::NOMBRE_CLIENTE,'%'.$this->getRequestParameter('nombCliente').'%',Criteria::LIKE);
		$parametros .= "&nombCliente=".$this->getRequestParameter('nombCliente');				
	}		
    /************************************************************************************************************/
    if($this->getRequestParameter('numSolicitud')){			    
	    $c->add(ClSolicitudPrestamoPeer::CLSOLICITUDPRESTAMO_ID,$this->getRequestParameter('numSolicitud'));
		$parametros .= "&numSolicitud=".$this->getRequestParameter('numSolicitud');				
	}		
    /************************************************************************************************************/
    if($this->getRequestParameter('usuario_id')){
		$c->add(ClSolicitudPrestamoPeer::USUARIO_ID, $this->getRequestParameter('usuario_id'));
		$parametros.= "&usuario_id=".$this->getRequestParameter('usuario_id');		
	}	
	/**************************************************************************************************************/
	if($this->getRequestParameter('cl_solicitud_prestamo_estado_id')){			    
	    $c->add(ClSolicitudPrestamoPeer::CLSOLICITUDPRESTAMOESTADO_ID,$this->getRequestParameter('cl_solicitud_prestamo_estado_id'));
		$parametros.= "&cl_solicitud_prestamo_estado_id=".$this->getRequestParameter('cl_solicitud_prestamo_estado_id');				
	}
	/************************************************************************************************************/
	if ($this->getRequestParameter('fechaInicial')) {
			if ($this->getRequestParameter('fechaFinal')) {
	            $c->add(ClSolicitudPrestamoPeer::FECHA_CREACION,$this->getRequestParameter('fechaInicial'),Criteria::GREATER_THAN);
	            $c->addAnd(ClSolicitudPrestamoPeer::FECHA_CREACION,$this->getRequestParameter('fechaFinal'),Criteria::LESS_THAN);
	            $this->parametros .= "&fechaInicial=" . $this->getRequestParameter('fechaInicial');
	        }else{
			    $c->add(ClSolicitudPrestamoPeer::FECHA_CREACION,$this->getRequestParameter('fechaInicial'),Criteria::GREATER_THAN);
			    $this->parametros .= "&fechaInicial=" . $this->getRequestParameter('fechaInicial');
		    }
	}
	/**************************************************************************************************************/
	    
	
    /**************************************************************************************************************/
  	$pager=new sfPropelPager('ClSolicitudPrestamo',10);
	$pager->setCriteria($c);
	$pager->setPage($this->getRequestParameter('page',1));
	$pager->init();
	$this->pager=$pager;
	$this->filtros_consulta = $parametros;
	$this->usuariologueado = $usuariologueado;
	/**************************************************************************************************************/
  }
   
  public function executeShow()
  {
  	$usuariologuiado = $this->getUser()->getAttribute('usuario_id', '', 'subscriber');
    //$cl_solicitud_prestamo = ClSolicitudPrestamoPeer::retrieveByPk($this->getRequestParameter('clsolicitudprestamo_id'));
    $this->opcion = $this->getRequestParameter('opcion');
    /*
    if($cl_solicitud_prestamo->getClsolicitudprestamoId() == 1 && $cl_solicitud_prestamo->getUsuarioId() == $usuariologuiado){
		$this->solicitada = true;
	}else{
		$this->solicitada = false;
	}
    */	
    $c = new Criteria();
	$c->addJoin(ClDetallePrestamoPeer::CLSOLICITUDPRESTAMO_ID,ClSolicitudPrestamoPeer::CLSOLICITUDPRESTAMO_ID);
	$c->add(ClSolicitudPrestamoPeer::CLIENTE_ID,$this->getRequestParameter('cliente_id'));
	$c->add(ClDetallePrestamoPeer::CLESTADOPRESTAMO_ID,1);
	$this->cl_solicitud_prestamo =  ClDetallePrestamoPeer::doSelectOne($c);
	
	//$this->cl_solicitud_prestamo = $cl_solicitud_prestamo;
	
    $this->forward404Unless($this->cl_solicitud_prestamo);
  }    
  
  public function executeCreate()
  {
    $this->cl_solicitud_prestamo = new ClSolicitudPrestamo();

    $this->setTemplate('edit');
  }
  
  public function executeRechazar()
  {
  	/**************************************************************************************************************/
    $solicitud_prestamo = ClSolicitudPrestamoPeer::retrieveByPk($this->getRequestParameter('clsolicitudprestamo_id'));	
    $solicitud_prestamo->setClsolicitudprestamoestadoId(3);
    $solicitud_prestamo->setFechaAtencion(date("Y-m-d G:i:s"));
    $solicitud_prestamo->save();
	/**************************************************************************************************************/
  }
  
  public function executeAdicionar()
  {
  /**************************************************************************************************************/    $solicitud_prestamo = ClSolicitudPrestamoPeer::retrieveByPk($this->getRequestParameter('clsolicitudprestamo_id'));  /**************************************************************************************************************/
  $solicitud_prestamo = ClSolicitudPrestamoPeer::retrieveByPk($this->getRequestParameter('clsolicitudprestamo_id'));		
  /**************************************************************************************************************/	    $this->getUser()->addCredential('prestamo_cliente');
	$cadSolicitud   = $this->getUser()->getAttribute('solicitud_cliente','','prestamo_cliente');
	if($cadSolicitud == ''){
		$cadSolicitud  .=  $solicitud_prestamo->getClSolicitudprestamoId();		
		$this->getUser()->setAttribute('solicitud_cliente', $cadSolicitud, 'prestamo_cliente');	
	}else{
		$cadSolicitud  .=  ','.$solicitud_prestamo->getClSolicitudprestamoId();		
		$this->getUser()->setAttribute('solicitud_cliente', $cadSolicitud, 'prestamo_cliente');
	}
  /**************************************************************************************************************/  
  }
  
  public function executeAnular()
  {
  /**************************************************************************************************************/
  $solicitud_prestamo = ClSolicitudPrestamoPeer::retrieveByPk($this->getRequestParameter('clsolicitudprestamo_id'));	
  /**************************************************************************************************************/
		
	/*****************************Anular el ID Solicitud De la Session*********************************************/		$cadSolicitud   = $this->getUser()->getAttribute('solicitud_cliente','','prestamo_cliente');					    $cadSolicitud   = $this->getUser()->getAttribute('solicitud_cliente','','prestamo_cliente');
		$this->getUser()->setAttribute('solicitud_cliente', '', 'prestamo_cliente');
		$tempCad = '';
		$arrIds         = split(",",$cadSolicitud);	
		for($i=0; $i<count($arrIds); $i++){			
			if( $arrIds[$i] != $this->getRequestParameter('clsolicitudprestamo_id')){
				if($tempCad == ''){
					$tempCad  .=  $arrIds[$i];		
					$this->getUser()->setAttribute('solicitud_cliente', $tempCad, 'prestamo_cliente');	
				}else{
					$tempCad  .=  ','.$arrIds[$i];		
					$this->getUser()->setAttribute('solicitud_cliente', $tempCad, 'prestamo_cliente');
				}
			}
		}				
	/**************************************************************************************************************/		
  }
  
  public function executeUpdateRadicar()
  {
  	$usuariologuiado = $this->getUser()->getAttribute('usuario_id', '', 'subscriber');
  	$reg = $this->getRegionalFirma($usuariologuiado);  	
  	/*************************************Radicar el prestamo en la base de datos**********************************/
  	$radicar_prestamo = new ClPrestamo();
  	$radicar_prestamo->setClEstadoprestamoId(1);
  	$radicar_prestamo->setUsuarioId($usuariologuiado);
  	$radicar_prestamo->setRegionalId($reg);
  	$radicar_prestamo->setPeriodoId(date("Y"));
  	$radicar_prestamo->setFechaPrestamo(date("Y-m-d"));
  	$radicar_prestamo->setFechaVencimiento($this->getFechaVence());
  	//$radicar_prestamo->setFechaDevolucion();
  	$radicar_prestamo->setObservaciones($this->getRequestParameter('observaciones'));
  	$radicar_prestamo->setConsecutivoRegional($this->formatoRadicar());  	  	
  	$radicar_prestamo->setNumeroRadicacion($this->getNumRadicacion($reg));
  	$radicar_prestamo->save();
  	//$this->setFechaVence($radicar_prestamo->getPrestamoId(),$radicar_prestamo->getFechaPrestamo());
  	/**************************************************************************************************************/
  	
  	/*****************************Radicar los Detalles Del prestamo en la base de datos****************************/
  	$cadSolicitud   = $this->getUser()->getAttribute('solicitud_cliente','','prestamo_cliente');
  	$solicitudes_id = split(",",$cadSolicitud);
  	for($i = 0; $i < count($solicitudes_id); $i++){
	  	//Creas los detalles del prestamo con los ids de las solicitudes.	  				
	  	$detalles_prestamo = new ClDetallePrestamo();
	  	$detalles_prestamo->setClPrestamoId($radicar_prestamo->getClPrestamoId());
	  	$detalles_prestamo->setClEstadoprestamoId(1);
	  	$detalles_prestamo->setClSolicitudprestamoId($solicitudes_id[$i]);
	  	$detalles_prestamo->save();
	  	//Actualiza los estados de la solicitud y la fecha de atencion 
	  	$solicitudes  = ClSolicitudPrestamoPeer::retrieveByPK($solicitudes_id[$i]);
	  	$solicitudes->setClSolicitudprestamoestadoId(2);
	  	$solicitudes->setFechaAtencion(date("y-m-d G:i:s"));
	  	$solicitudes->save();
	}
	
  	/**************************************************************************************************************/  	
  	
  	/***********************Borrar Los IDs De solicitudes en la Variable de sesion*********************************/
  	$this->getUser()->setAttribute('solicitud_cliente', "", 'prestamo_cliente');
  	$this->redirect('solicitud_prestamo_cliente/imprimir?opcion=0&clprestamo_id='.$radicar_prestamo->getClPrestamoId());
  	/**************************************************************************************************************/
  }
  
  public function executeImprimir()
  {
  	$c = new Criteria();
  	$this->opcion = $this->getRequestParameter('opcion');  	
  	
  	$parametros_consulta = '';
	$c->add(ClDetallePrestamoPeer::CLPRESTAMO_ID,$this->getRequestParameter('clprestamo_id'));
	
	/**************************************************************************************************************/
  	$pager=new sfPropelPager('ClDetallePrestamo',10);
	$pager->setCriteria($c);
	$pager->setPage($this->getRequestParameter('page',1));
	$pager->init();
	$this->pager=$pager;
	$this->filtros_consulta = $parametros_consulta;
	/**************************************************************************************************************/  
	
	$resp  = ClDetallePrestamoPeer::doSelect($c);
	foreach($resp as $result){
		$this->nombreSolicitante = $result->getClSolicitudprestamo()->getUsuario();
		break;
	}
	
	$this->prestamo  = ClPrestamoPeer::retrieveByPK($this->getRequestParameter('clprestamo_id'));
	    	
  }
  
  public function executeEdit()
  {
    $this->cl_solicitud_prestamo = ClSolicitudPrestamoPeer::retrieveByPk($this->getRequestParameter('clsolicitudprestamo_id'));
    $this->forward404Unless($this->cl_solicitud_prestamo);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('clsolicitudprestamo_id'))
    {
      $cl_solicitud_prestamo = new ClSolicitudPrestamo();
    }
    else
    {
      $cl_solicitud_prestamo = ClSolicitudPrestamoPeer::retrieveByPk($this->getRequestParameter('clsolicitudprestamo_id'));
      $this->forward404Unless($cl_solicitud_prestamo);
    }
    $usuariologuiado = $this->getUser()->getAttribute('usuario_id', '', 'subscriber');
    $cl_solicitud_prestamo->setClsolicitudprestamoId($this->getRequestParameter('clsolicitudprestamo_id'));
    $cl_solicitud_prestamo->setClienteId($this->getRequestParameter('cliente_id'));
    $cl_solicitud_prestamo->setUsuarioId($usuariologuiado);
    $cl_solicitud_prestamo->setClsolicitudprestamoestadoId(1);    
    $cl_solicitud_prestamo->setFechaCreacion(date("Y-m-d G:i:s"));    
    if ($this->getRequestParameter('fecha_atencion'))
    {
      list($d, $m, $y) = sfI18N::getDateForCulture($this->getRequestParameter('fecha_atencion'), $this->getUser()->getCulture());
      $cl_solicitud_prestamo->setFechaAtencion("$y-$m-$d");
    }

    $cl_solicitud_prestamo->save();

    return $this->redirect($this->getRequest()->getScriptName().'/cliente/show?cliente_id='.$cl_solicitud_prestamo->getClienteId());
  }
  
  public function executeConsulta()
  {
  	$currentForm="solicitud_prestamo_cliente/consulta";
  	$this->verificaPrilegio($currentForm);  	
  	$this->usuarios  = new Usuario();
	$this->estados   = new ClSolicitudPrestamoEstado();  
	
	$this->mostrarUsuario=0;
    if($this->getRequestParameter('mostrarUsuario')==1)
     $this->mostrarUsuario=1;
  	  	
  }
  
  public function executeDelete()
  {
    $cl_solicitud_prestamo = ClSolicitudPrestamoPeer::retrieveByPk($this->getRequestParameter('clsolicitudprestamo_id'));

    $this->forward404Unless($cl_solicitud_prestamo);

    $cl_solicitud_prestamo->delete();

    return $this->redirect($this->getRequest()->getScriptName().'/solicitud_prestamo_cliente/list');
  }
  
  public function getNumRadicacion($regional)
  {
    $periodoActual = date("Y");
    $parametro = ParametroPeer::retrieveByPk(39);
    $formaRad = $parametro->getCodigo();
    $conexion = Propel::getConnection();
    //************************************************************************************
    if ($formaRad == "REG") {
        $consulta = "SELECT MAX(%s) AS max FROM %s where %s=" . $regional . "  and %s=" .$periodoActual . " ";
        $consulta = sprintf($consulta, ClPrestamoPeer::NUMERO_RADICACION, ClPrestamoPeer::TABLE_NAME, ClPrestamoPeer::REGIONAL_ID, ClPrestamoPeer::PERIODO_ID);
    } elseif ($formaRad == "GEN") {
        $consulta = "SELECT MAX(%s) AS max FROM %s where  %s=" . $periodoActual . " ";
        $consulta = sprintf($consulta, ClPrestamoPeer::NUMERO_RADICACION, ClPrestamoPeer::TABLE_NAME, ClPrestamoPeer::PERIODO_ID);
    }
    //************************************************************************************
    $sentencia = $conexion->prepare($consulta);
    $sentencia->execute();
    $resultset = $sentencia->fetch(PDO::FETCH_OBJ);
    return ($resultset->max + 1);
    //************************************************************************************        
  }
  
  public function formatoRadicar()
  {
    $periodoActual = date("Y");
    $usuariologuiado = $this->getUser()->getAttribute('usuario_id', '', 'subscriber');
	$reg = $this->getRegionalFirma($usuariologuiado);    	
    $max = $this->getNumRadicacion($reg);        
    $cad = sprintf("%02d-%05d",$reg, $max);        
    return $cad;
  }
    
  public function getRegionalFirma($userId)
  {
    // consultar regional firmante inicial.
    $firmante = '';
    $c = new Criteria();        
    $c->add(UsuarioPeer::USUARIO_ID, $userId);
    $result = UsuarioPeer::doSelectOne($c);        
    $firmante = $result->getRegionalId();                
    return $firmante;
  }
  
  public function getFechaVence()
  {
  	//calcula la fecha de vencimiento del prestamo segun la dependencia del usuario logueado
	$usuariologuiado = $this->getUser()->getAttribute('usuario_id', '', 'subscriber');
	$usuario  = UsuarioPeer::retrieveByPK($usuariologuiado);
	$dias_prestamo  = $usuario->getDependencia()->getTiempoPrestamo();
	$vence   = AddDays(date("Y-m-d"),$dias_prestamo);
	return $vence;	
  }
}
