<?php
// auto-generated by sfPropelCrud
// date: 2008/11/24 10:05:27
$path_theme = sfConfig::get('theme_simad');
$base_path = sfConfig::get('base_simad');

use_helper('jQuery');
?>
<div class="row">
	<div class="col-md-12">        
        <?php
	    $cantidad_registros = $pager->getNbResults();
	    if($cantidad_registros == 0):
	    ?>
        <div class="panel panel-primary">
		      <div class="panel-heading">
		        <div class="panel-title">Lista De Variables</div>
		      </div>

		      <div class="panel-body">
		      	<div class="alert alert-default"><strong>No existen Registros</strong>, Intente con diferentes filtros de consulta.</div>
	      	  </div>
              
              <!-- Opciones Listar -->
              <hr />
              <div class="row">
            	<div class="col-sm-12 form-group">
                    <a class="btn btn-white btn-sm tooltip-primary" data-toggle="tooltip" data-original-title="Crear nueva variable" href="<?php echo $base_path; ?>/administracion.php/wf_variable/create?wfactividadtransicion_id=<?php echo $sf_params->get('wfactividadtransicion_id'); ?>">
                        <img src="<?php echo $base_path; ?>/images/simad/ico_crear_nuevo.png" width="25" height="25" align="middle" />Crear Variable
                    </a>
                </div>
             </div>
      	</div>        
        <?php
	    else:
	    ?>
        <div class="panel panel-primary">
	      <div class="panel-heading">
	        <div class="panel-title">Lista De Variables</div>
	      </div>
	      <div class="panel-body with-table">              
              <table class="table table-bordered table-hover table-striped responsive">
                  <thead>
                      <tr>
                          <th>Consecutivo</th>
                          <th>Actividad Transicion</th>
                          <th>Nombre</th>
                          <th>Tipo dato</th>
                          <th>Orden</th>
                          <th>Opciones</th>
                      </tr>
                  </thead>
                  <tbody>
                  <?php
                    foreach ($pager->getResults() as $wf_variable): ?>
                    <tr>
                        <td class="text-center"><?php echo str_pad($wf_variable->getWfvariableId(),5, "0",STR_PAD_LEFT); ?></td>
                        <td><?php echo $wf_variable->getWfActividadTransicion()->getWfActividad(); ?></td>
                        <td><?php echo $wf_variable->getNombre() ?></td>
                        <td><?php echo $wf_variable->getWfTipoDato() ?></td>
                        <td><?php echo $wf_variable->getOrden() ?></td>
                        <td class="text-center">
                            <a class="tooltip-primary" href="<?php echo $base_path; ?>/administracion.php/wf_variable/edit?wfvariable_id=<?php echo $wf_variable->getPrimaryKey(); ?>" data-toggle="tooltip" data-original-title="Editar variable">
    	                       <img alt="ir a" width="25" border="=0" src="<?php echo $base_path; ?>/images/simad/ico_editar.png" />
    	                    </a>
                        </td>
                    </tr>                  
                  <?php endforeach; ?>
                  </tbody>
              </table>                  
              <!-- Opciones Listar -->
              <hr />
              <div class="row">
            	<div class="col-sm-12 form-group">
                    <a class="btn btn-white btn-sm tooltip-primary" data-toggle="tooltip" data-original-title="Crear nueva variable" href="<?php echo $base_path; ?>/administracion.php/wf_variable/create?wfactividadtransicion_id=<?php echo $sf_params->get('wfactividadtransicion_id'); ?>">
                        <img src="<?php echo $base_path; ?>/images/simad/ico_crear_nuevo.png" width="25" height="25" align="middle" />Crear Variable
                    </a>
                </div>
             </div>
             <!-- Paginador -->
             <div class="dataTables_wrapper">
                <div class="row">
                    <div class="col-xs-6 col-left">
                      <div class="dataTables_info" id="table-2_info" role="status" aria-live="polite">Mostrando del <?php print $pager->getFirstIndice();?> al <?php print $pager->getLastIndice(); ?> de <?php print $pager->getNbResults();?></div>
                    </div>
                    <div class="col-xs-6 col-right">
                      <div class="dataTables_paginate paging_bootstrap" id="table-2_paginate">
                        <?php
                            echo use_helper('Pagination');
                            echo pager_navigation($pager, 'wf_variable/list', $parametros);
                        ?>
                      </div>
                    </div>
                </div>
             </div>
            <!-- fin  paginacion -->
          </div>
        </div>                      
    <?php endif; ?>
	</div>
</div> 