generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Usuario
    theme:            default
    list:
        display:      [usuario_id, nombre, apellido]
        fields:       [usuario_id, nombre, apellido]
        filters:      [usuario_id, nombre, apellido]
    edit:
        display:      
            "Usuario":   [usuario_id, nombre, apellido, user_name]
            "Clave nueva":     [password, password2]
        fields:  
            nombre:    { type: plain}
            apellido:    { type: plain}
            user_name:    { type: plain}     
            password:
               params:
                  size: 10
                  value: ""
                  type:  password
                  disabled:  false  
            password2:
               params:
                  size: 10
                  value: ""
                  type:  password
                  disabled:  false
        actions:
            _list:     false
            _save:     false
            

