<?php
// auto-generated by sfPropelCrud
// date: 2008/08/06 15:35:23
$path_theme = sfConfig::get('theme_simad');
$base_path = sfConfig::get('base_simad');

$wdg = new wf_widgets();
use_helper('Object','jQuery','UserComponent');
?>
<!-- Imported scripts on this page -->
<script src="<?php echo $path_theme; ?>/assets/js/jquery.multi-select.js"></script>
<link rel="stylesheet" href="<?php echo $path_theme; ?>/assets/css/multi-select.css"/>

<div class="row">
  <div class="col-md-10">
    <!-- Contenedor Pagina -->
    <div class="panel panel-info panel-shadow" data-collapsed="0">
        <div class="panel-heading">
            <div class="panel-title"><strong style="font-size: 12px;">VF RESPUESTAS</strong></div>
        </div>
        <!-- Contenedor Contenido Formulario-->
        <div class="panel-body">
            <?php 
                echo form_tag('com_recibida/index',array('name'=>'form1', 'role' => 'form', 'class' => 'form-horizontal form-groups-bordered validate')); 			
                echo input_hidden_tag('vfasignadosId');
            ?>        
            <div class="form-group">
            	<div class="col-sm-12">
            		<select multiple="multiple" id='listobjectsvf' class="form-control multi-select">
                    <option onselect=""></option>
                    <?php 
                    foreach($list_objects as $item){
                        $selected = "";
                        $item_text = trim($item->getCodigo());
                        $item_title = trim($item->getDescripcion());
                        $item_value = $item->getPrimaryKey(); 
                        //if(trim($item[2])){ $selected = "selected"; }
                        echo '<option value="'.$item_value.'" '.$selected.' class="tooltip-primary" data-toggle="tooltip" data-original-title="'.$item_title.'">'.$item_text.'</option>';
                    }
                    ?>
            		</select>
            	</div>
            </div>
            </form>
        </div>    
    </div>
  </div>
</div>
<script type="text/javascript">
jQuery('.multi-select').multiSelect({
  selectableHeader: "<div class='custom-header'>Vf(s) Disponibles</div>",
  selectionHeader: "<div class='custom-header'>Vf(s) Asignadas</div>",
  afterSelect: function(values){
        var current_list = jQuery('#vfasignadosId').val().split(',');
        //******************************************************************
        current_list.push(values);
        var current_list = current_list.join(",");
        //******************************************************************
        jQuery('#vfasignadosId').val(current_list);
        //console.log(jQuery('#vfasignadosId').val());
        <?php /*echo jq_remote_function(array(
        	'update'    =>'',
        	'url'     => $base_path.'/administracion.php/wf_detalles/addPermByAction',
            'with' => "'wf_actividad_id=' + values + '&wf_transicion_id=".$wf_transicion->getPrimaryKey()."'",
            'loading'  => 'javascript:jQuery.LoadingStructData();',
            'complete'  => "javascript:jQuery.CloseLoadingStructData();",
    		'failure' => "alert('Ocurrio un error realizando el proceso, Por favor intente de nuevo!')",
        ));*/ ?>
  },
  afterDeselect: function(values){
        var current_list = jQuery('#vfasignadosId').val().split(',');
        var removeItem = values;
        //******************************************************************
        var new_list = jQuery.grep(current_list, function(value) {
          return value != removeItem;
        });
        //******************************************************************
        jQuery('#vfasignadosId').val(new_list.join(","));
        //console.log(jQuery('#vfasignadosId').val());
		<?php /*echo jq_remote_function(array(
        	'update'    =>'',
        	'url'     => $base_path.'/administracion.php/wf_detalles/deletePermByAction',
            'with' => "'wf_actividad_id=' + values + '&wf_transicion_id=".$wf_transicion->getPrimaryKey()."'",
            'loading'  => 'javascript:jQuery.LoadingStructData();',
            'complete'  => "javascript:jQuery.CloseLoadingStructData();",
    		'failure' => "alert('Ocurrio un error realizando el proceso, Por favor intente de nuevo!')",
          ));*/ ?>
  }
});
</script>