<?php
// auto-generated by sfPropelCrud
// date: 2008/09/04 15:57:23
?>
<?php use_helper('Object') ?>

<?php echo form_tag('redireccionar/update') ?>

<?php echo object_input_hidden_tag($redireccion, 'getRedireccionId') ?>

<table width="99%" height="134" cellpadding="0" cellspacing="0" align="center">
<caption>
     Editar Redireccionar
</caption>
<tr>
 <td valign="top" >
 <tr> 
  <th height="20" colspan="6" class="nobgLeft" scope="col"></th>
</td>
<td width="135" class="blanco"></td>
</tr>
<tbody>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Estado Redireccion:</th>
  <td colspan="4" class="Color"><?php echo object_select_tag($redireccion, 'getEstadoredireccionId', array (
  'related_class' => 'EstadoRedireccion',
)) ?></td>
</tr>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Motivo:</th>
  <td colspan="4" class="Color"><?php echo object_input_tag($redireccion, 'getMotivo', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Fecha inicial:</th>
  <td colspan="4" class="Color"><?php echo object_input_date_tag($redireccion, 'getFechaInicial', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th width="95" height="20" class="ColorRight" scope="row" nowrap="true">Fecha final:</th>
  <td colspan="4" class="Color"><?php echo object_input_date_tag($redireccion, 'getFechaFinal', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<?php echo submit_tag('save') ?>
<?php if ($redireccion->getRedireccionId()): ?>
  &nbsp;<?php echo link_to('delete', 'redireccionar/delete?redireccion_id='.$redireccion->getRedireccionId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'redireccionar/show?redireccion_id='.$redireccion->getRedireccionId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'redireccionar/list') ?>
<?php endif; ?>
</form>
