<?php
/**
 * Skeleton subclass for representing a row from the 'DOCS_CONTROL_CAMBIO' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Thu Jul 24 15:55:53 2025
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */

 include __DIR__ . '/../PHPDiffText/autoload.php';

use Jfcherng\Diff\Factory\LineRendererFactory;
use Jfcherng\Diff\Renderer\RendererConstant;
use Jfcherng\Diff\SequenceMatcher;
use Jfcherng\Utility\MbString;

class DocsControlCambio extends BaseDocsControlCambio
{
    /**
     * Compara el contenido de esta versión contra la versión actual, párrafo por párrafo: los
     * párrafos sin cambios se muestran con su formato original intacto (centrado, justificado,
     * encabezados en negrita), y solo los que cambiaron se resaltan por palabra dentro de ese
     * mismo formato. Diferenciar el HTML crudo carácter por carácter (sin este paso por bloques)
     * deja que la librería de diff corte justo en medio de una etiqueta y deje markup roto visible
     * en el resultado; diferenciar puro texto plano sin bloques pierde todo el formato visual.
    */
    public function compareVersions($renderType = 'Inline')
    {
        try {
            $current_docversion = DocsControlCambioPeer::getCurrentVersionDoc($this->getConsecutivoId(), $this->getModuloId());

            if (empty($current_docversion) || empty($this)) {
                throw new Exception("Una o ambas versiones no existen");
            }
            //*********************************************************************************************
            $oldContent = $this->getContenidoText();
            $newContent = $current_docversion->getContenidoText();

            if ($oldContent == null || $newContent == null) {
                throw new Exception("Una o ambas versiones no existen");
            }
            //*********************************************************************************************
            $oldBlocks = $this->extraerBloquesParaComparar($oldContent);
            $newBlocks = $this->extraerBloquesParaComparar($newContent);
            //*********************************************************************************************
            $oldTexts = array_map(function ($bloque) { return $bloque['text']; }, $oldBlocks);
            $newTexts = array_map(function ($bloque) { return $bloque['text']; }, $newBlocks);
            //*********************************************************************************************
            if ($oldTexts === $newTexts) {
                return array('diff' => null, 'sin_diferencias' => true, 'wysiwyg_editor' => null);
            }
            //*********************************************************************************************
            $matcher = new SequenceMatcher($oldTexts, $newTexts, null, array('ignoreCase' => false, 'ignoreWhitespace' => false));
            $diff = $this->renderTablaComparacion($matcher->getOpcodes(), $oldBlocks, $newBlocks);
            //*********************************************************************************************
            return array('diff' => $diff, 'sin_diferencias' => false, 'wysiwyg_editor' => null);
        } catch (PropelException $ex) {
            return null;
        } catch (\Exception $ex) {
            return null;
        } catch (\Throwable $ex) {
            return null;
        }
    }

    /**
     * Extrae los párrafos/bloques de un HTML para comparar de a uno, conservando el HTML interno
     * real de cada línea (con sus <strong>/<em> intactos, para mostrarla fiel al original si no
     * cambió) y el estilo del bloque que la contiene (centrado, justificado). <br> y los límites
     * de bloque (p/div/h1-6/li/table) actúan como separadores de línea, sin importar si el texto
     * viene envuelto en su propio párrafo o "suelto" directamente dentro del documento -como pasa
     * en partes de estos documentos, donde no todo el contenido queda dentro de un <div>-.
     */
    private function extraerBloquesParaComparar($html)
    {
        $bloques = array();
        $html = trim((string) $html);
        if ($html === '') {
            return $bloques;
        }
        //*********************************************************************************************
        $dom = new \DOMDocument();
        libxml_use_internal_errors(true);
        $dom->loadHTML('<?xml encoding="utf-8" ?><div id="___raiz___">' . $html . '</div>', LIBXML_NOWARNING | LIBXML_NOERROR);
        libxml_clear_errors();
        //*********************************************************************************************
        $raiz = $dom->getElementById('___raiz___');
        if ($raiz === null) {
            return $bloques;
        }
        //*********************************************************************************************
        $linea = array('html' => '', 'texto' => '', 'estilo' => '');
        $this->recorrerNodo($raiz, $bloques, $linea, false);
        $this->cerrarLinea($bloques, $linea);
        //*********************************************************************************************
        return $bloques;
    }

    /**
     * Recorre recursivamente los nodos acumulando contenido en $linea (la línea/párrafo "en
     * construcción" que se está armando), cerrándola -guardándola como un bloque- cada vez que
     * aparece un <br>, un elemento de bloque (p/div/h1-6/li/ul/ol/blockquote) o una tabla.
     */
    private function recorrerNodo(\DOMNode $nodo, array &$bloques, array &$linea, $dentroDeNegrita)
    {
        static $tagsDeBloque = array('p', 'div', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'li', 'ul', 'ol', 'blockquote');
        static $tagsDeNegrita = array('strong', 'b', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6');
        //*********************************************************************************************
        foreach ($nodo->childNodes as $hijo) {
            if ($hijo->nodeType === XML_TEXT_NODE) {
                if (trim($hijo->textContent) !== '') {
                    $linea['html'] .= htmlspecialchars($hijo->textContent, ENT_QUOTES, 'UTF-8');
                    $linea['texto'] .= $hijo->textContent;
                }
                continue;
            }
            if ($hijo->nodeType !== XML_ELEMENT_NODE) {
                continue;
            }
            $tag = strtolower($hijo->nodeName);
            //*****************************************************************************************
            if ($tag === 'br') {
                $this->cerrarLinea($bloques, $linea);
                continue;
            }
            if ($tag === 'table') {
                $this->cerrarLinea($bloques, $linea);
                $htmlTabla = (string) $hijo->ownerDocument->saveHTML($hijo);
                $bloques[] = array('isTabla' => true, 'html' => $htmlTabla, 'text' => 'TABLA:' . md5($htmlTabla));
                continue;
            }
            //*****************************************************************************************
            $esNegritaAqui = $dentroDeNegrita || in_array($tag, $tagsDeNegrita, true);
            //*****************************************************************************************
            if (in_array($tag, $tagsDeBloque, true)) {
                // Un elemento de bloque siempre empieza una línea nueva, tenga o no texto propio
                // directo (si solo envuelve otros bloques, esto simplemente cierra una línea vacía,
                // que no se guarda) y hereda el estilo del bloque mientras se procesa su contenido.
                $this->cerrarLinea($bloques, $linea);
                $linea['estilo'] = $hijo->hasAttribute('style') ? $hijo->getAttribute('style') : '';
                $this->recorrerNodo($hijo, $bloques, $linea, $esNegritaAqui);
                $this->cerrarLinea($bloques, $linea);
                $linea['estilo'] = '';
                continue;
            }
            //*****************************************************************************************
            // Elemento en línea (strong, em, span, etc.): se conserva tal cual en el HTML de la línea
            // -salvo atributos como colores de resaltado, que no son el foco aquí-, para que un bloque
            // sin cambios se muestre fiel al original en vez de perder su negrita/cursiva puntual.
            if (in_array($tag, array('strong', 'b', 'em', 'i'), true)) {
                $linea['html'] .= '<' . $tag . '>';
                $this->recorrerNodo($hijo, $bloques, $linea, $esNegritaAqui);
                $linea['html'] .= '</' . $tag . '>';
            } else {
                $this->recorrerNodo($hijo, $bloques, $linea, $esNegritaAqui);
            }
        }
    }

    /**
     * Guarda $linea como un bloque (si tiene texto) y la reinicia para la siguiente. El estilo se
     * conserva tal cual estaba (lo fija/limpia recorrerNodo() al entrar/salir de un bloque real),
     * para que varias líneas separadas por <br> dentro de un mismo párrafo compartan su estilo.
     */
    private function cerrarLinea(array &$bloques, array &$linea)
    {
        $texto = html_entity_decode($linea['texto'], ENT_QUOTES, 'UTF-8');
        $texto = str_replace("\xc2\xa0", ' ', $texto); // &nbsp; decodificado, no lo reconoce trim()
        $texto = trim(preg_replace('/\s+/', ' ', $texto));
        if ($texto !== '') {
            $bloques[] = array(
                'isTabla' => false,
                'style' => $linea['estilo'],
                'html' => trim(preg_replace('/\s+/', ' ', $linea['html'])),
                'bold' => (bool) preg_match('#^<(strong|b)>.*</\1>$#s', trim($linea['html'])),
                'text' => $texto,
            );
        }
        $linea['html'] = '';
        $linea['texto'] = '';
    }

    /**
     * Resalta, palabra por palabra, las diferencias entre dos líneas de texto -reutilizando el
     * mismo renderizador de palabras que usa la librería de diff- y devuelve cada lado ya con
     * <ins>/<del> en las palabras puntuales que cambiaron.
     *
     * @return array{0: string, 1: string} [textoViejoMarcado, textoNuevoMarcado]
     */
    private function marcarDiferenciaPorPalabra($textoViejo, $textoNuevo)
    {
        $mbViejo = new MbString(htmlspecialchars($textoViejo, ENT_QUOTES, 'UTF-8'));
        $mbNuevo = new MbString(htmlspecialchars($textoNuevo, ENT_QUOTES, 'UTF-8'));
        //*********************************************************************************************
        LineRendererFactory::make('word', array(), array('wordGlues' => array(' ', '-')))->render($mbViejo, $mbNuevo);
        //*********************************************************************************************
        $viejoMarcado = str_replace(RendererConstant::HTML_CLOSURES, RendererConstant::HTML_CLOSURES_DEL, $mbViejo->get());
        $nuevoMarcado = str_replace(RendererConstant::HTML_CLOSURES, RendererConstant::HTML_CLOSURES_INS, $mbNuevo->get());
        //*********************************************************************************************
        return array($viejoMarcado, $nuevoMarcado);
    }

    /**
     * Arma la tabla HTML de diferencias a partir de los opcodes de SequenceMatcher, mostrando
     * cada bloque con su propio formato (estilo/negrita) en vez del formato genérico del
     * renderizador de la librería.
     */
    private function renderTablaComparacion(array $opcodes, array $oldBlocks, array $newBlocks)
    {
        $html = '<table class="diff-wrapper diff diff-html diff-combined"><thead><tr><th>Diferencias</th></tr></thead>';
        //*********************************************************************************************
        foreach ($opcodes as list($tag, $i1, $i2, $j1, $j2)) {
            if ($tag === SequenceMatcher::OP_EQ) {
                for ($k = $i1; $k < $i2; $k++) {
                    $html .= $this->renderBloqueComparado($newBlocks[$j1 + ($k - $i1)], null, 'eq', 'new');
                }
            } elseif ($tag === SequenceMatcher::OP_DEL) {
                for ($k = $i1; $k < $i2; $k++) {
                    $html .= $this->renderBloqueComparado($oldBlocks[$k], null, 'del', 'old');
                }
            } elseif ($tag === SequenceMatcher::OP_INS) {
                for ($k = $j1; $k < $j2; $k++) {
                    $html .= $this->renderBloqueComparado($newBlocks[$k], null, 'ins', 'new');
                }
            } else {
                // OP_REP: puede haber distinta cantidad de párrafos viejos y nuevos en el bloque
                // reemplazado; se emparejan de a uno y el resto se muestra como inserción/eliminación.
                $oldCount = $i2 - $i1;
                $newCount = $j2 - $j1;
                $max = max($oldCount, $newCount);
                for ($k = 0; $k < $max; $k++) {
                    $oldBlock = $k < $oldCount ? $oldBlocks[$i1 + $k] : null;
                    $newBlock = $k < $newCount ? $newBlocks[$j1 + $k] : null;
                    if ($oldBlock !== null && $newBlock !== null && !$oldBlock['isTabla'] && !$newBlock['isTabla']) {
                        list($oldMarcado, $newMarcado) = $this->marcarDiferenciaPorPalabra($oldBlock['text'], $newBlock['text']);
                        $html .= $this->renderBloqueComparado($oldBlock, $oldMarcado, 'rep', 'old');
                        $html .= $this->renderBloqueComparado($newBlock, $newMarcado, 'rep', 'new');
                    } elseif ($oldBlock !== null && $newBlock !== null) {
                        // Una tabla cambió (ej. el bloque de firmas): se muestran ambas versiones
                        // completas -vieja y nueva-, sin intentar resaltar palabra por palabra dentro.
                        $html .= $this->renderBloqueComparado($oldBlock, null, 'rep', 'old');
                        $html .= $this->renderBloqueComparado($newBlock, null, 'rep', 'new');
                    } elseif ($oldBlock !== null) {
                        $html .= $this->renderBloqueComparado($oldBlock, null, 'del', 'old');
                    } elseif ($newBlock !== null) {
                        $html .= $this->renderBloqueComparado($newBlock, null, 'ins', 'new');
                    }
                }
            }
        }
        //*********************************************************************************************
        return $html . '</table>';
    }

    /**
     * Renderiza una fila de la tabla de diferencias para UN bloque/párrafo, conservando su
     * estilo original (y negrita si corresponde). $contenidoMarcado ya viene con <ins>/<del>
     * cuando aplica, o null para mostrar el texto del bloque tal cual (ya escapado).
     */
    private function renderBloqueComparado(array $bloque, $contenidoMarcado, $tipoCambio, $claseCelda)
    {
        if ($bloque['isTabla']) {
            // Las tablas se muestran íntegras, con su HTML original (filas/columnas intactas),
            // nunca aplanadas a texto ni resaltadas por palabra.
            return '<tbody class="change change-' . $tipoCambio . '">' .
                '<tr><td class="' . $claseCelda . '">' . $bloque['html'] . '</td></tr>' .
            '</tbody>';
        }
        //*********************************************************************************************
        $estilo = trim($bloque['style']);
        if ($bloque['bold']) {
            $estilo = ($estilo === '' ? '' : rtrim($estilo, '; ') . '; ') . 'font-weight: bold;';
        }
        //*********************************************************************************************
        $contenido = $contenidoMarcado !== null ? $contenidoMarcado : $bloque['html'];
        //*********************************************************************************************
        return '<tbody class="change change-' . $tipoCambio . '">' .
            '<tr><td class="' . $claseCelda . '" style="' . htmlspecialchars($estilo, ENT_QUOTES, 'UTF-8') . '">' . $contenido . '</td></tr>' .
        '</tbody>';
    }
}
