<?php



/**
 * Skeleton subclass for performing query and update operations on the 'EXPEDIENTE_ETIQUETA' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * lun 20 oct 2025 17:05:29
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ExpedienteEtiquetaPeer extends BaseExpedienteEtiquetaPeer
{
    public static function getExpedienteEtiquetasByModulo($modulo_id = null, $isAsigned = false, $esta_activo = 1)
    {
        try {
            $c = new Criteria();
            //***************************************************************************************
            if($isAsigned){ $c->addJoin(ExpedienteEtiquetaPeer::EXPEDIENTEETIQUETA_ID,ExpedienteReglaEtiquetaPeer::EXPEDIENTEETIQUETA_ID,Criteria::INNER_JOIN); }
            //***************************************************************************************
            $c->add(ExpedienteEtiquetaPeer::MODULO_ID,$modulo_id);
            $c->add(ExpedienteEtiquetaPeer::ESTA_ACTIVO,$esta_activo);
            //***************************************************************************************
            $c->addAscendingOrderByColumn(ExpedienteEtiquetaPeer::NOMBRE_INTERNO);
            return ExpedienteEtiquetaPeer::doSelect($c);
        } catch (PropelException $th) {
            return array();
        } catch (\Exception $th) {
            return array();
        } catch (\Throwable $th) {
            return array();
        }
    }

    public static function getFieldNamesByClass($modulo_pk, $loadForeingPk = true)
    {   
        try {
            if($modulo_pk == ModulesEnable::ComEnviada){
                $clasename_main = ComEnviadaPeer::getOMClass();
            }elseif ($modulo_pk == ModulesEnable::ComRecibida) {
                $clasename_main = ComRecibidaPeer::getOMClass();
            }elseif ($modulo_pk == ModulesEnable::ComInterna) {
                $clasename_main = ComInternaPeer::getOMClass();
            }else{
                $clasename_main = null;
            }
            //***********************************************************************************************

            if(empty($clasename_main)){
                $response_info['status'] = 300;
                $response_info['message'] = "El modulo seleccionado no esta habilitado";
                return $response_info;
            }
            //***********************************************************************************************
            $peername_main = sprintf("%sPeer",$clasename_main);
            //***********************************************************************************************
            $tableMap = $peername_main::getTableMap();
            $current_table = $tableMap->getClassName();
            //***********************************************************************************************
            $listCustom = array();
            $tableColumns = $tableMap->getColumns();
            foreach($tableColumns as $row)
            {
                if(!empty($row->getRelatedTableName()) && $loadForeingPk === true)
                {
                    $relClassName = str_replace(" ","",ucwords(strtolower(str_replace("_"," ",$row->getRelatedTableName()))));
                    $relPeerClass = sprintf("%sPeer",$relClassName);
                    $relTableMap = $relPeerClass::getTableMap();
                    foreach ($relTableMap->getColumns() as $relCol) 
                    {
                        if(!$relCol->isPrimaryKey() && empty($relCol->getRelatedTableName()))
                        {
                            $tableNameInit = sprintf("%s.%s", $relTableMap->getPhpName(), $relCol->getPhpName());
                            $listCustom[] = array('id'=>md5($tableNameInit),'text'=>$tableNameInit);
                        }
                    }
                }
                else
                {
                    $tableNameInit = sprintf("%s.%s", $current_table, $row->getPhpName());
                    $listCustom[] = array('id' => SED::encryption($tableNameInit),'text' => $tableNameInit);
                }
            }
            //***********************************************************************************************
            return $listCustom;
        } catch (PropelException $th) {
            return array();
        } catch (\Exception $th) {
            return array();
        } catch (\Throwable $th) {
            return array();
        }
    }
}
