<?php



/**
 * Skeleton subclass for representing a row from the 'TIPO_CIERRE_EXPEDIENTE' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Tue Apr 29 17:04:21 2025
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TipoCierreExpediente extends BaseTipoCierreExpediente
{
}
