; habilitar modulos y funcionalidades especiales SIMAD
[version_aplicacion]
application_current_version = 6.0.158
[menu_aplicacion]
mod_actos_administrativos = 1
mod_control_contratistas = 0
com_interna_advance_create = 0
com_enviada_advance_create = 1
acto_administrativo_advance_create = 1
com_enviada_formato_factura = 0
mod_control_clientes  = 0
mod_control_contratistas  = 0
mod_documentacion_tecnica = 0
com_recibida_por_responder = 1
com_recibida_batch_create = 1
mod_correo_electonico = 1
[email_novedad_jefe]
; correos separados por comas a donde se notifica cuando un usuario deshabilitado por LDAP/AD
; tiene actividades pendientes pero no hay jefe de dependencia (RECEPTOR_DEP=1) activo o bloqueado
; configurado para reasignarlas automaticamente
email_novedad_jefe = javier.charry@aureasas.com,javier.charry@unidadvictimas.gov.co
[acceptedFiles_upload]
mtypes = image/*,.jpeg,.jpg,.png,.gif,.JPEG,.JPG,.PNG,.GIF,.TIF,.TIFF,.tif,.pdf,.tiff,.zip,.7z,.rar,application/pdf,.psd,.xls,.doc,.dat,.ppt,.msg,.mso,.xlsx,.docx,.pptx,.txt,.3gp,.mp3,.avi,.dwg,.wmv,.wav,.mp4,.m4v,.mov,.mpg,.mpeg,.mid,.midi,.gdb
[limit_read_spout]
limit_read_spout = 2500
[app_parameters]
java_jdk = C:\Program Files\Microsoft\jdk-17.0.5.8-hotspot\bin
[security_parameters]
com_enviada_watermark = 1
com_interna_watermark = 1
com_recibida_watermark = 1
archivo_contdocs_watermark = 1
keyprivate_watermark = MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqKFw77w5Mk8uBfPcJOjyCl5rh/uWDqIR9b1oPhQFdqAIW+Qa7oTl/t++XNFz0BDk08/m3c9umy8H8zrty8VjHFjPxUFMqrIGtpYJNKpHoitcNrUCiO2uJiLlbVp0I9MOypMax6C+3Mwj9x1/y1m283/g/WZKkTCAUUm1FITzI6QIDAQAB
keyprivate_svc_password = MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqKFw77w5Mk8uBfPcJOjyCl5rh/uWDqIR9b1oPhQFdqAIW+Qa7oTl/t++XNFz0BDk08/m3c9umy8H8zrty8VjHFjPxUFMqrIGtpYJNKpHoitcNrUCiO2uJiLlbVp0I9MOypMax6C+3Mwj9x1/y1m283/g/WZKkTCAUUm1FITzI6QIDAQAB
[modulos_auditoria]
audit_administracion = 1
audit_apoyo_usuario = 1
audit_archivo = 1
audit_backend = 1
audit_clientes = 1
audit_comun = 1
audit_documentacion = 1
audit_com_enviada = 1
audit_com_interna = 1
audit_com_recibida = 1
audit_servicios = 1
audit_facturas = 1
audit_proveedores = 1
audit_procedimientos = 1
audit_workflow = 1
[sticker_comunicaciones]
; opciones: QR | CODEBAR
com_enviada_sticker = QR 
com_interna_sticker = QR 
com_recibida_sticker = QR
acto_administrativo_sticker = QR
[parametros_oficina_virtual]
max_file_size = 20 ;hace referencia maximo permitido por archivo en Mb
digit_mtypes = application/pdf,application/msg,image/tif,image/tiff
attachments_mtypes = image/jpeg,image/png,application/pdf,application/msword,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.wordprocessingml.document
url_virtual = /oficina_virtual?hashcom
[parametros_correo_certificado]
;donde se archiva el acta del correo certificado opciones radicado||expediente||servicio;
archivar_acta_com_enviada = radicado
[parametros_correo_fisico_certificado]
;donde se archiva el acta del correo fisico certificado opciones radicado||expediente||servicio;
archivar_acta_guia_com_enviada = radicado
[archivo_estampa_ocr]
;app_cli_command = ocrmypdf -l eng+spa --rotate-pages --deskew --output-type pdfa-3 "$fname" "$fname"
ocr_engine_cli_command = C:/Users/simad/AppData/Local/Programs/Python/Python311/Scripts/ocrmypdf.exe
ghostscript_engine_cli_command = C:/Users/simad/AppData/Local/Programs/gs/gs10.03.1/bin/gswin64.exe
ocr_engine_cli_arguments = -l eng+spa --rotate-pages --deskew --force-ocr --output-type pdfa-3
;stamp_engine_cli_command = C:/Users/simad/AppData/Local/Programs/Python/Python311/Scripts/ocrmypdf.exe
;stamp_engine_cli_arguments = -l eng+spa --rotate-pages --deskew --output-type pdfa-3
[verapdf_cli_command]
verapdf_cli_command_path = C:/Users/simad/AppData/Local/verapdf/verapdf.bat
[pdftk_cli_command]
pdftk_cli_command_path = C:/inetpub/wwwroot/sgdeapruebas/lib/pdftk/pdftk.exe
[exiftool_cli_command]
exiftool_cli_command_path = C:/inetpub/wwwroot/sgdeapruebas/lib/exiftool-13.35_64/exiftool.exe
[params_enlaces_modal]
; opciones: MODAL | BLANK
tipo_enlace = MODAL
[params_notify_inline]
; opciones: YES | NO
; opciones: 1 | 0
notify_inline = 1
margin_time = 5
[params_certimail]
certimail_enable = false
[correo_cert_enable]
correo_cert_fisico_enable = true
[params_certifisiconal]
certifisiconal_enable = false
[correspondencia_module]
app_automatice_expediente = true
[email_radicar]
email_attach_eml = true
[params_email_sync]
domains_enable = unidadvictimas.gov.co
;ubicaciones fisicas paths
[ruta_default]
ruta_default[] = E:/Archidhu/files/
ruta_default[] = E:/Archidhu/files/Clientes/

[alias_default]
alias_default[] = /digit_actosadm/
alias_default[] = /digit_archivo/
alias_default[] = /digit_clientes/
alias_default[] = /digit_documentacion/
alias_default[] = /digit_enviada/
alias_default[] = /digit_interna/
alias_default[] = /digit_manualesTecnicos/
alias_default[] = /digit_recibida/
alias_default[] = /digit_servicios/
alias_default[] = /Imagenes/
alias_default[] = /marcxml/
alias_default[] = /Adjuntos/digit_documentacion/

[ruta_archivo]
ruta_archivo[] = E:/Archidhu/files/

[alias_archivo]
alias_archivo[] = /digit_archivo/
;bloque mensajeria
[mensajeria_settings]
mensajeria_items[valija] = 5
mensajeria_items[correo_nacional] = 2
mensajeria_items[mensajeria_local] = 13
[timer_submit]
limit_timer_submit = 30
[campos_metadatos_bd]
;debe ser el nombre del metodo sin el get
campos_metadatos_bd[] = ASUNTO
campos_metadatos_bd[] = FOLIOS
campos_metadatos_bd[] = TIPOCOMRECIBIDA_ID
campos_metadatos_bd[] = COM_RECIBIDA[COMRECIBIDA_ID].COMRECIBIDA_INTERESADOS[INTERESADO_ID].INTERESADOS.PRIMER_NOMBRE
campos_metadatos_bd[] = COM_RECIBIDA[COMRECIBIDA_ID].COMRECIBIDA_INTERESADOS[INTERESADO_ID].INTERESADOS.PRIMER_APELLIDO
campos_metadatos_bd[] = COM_RECIBIDA[COMRECIBIDA_ID].COMRECIBIDA_INTERESADOS[INTERESADO_ID].INTERESADOS.NUMERO_IDENTIFICACION
campos_metadatos_bd[] = COM_RECIBIDA[COMRECIBIDA_ID].COMRECIBIDA_INTERESADOS[INTERESADO_ID].INTERESADOS.TIPO_IDENTIFICACION.TIPOIDENTIFICACION_ID
[automatizacion_modules_enabled]
;automatizacion_modules[2] = 'Comunicaciones Internas'
automatizacion_modules[3] = 'Comunicaciones Recibidas'
;automatizacion_modules[4] = 'Comunicaciones Enviadas'
[distribuidor_regional_destino]
distribuidor_regional_area_pk = 21
[domain_controllers]
domain_controllers[] = 30.0.1.4
[convertir_word_to_pdf]
;libreoffice|PhpWord
strategy_gen_word_to_pdf = libreoffice
soffice_cli_command_path = C:\LibreOfficePortable\App\libreoffice\program\soffice.exe
[rmail_config]
rmail_enable_service = true
rmail_base_url = https://webapi.r1.rpost.net
rmail_app_id = 0
rmail_username = servicioalciudadano@unidadvictimas.gov.co
rmail_password = Unidad2026*
rmail_client_id = 0
rmail_receipts_path = E:/Archidhu/files/correocertificado/
rmail_from = servicioalciudadano@unidadvictimas.gov.co
rmail_test_env = true
[providers_certi_email]
;RMail o Andes
provider_certi_email_enable = RMail