dev:
  propel:
    param:
      classname:  DebugPDO
      debug:
        realmemoryusage: true
        details:
          time:       { enabled: true }
          slow:       { enabled: true, threshold: 0.1 }
          mem:        { enabled: true }
          mempeak:    { enabled: true }
          memdelta:   { enabled: true }
all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        'sqlsrv:server=30.0.1.75;Database=DBSIMAD5;MultipleActiveResultSets=false'
      username:   dbsimad5
      password:   Q4t4r21
      encoding:   utf-8
      persistent: true
      pooling:    true