<?php
// auto-generated by sfPropelCrud
// date: 2008/07/15 17:22:01
header("Content-type: application/vnd.ms-excel");
header("Content-disposition: attachment; filename=resultado.xls"); 
?>
<table cellspacing="0" border="1">
<tr>
<th>Prestamos: </th>
<td><?php echo $userName ?></td>
</tr>
<tr>
<th>Fecha: </th>
<td><?php echo date("Y-m-d") ?></td>
</tr>
<tr>
<th>Hora: </th>
<td><?php echo date("G:i:s") ?></td>
</tr>
<tr>
<th>Enviado Por: </th>
<td><?php echo $userName ?></td>
</tr>
</table>
<br>
<table cellspacing="0" width="98%" align="center" border="1">
<body>
<h1 align="center">
   Lista De Prestamos 
</h1>
<thead>
<tr>
  <th>Consecutivo:</th>  
  <th>Nombre Archivo:</th>
  <th>Codigo Barras:</th>
  <th>Serie:</th>
  <th>Subserie:</th>
  <th>Prestado A:</th>  
  <th>Fecha prestamo</th>
  <th>Fecha vencimiento</th>
  <th>Fecha devolucion</th>
  <th>Prestado Por:</th>
  <th>Estado</th>    
</tr>
</thead>
<tbody>
<?php
    $i = 0;     	
	while($object = $prestamo->fetch()): ?>
<tr>
    <th align="center"><?php echo $object[0].'&nbsp;' ?></th>
    <td align="center"><?php echo $object[1].'&nbsp;' ?></td>
    <td align="center"><?php echo $object[2].'&nbsp;' ?></td>
    <td align="center"><?php echo $object[3].'&nbsp;' ?></td>
    <td align="center"><?php echo $object[4].'&nbsp;' ?></td>
    <td align="center"><?php echo $object[5].'&nbsp;' ?></td>         
    <td align="center"><?php echo $object[6].'&nbsp;' ?></td>
    <td align="center"><?php echo $object[7].'&nbsp;' ?></td>
    <td align="center">
    <?php 
    if($object[8].'&nbsp;'!= ''){ 
	   echo $object[8].'&nbsp;';
	}else{
	   echo '0000-00-00';
	}
    ?>
    </td>
    <td align="center"><?php echo $object[9].' '.$object[10].'&nbsp;' ?></td>
    <td align="center"><?php echo $object[11].'&nbsp;' ?></td>	   
  </tr>
<?php 
$i++;
endwhile; ?>
</tbody>
</table>
</form>