generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Usuario
    theme:            default
    edit:
         display: [usuario_id, user_name, apellido, nombre, email, usuario_privilegio] 
         fields:
             user_name:        { type: plain }
             apellido:         { type: plain }
             nombre:           { type: plain }
             email:            { type: plain }
             usuario_privilegio:     { type: admin_double_list, params: through_class=UsuarioPrivilegio }
          

