<?php
// auto-generated by sfPropelCrud
// date: 2009/04/20 12:39:12
$path_theme = sfConfig::get('theme_simad');
$base_path = sfConfig::get('base_simad');

use_helper('Object');
?>
<div class="row">
  <div class="col-md-12">
    <!-- Contenedor Pagina -->
    <div class="panel panel-gradient" data-collapsed="0">

      <div class="panel-heading">
        <div class="panel-title">
          Consultar Proveedor
        </div>        
      </div>
      <!-- Contenedor Contenido Formulario-->
      <div class="panel-body">
        <?php 
        echo form_tag('proveedor/escogelist', array('name'=>'form1', 'method' => 'GET', 'role' => 'form', 'class' => 'form-horizontal form-groups-bordered validate'));
        echo input_hidden_tag('opcion',$opcion); 
        echo input_hidden_tag('campoId',$campoId);
        echo input_hidden_tag('campoText',$campoText);
        ?>      
        <div class="form-group">  
          <!-- Codigo de Barras -->  
          <label for="lbnombre" class="col-sm-1 control-label">Nombre:</label>
          <div class="col-sm-4">
            <?php 
            echo object_input_tag($proveedor, 'getNombre', array('class'=>'form-control input-sm'));
            ?>
          </div>
        
          <!-- Nit -->
          <label for="lbnit" class="col-sm-1 control-label">Nit:</label>
          <div class="col-sm-4">
            <?php 
            echo object_input_tag($proveedor, 'getNit', array('class'=>'form-control input-sm'));
            ?>
          </div>        
        </div>
        
        <div class="form-group">  
          <!-- Representante legal -->  
          <label for="lbRepresentantelegal" class="col-sm-1 control-label">Representante legal:</label>
          <div class="col-sm-4">
            <?php 
            echo object_input_tag($proveedor, 'getRepresentanteLegal', array('class'=>'form-control input-sm'));
            ?>
          </div>
        
          <!-- Nit -->
          <label for="lbIdentificacionrl" class="col-sm-1 control-label">Identificacion rl:</label>
          <div class="col-sm-4">
            <?php 
            echo object_input_tag($proveedor, 'getIdentificacionRl', array('class'=>'form-control input-sm'));
            ?>
          </div>        
        </div>
        
        <div class="form-group">  
          <!-- Direccion -->  
          <label for="lbDireccion" class="col-sm-1 control-label">Direccion:</label>
          <div class="col-sm-4">
            <?php 
            echo object_input_tag($proveedor, 'getDireccion', array('class'=>'form-control input-sm'));
            ?>
          </div>
        
          <!-- Telefono -->
          <label for="lbIdentificacionrl" class="col-sm-1 control-label">Telefono:</label>
          <div class="col-sm-4">
            <?php 
            echo object_input_tag($proveedor, 'getTelefono', array('class'=>'form-control input-sm'));
            ?>
          </div>        
        </div>
        
        <div class="form-group">  
          <!-- Naturaleza juridica -->  
          <label for="lbNaturalezajuridica" class="col-sm-1 control-label">Naturaleza juridica:</label>
          <div class="col-sm-4">
            <?php 
            echo object_input_tag($proveedor, 'getNaturalezaJuridica', array('class'=>'form-control input-sm'));
            ?>
          </div>
        </div>
      <div class="form-group">
          <!-- Botonera -->
          <div class="col-sm-offset-4 col-sm-5">
            <button type="submit" class="btn btn-blue btn-icon">Consultar<i class="entypo-search"></i></button>
            <?php echo button_to('Deshacer','proveedor/consulta?opcion='.$opcion.'&campoText='.$campoText.'&campoId='.$campoId,array('class' => 'btn btn-red')); ?>
          </div>
      </div>
      <div class="clear"></div>
      </form>
        </div>
      </div>
    </div>
</div>